### ISSUE TITLE
Code block support

### ISSUE THREAD

**Issue by tmr232** [wereturtle/ghostwriter#102]
Currently, the editor only seems to handle inline \`code\`. When I try to input multi-line code blocks, I get weird results as the editor recognizes the \`\`\` pattern as an open-close-open sequence. 
I would be happy to see code-block support added to the editor.

**Comment by nonplayer** [comment]
Is this universal to all flavors of Markdown?

When I attempt to replicate this, my code blocks display differently in the preview based on which flavor of markdown I select. Oddly, some portray them properly, others not at all, and others as a single-line jumble.

**Comment by tmr232** [comment]
I am not sure that it is universal (it does not appear in https://daringfireball.net/projects/markdown/syntax#code), but it is very very common.
It is supported on Github, StackOverflow, and pandoc. I believe that most recent implementations support it. 
For me, in any case, it is really hard to work without it.

**Comment by wereturtle** [comment]
Multi-line code blocks are typically inserted by using tab characters or four spaces at the front of the paragraph/line.  It's best also to have a blank line between the code block and the preceding/succeeding paragraphs.  As far as rendering in the preview goes, your results will vary based on the Markdown processor you have chosen.  You will have to study up on your favorite processor's particular flavoring to know for sure how it will look.
