### ISSUE TITLE
Close HTML preview via hotkey

### ISSUE THREAD

**Issue by tmr232** [wereturtle/ghostwriter#104]
When in fullscreen mode, I sometimes pop up the HTML preview by clicking <kbd>Ctrl</kbd><kbd>W</kbd>, take a look, then close it again. It would be nice if the same hotkey would be used to close the preview as well.

**Comment by nonplayer** [comment]
For the record, this is already addressed in #93

**Comment by wereturtle** [comment]
Even though it's just like #93, I'll keep it open to make sure I remember to do the work for the HTML preview as well.

**Comment by wereturtle** [comment]
Oh, never mind.  Issue #93 already references the HTML preview.  I'll close this one as a duplicate.
