### ISSUE TITLE
Incorrect repeat transition between maximize and Full screen modes in Windows 7

### ISSUE THREAD

**Issue by DeFabro** [wereturtle/ghostwriter#107]
I noticed incorrect repeat transition between maximize and Full screen modes in Windows 7 (need to test in Win 8,10)

Environment: Windows 7 SP1 (x64)

Steps to reproduce the issue:
1. Launch ghostwriter.
2. Click the "Maximized" button.
3. Press "F11" to enter Full screen mode.
4. Press "F11" to exit Full screen mode.
5. Press "F11" to enter Full screen mode again.

Expected results: ghostwriter displays correctly in Full screen mode.
Actual results: ghostwriter displays incorrectly in Full screen mode. It is hard to explain, see the screenshot:

![bug](https://cloud.githubusercontent.com/assets/7831856/17111970/911fae00-52ac-11e6-8047-7eeab923cca0.png)

**Comment by tmr232** [comment]
I have similar errors on Windows 10.

**Comment by wereturtle** [comment]
Confirmed.  Good catch!
