### ISSUE TITLE
Tasks starting with * instead of - not handled correctly

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#108]
Tasks with \* don't work the same as task starting with a  - (hyphen).  This is after updating to 1.4.0 and turning `*` off in Matched characters.

As an example, if I have

```
* [ ] item 1
* [ ] item 2
```

and I position the cursor on "item 1" and hit enter I get an \* added without the [ ]

But when I do the same on an item that's 
`- [ ] item 1`

I get 
`- [ ]`

Also, on a line that starts with an `*`, hitting Ctrl-T turns it into 
`- [ ] *`  instead of `* [ ]` ... note the extra \* after the [ ].

It seems like \* isn't really a first-class citizen.

**Comment by wereturtle** [comment]
Sorry about that.  The Github documentation didn't give any indication that other bullet point styles were supported for tasks.  I'll be sure to put this one in for the next major release.

**Comment by jeff9315** [comment]
Thanks!! You're awesome!
