### ISSUE TITLE
Another issue with * at beginning of line

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#109]
When I have a `-` at he beginning of the line and I try to over-type it with an `*`, I get `*-*` instead of just a single `*`. This is after updating to 1.4.0 and turning `*` off in Matched characters.

**Comment by wereturtle** [comment]
Actually, that's working as intended.  But since the feature is getting in the way, I'll add an option to the settings menu to turn off inserting paired characters for selected text.

**Comment by jeff9315** [comment]
Thanks again!!

**Comment by wereturtle** [comment]
Instead of adding another option to the preferences, I had the automatching for the text selection respect the existing preferences for the matching done while typing without text selected.  I hope that works for you.
