### ISSUE TITLE
In "Emacs Org mode" as you type simple markups, it renders bold,italic,url,list etc in the input window itself , like WYSIWYG

### ISSUE THREAD

**Issue by zaxebo1** [wereturtle/ghostwriter#11]
I reached here from commonmark updates email list.
Sorry , i have not tried installing this cute looking editor yet, I am writing based on the perception of the screenshots. I will install it on weekend, after auditing the source code.

***

suggestion / question:

Although org-mode is a lightweight markup language,just like markdown. But when you use it in Emacs editor, it almost works as **WYSIWYG**
see  https://www.youtube.com/watch?v=fgizHHd7nOo

***

in ghostwriter and many other markdown editors, i type in one window and it renders in another window. Thats fine. BUT atleast in case of bold , url and other small markups it should also be rendered in the entry window.
That is if i type  \*\*my bold text\*\*  , then it should be rendered as bold in the "entry window" itself (not just in second output window). It will show the surrounding asterisks \*\* but still it will also make the text bold. That is, it is "almost WYSIWYG"

==============

**Comment by zaxebo1** [comment]
org-mode for outline https://www.youtube.com/watch?v=_TmMdMenM1A
(see the 'list outline heirarchy' itself as i type in the same  window, not in the other window. Fold and unfold this list in the window, where the text exists, not in some other window)

**Comment by wereturtle** [comment]
Hi zax,

Thanks for the feedback.  ghostwriter does bold text as you type, but it will leave the asterisks intact, just like Byword or other OS X Markdown editors do.  It will do the same for headers, links, etc.  In other words, there is full syntax highlighting.

While I don't handle lists exactly like Emacs org-mode, it will enter the next bullet-point or number for a list when you hit the enter key.  It also recognizes list nesting, and will indent the next item based on your current level in the list.  I think you will also be pleased to find that it handles GitHub todo list items.  You can hit `Ctrl+D` to toggle the todo list item being checked/unchecked.

When you first run ghostwriter, go to Help->Quick Reference Guide in the menu bar.  There's a list of shortcut keys for power users like yourself.  I'm sure I'll being growing the list of shortcuts over time as people bring their suggestions on what's useful for them.  You can also take a peek at the resources/quickreferenceguide.html file before installation, if you'd rather.

I'll be sure to look further into Emacs org-mode to see if I can enhance the lists shortcuts.  Thank you for the suggestion.

**Comment by zaxebo1** [comment]
thanks buddy for accepting the list shortcuts enhancements :-) :-)  :+1:
