### ISSUE TITLE
"The Document has been modified by another program. Would you like to reload the document?"

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#112]
In 1.4.0 I am getting this consistently. I can reproduce this every single time by doing the following:

1. Ensure all other applications closed
2. Open Windows Explorer folder to document location
3. Click on file-associated .md file to open it in Ghostwriter
4. Make a change
5. Save the document

Result: that notification message "The Document has been modified by another program. Would you like to reload the document?" Saying yes just reloads the document, complete with the change I made, and I can continue working without further issue.

It only happens once per "session." If I close the document and reopen, I can immediately replicate.

It's not actually a problem so much as a weird minor annoyance.

Also: Win10 Pro 64-bit, have not updated to Anniversary yet.

**Comment by wereturtle** [comment]
Unfortunately, I can't seem to replicate this issue on Windows 7, and I don't have Windows 10.  However, I have not heard of other Windows 10 users having this issue in the past.

I did bump up the Qt version that came bundled with the 1.4.0 ghostwriter release to version 5.5.1 (from 5.5.0).  Does this issue appear for you in ghostwriter 1.3.1?  That version came bundled with Qt 5.5.0.  I am wondering if the newer libraries may be causing the problem.

**Comment by wereturtle** [comment]
Closing due to lack of further information to help troubleshoot.

**Comment by nonplayer** [comment]
Forgot to update: this problem went away with 1.4.2. Thanks.

**Comment by wereturtle** [comment]
Glad to hear it!
