### ISSUE TITLE
Problem when writing words like doesn't

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#114]
Dear all, 

I would like to discuss the following problem. When writing, for example, the word `doesn't`, then the ``is being auto-completed to`''`.

In this particular case of writing `doesn't`, I do not want this auto-completion feature.

The problem is also demonstrated in the attached gif animation. 

Warmly,

~Robert

![hyphen](https://cloud.githubusercontent.com/assets/170947/17527995/d203ed92-5e6d-11e6-8638-e29dcdde241d.gif)

**Comment by francesca-c** [comment]
I also have this problem. Auto-complete of punctuation pairs like that is great for code, not as great for writing prose.

Another issue I have is when editing with any text below it, backspacing eats up all the line breaks till your later text is right up against the cursor. It's visually very distracting.

This is on Linux Mint 18 Cinnamon and Mate.

But otherwise I love this software. Thank you!
- Cheryl

**Comment by jeff9315** [comment]
If you look at my post "**Several feature requests**", the 3rd bullet point also mentions this problem with the single quote. As a workaround, in Version 1.4 and above, go to **Settings > Customize Matched Characters** and turn off the single quote matching.

Thanks ... Jeff

**Comment by orschiro** [comment]
Dear Jeff, 

I have never looked into the `Customize Matched Characters` menu. Thank you!

That workaround does work well for me. :-)

~Robert

**Comment by francesca-c** [comment]
Yes, that's great that you can customize the matching. I should have looked for that first!

**Comment by wereturtle** [comment]
I'm actually going to keep this issue open, since I had the idea that not auto-matching the apostrophe character when there are preceding word characters would be helpful as well.

**Comment by wereturtle** [comment]
This issue also needs to address the following mentioned in #110:

> A `*` at the beginning of the line (only white space preceding it) or an `'` immediately after a letter or number should NOT be paired with it's opposite.

This issue should also consider context for matching of other characters.
