### ISSUE TITLE
Backspace deletes adjacent line breaks, too

### ISSUE THREAD

**Issue by Digitale-Substanz** [wereturtle/ghostwriter#115]
Hey all,

When the cursor sits at the end of a line and backspace is hit to delete any character in this line, adjacent line breaks are accidentally removed, too. 
This can be pretty annoying, if you're in the middle of your text, correcting misspellings for example, but each time you hit the backspace key, abstracts from further down the page suddenly jump upwards.

I'm having this trouble with 1.4.0 using Ubuntu 16.04. 

Best,
Ron

**Comment by wereturtle** [comment]
Sorry, but I can't replicate this.  I'm running Mint 18 (which is based on Ubuntu 16.04) at the moment.  Earlier in the year, I also ran ghostwriter on the Ubuntu 16.04 beta with the Unity DE without noticing any issues in using the backspace key.

Perhaps you can upload a video (or animated gif from a video capture) showing what is happening in case I am misunderstanding?

**Comment by DeFabro** [comment]
The Backspace key deletes a break line together with a previous character.

Steps to reproduce:
1. Type two sample paragraphs
2. Place the cursor at the end of the first paragraph
3. Press backspace to delete a character.

Tested on Windows 7.

**Comment by Digitale-Substanz** [comment]
@DeFabro that's exactly what happens here too. I've just recorded a screencast to showcase the behaviour. But think, it's not necessary to upload it twice.

**Comment by Luke-Nukem** [comment]
Confirmed here (openSUSE Linux). I work around it currently by adding a space in-front of the cursor position - not ideal though.

**Comment by wereturtle** [comment]
OK, I see what you mean now.  Thanks for the gif.  Strangely, this is not happening for me on Linux Mint 18.  I can only replicate it on Windows 7.  Which is strange, considering we have a report in this thread of the issue occurring on openSUSE.  Since this bug is highly annoying, I'll release the solution as a hot fix (as soon as I find the solution, that is).

**Comment by francesca-c** [comment]
I can confirm, I had that problem on Linux Mint 18, but it seems to have stopped in the last day or two, which is strange. And I just installed it to test on my Mint 17.3 netbook, and it has the same issue.

**Comment by alfsb** [comment]
Same problem, Ubuntu 14.04.5 LTS with Gnome Flashback. Backspace on a empty line works as expected, but backspace on last char of a line with text also deletes a line break. Some quirk on handling of `\n`, `\r`, `\n\r`?

My file is saved with Unix/Linux line endings.

**Comment by alfsb** [comment]
This bug has some side effects. #120 only happens after this bug is triggered. And them `Ctrl+X` on some selected text starts generating some garbage too.
