### ISSUE TITLE
Recognising misspelled words with a hyphen?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#128]
Dear @wereturtle,

Can Ghostwriter recognise `Wi-Fi` as an entire word so that I can add it to my custom dictionary?

Thankfully,

-Robert

**Comment by wereturtle** [comment]
I'll look into it.  I'm pretty sure Hunspell does handle hyphenation just fine (it's working fine in LibreOffice, which uses Hunspell).  It's probably the code I lifted from FocusWriter that's splitting up the hyphenated words and feeding them to Hunspell that way.

Thanks!

**Comment by orschiro** [comment]
Great, thank you for taking care of this! :+1:

**Comment by orschiro** [comment]
Thanks! :-)
