### ISSUE TITLE
Multi document support

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#130]
It would be really nice to hava a kind of _project file_ support. Which structures a document consisting of multiple md files. This makes working with multifile documents much more convenient.
Perhaps something linke the [Gitbook](http://gitbook.com) people do. There you have a `SUMMARY.md` which looks like this

```
# Title

## Chapter 1
[Scene1](./chapter1/scene1.md)
[Scene2](./chapter1/scene2.md)

## Chapter 2
...
```

This overview can be displayed in a _project_ HUD to make navigation to subfiles easier.
What do you think?

**Comment by wereturtle** [comment]
First of all, I made the application to excel at handling large documents, so splitting up a document into multiple files is unnecessary.  (Although there is some awkwardness in navigating to different scenes within a chapter, but that feature might be more negotiable for the future.)

Second, I am very leery of adding any kind of project management, multitabbing, etc.  If I go down that road, I could one day wake up to find that I've cloned Sublime Text, and should have just written a plugin in the first place.  I decided when I set out to make the application more like a themable sheet of blank paper to crank out that dissertation or novel.

But thank you for your suggestion!
