### ISSUE TITLE
Desktop file wrongly specifies that Ghostwriter can open multiple files on command line

### ISSUE THREAD

**Issue by mcfadzgit** [wereturtle/ghostwriter#132]
ghostwriter.desktop specifies:
`Exec=ghostwriter %F`
But if you run Ghostwriter from a terminal with multiple files, only the first is opened.
So, the desktop file should instead specify:
`Exec=ghostwriter %f`

**Comment by wereturtle** [comment]
Good catch!

I'll be sure to fix the ghostwriter.desktop file on the next release.

(This is what happens when you copy someone else's debian packaging and tailor it for your application.  Oops!)

**Comment by mcfadzgit** [comment]
Thank you, and I noticed that the man file also specifies:
`[file...]` rather than `[file]`

Another small query:
Although I usually want Ghostwriter to 
`Remember File History`
I don't always want it to load the very last file I was working on; I might want to select one of the *other* recent files or another file entirely.
Would it be possible to have a separate setting to
`Load last file` ?

Ghostwriter is certainly my favourite markdown editor (especially for maintaining website content), and I wish it every success in the future.

**Comment by wereturtle** [comment]
I've added a new issue for your request (#135).  Thanks again!
