### ISSUE TITLE
MultiMarkDown CSS metadata

### ISSUE THREAD

**Issue by firedrow** [wereturtle/ghostwriter#133]
I've installed the MultiMarkDown package on Windows 10, and I love using the variables and metadata.  But I assume some metadata options are being ignored, specifically the CSS rendering.  If I use CSS: url_to_css_file it's inserted into the HTML preview, but not used.  I can Copy HTML and confirm the link rel is in the head, but none of the CSS options are rendered.  If I copy the CSS file contents and put them either in a local CSS file for Ghostwriter or an HTML Header metadata tag, then they work.

**Comment by wereturtle** [comment]
I gave using the CSS metadata a try with MultiMarkdown instead, and it successfully overrode the stylesheet set by the HTML Preview window.  The path to the CSS file does have to be a URL it can find, either on your local hard disk (such as `file:///path/to/your/stylesheet.css`) or somewhere on a website (such as `http://your.website.com/stylesheet.css`).  A relative path to your document should also work (i.e., `../../stylesheet.css`).

Just to confirm, did you change the Markdown processor in the HTML Preview window from Sundown to MultiMarkdown?  (The combo box is in the lower left corner.)  Perhaps you can provide me with a more concrete example that I can better replicate the issue on my end?

**Comment by firedrow** [comment]
The difference may be I am using HTTPS sites for both my hosted files.  [](https://cdn.rawgit.com/firedrow/misc/master/md.css) and [](https://rowland.pw/md.css)

**Comment by wereturtle** [comment]
Alas, I probably can't help you there.  That's a WebKit thing, and WebKit is what is powering the previewer.  But I'm glad the HTTP URL is working for you!
