### ISSUE TITLE
When Alt-Tabbing Back to Ghostwriter, Only One Pane Comes Back (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jvarghe** [wereturtle/ghostwriter#134]
I have Ghostwriter v1.4.2 installed on Ubuntu 16.04 LTS.

When I write in Ghostwriter, I need to alt-tab and consult lots of other material. I have the writing pane and html preview pane side by side so I can check the rendering: 
![ghostwriter - dual pane view](https://cloud.githubusercontent.com/assets/13189319/18452836/9001503a-790a-11e6-8b3f-aaef0e55a796.jpg)

After I read something, I alt-tab switch to Ghostwriter and I get only one screen back, as you can see:

![ghostwriter - view after alt-tabbing](https://cloud.githubusercontent.com/assets/13189319/18452955/f838b260-790a-11e6-9737-721715a92630.jpg)

I think I'm slowly going insane from having to manually bring back the other pane every time! I would use another program, but Ghostwriter is the only Commonmark editor available on Linux.

Could you please add a dual pane mode like Markdown Edit does or make both panes appear when I alt-tab back to Ghostwriter? 

Please have mercy on my sanity. ;-)

**Comment by wereturtle** [comment]
While I sympathize with your suffering, why don't you try using multiple workspaces instead?  That's exactly what they are for.

I see from your screenshot that you are using the Unity desktop.  Check out this link [here](http://askubuntu.com/questions/83176/how-do-i-quickly-switch-between-workspaces-in-unity) for shortcut keys for switching between workspaces quickly.  It also tells you how to enable workspaces, as apparently they aren't enabled by default.

With this, you never have to go through this madness for any app (or even group of applications you have displayed side-by-side) ever again.

**Comment by jvarghe** [comment]
I just switched to Ubuntu a few weeks ago. I didn't about Workspaces. That's a lovely feature I never knew about in Windowsland. Thanks! This will be very useful.

I still think this dual pane mode is important. When I scroll down the writing pane, it would be great if the HTML preview window kept pace and auto-scrolled to the same place in the document.

**Comment by wereturtle** [comment]
I think Windows 10 finally added workspaces, after all these years of various Linux desktops having them.  At least that's what I heard.  (It's about time!)  But anyway, welcome to the wonderful world of Linux!

Autoscrolling is a rather complex feature to get right.  Most other editors with this feature scroll by an estimated percentage.  This works fine on small documents, but it quickly becomes inaccurate on large documents or documents that have images that offset the text significantly.  Differences in fonts between the editor and preview window will also cause the preview window to scroll to the wrong position.

I may try implementing this feature in the distant future, but not anytime soon I'm afraid.
