### ISSUE TITLE
Size of the text under Gnome

### ISSUE THREAD

**Issue by gnacho** [wereturtle/ghostwriter#137]
This is what I get, different computers, all under Gnome 3.20 and ArchLinux. 
![untitled- - ghostwriter_001](https://cloud.githubusercontent.com/assets/10582292/18807750/d23ddf24-824f-11e6-9467-eb0a1555e2da.png)
Any ideas?

**Comment by wereturtle** [comment]
Whoa!  That's really weird looking!

A few questions to help me troubleshoot:

1. Are you on a high resolution display (i.e., your screen resolution is larger than 1920x1080)?
2. How do other Qt 5 applications look?  Are you getting similar behavior?  A good test would be to try QOwnNotes or FocusWriter.
3. Have you adjusted your DPI and font antialiasing under Gnome without adjusting your Qt DPI settings separately?  (For Qt 5, that is.  Adjusting for Qt 4 won't help Qt 5 applications.)
4. Do other desktop environments under Arch exhibit this behavior?  Did a prior version of Gnome work OK, or did this just start with 3.20?

Thanks!

**Comment by wereturtle** [comment]
Also, could you try exporting the following from a terminal, and then launching ghostwriter from the terminal?

```
export QT_STYLE_OVERRIDE=adwaita
export QT_AUTO_SCREEN_SCALE_FACTOR=0.8
```

I couldn't help but notice how gigantic the scrollbar and the full screen button look in your screenshot.  I'm betting this has something to do with HiDPI.

This tip came from [here](https://bbs.archlinux.org/viewtopic.php?id=211118).  Let me know if it improves anything.

**Comment by gnacho** [comment]
> 1. Are you on a high resolution display (i.e., your screen resolution is larger than 1920x1080)?    

No,  both computers have 1920x1080 resolution.

>2 How do other Qt 5 applications look? Are you getting similar behavior? A good test would be to try QOwnNotes or FocusWriter.

QOwnNotes and FocusWriter look fine, as well as the rest of QT apps I have (not so many). The only other QT app that looks huge is Seafile client, and it doesn't happen with two monitors. Related: https://github.com/haiwen/seafile-client/issues/809

>3 Have you adjusted your DPI and font antialiasing under Gnome without adjusting your Qt DPI settings separately? (For Qt 5, that is. Adjusting for Qt 4 won't help Qt 5 applications.)

No, I didn't touch anything of DPI settings.

>4 Do other desktop environments under Arch exhibit this behavior? Did a prior version of Gnome work OK, or did this just start with 3.20?

I didn't try this app under other desktop enviroments or before Gnome 3.20, so can't be really useful here.

I tried the tips you gave me but didn't change anything.

**Comment by wereturtle** [comment]
Thanks for the reply.  At least we can rule some things out.  I'll try installing Antergos with Gnome 3.20 in Virtualbox and see what's up.

**Comment by gnacho** [comment]
Thanks! Anything you need let me know. Within the next weeks I guess Arch will be upgraded to Gnome 3.22 so let's see how Gnome Shell deals with this issue too.

**Comment by wereturtle** [comment]
Hmm, well, all is working in Antergos with Gnome 3.20 under Virtualbox.  Perhaps I'd need to have a proper graphics driver installed while running on real hardware to see this problem?

I forgot to ask earlier:  Did you compile ghostwriter with code directly from this Github repository, or did you use something you found in the AUR?  I know someone put ghostwriter in the AUR, but it is missing several dependencies, and would not even install in anything but KDE last time I tried it with Manjaro.  (KDE happened to already have the necessary dependencies.)  Still, the AUR package shouldn't even install in the first place to give you this kind of trouble.  I am quite perplexed.

**Comment by gnacho** [comment]
I'm using AUR package, which seems to be working fine in one of the three computers I tried (desktop computer). Both laptops with i7 and m5 processors are the ones showing this issue. Maybe it's something related to Intel mobile graphics?

**Comment by wereturtle** [comment]
As a last ditch effort, I'd try cloning the ghostwriter git repository and compiling from scratch.  You'll have to install the dependencies listed in the README file manually.  However, just be aware that the dependencies I listed were for Debian package names.  Arch is a little bit different in naming convention, but easy enough to sort out.  (I'll have to get around to updating the README for that.)

Beyond that, it might be some sort of graphics conflict.  I'm not sure.  Perhaps folks on the Arch forum might know where to look next?  Unfortunately, I'm way out of my league at this point.

Sorry, I wish I could help out more.

**Comment by gnacho** [comment]
Ok, many thanks. I'll let you know if I can fix it.

**Comment by gnacho** [comment]
Same issue after upgrading to GNOME 3.22, both using Wayland and Xorg. Must be something related to QT (does not happen with 2 screens).

**Comment by gnacho** [comment]
Found the solution by doing this:

Add
```
export QT_AUTO_SCREEN_SCALE_FACTOR=0.8
```
to ~/.profile (if does not exist, create it) and reboot.

Worked for me. Can other people confirm?

**Comment by wereturtle** [comment]
Oh, wow!  I'm glad you found the solution!

I'm thinking I'll add a link to this issue and to other Linux-specific issues in the README, since so many weird Qt5 issues pop up all the time.

**Comment by gnacho** [comment]
And seems to be behaving like that again. Not sure what's the reason but the solution must be different  one.

**Comment by gloomy-ghost** [comment]
`QT_AUTO_SCREEN_SCALE_FACTOR` is actually a boolean so `0.8` doesn't really make a difference...
