### ISSUE TITLE
Possible to get code blocks AND metadata items to both render correctly?

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#138]
I can't seem to get both code blocks and metadata attributes to render correctly in the same document. I am switching between different markdown renders, and it seems I can have one or the other, but not both. It either hides the metadata appropriately while converting the block to a single line, or displays the block correctly but also prints the metadata text.

Is there a renderer that  both hides the metadata _and_ displays full code blocks? Is this a bug, a missing feature of the renderers, or am I just doing it wrong?

I've attached a very simple file that should show what I'm talking about. Load it up, render in HTML, then try the different markdown processors.
[mdtest.txt](https://github.com/wereturtle/ghostwriter/files/491262/mdtest.txt)

**Comment by wereturtle** [comment]
The renderer you are looking for is MultiMarkdown, available [here](http://fletcherpenney.net/multimarkdown/).  Pandoc and the others don't handle that particular metadata format you are using (and sadly, not even Pandoc's MultiMarkdown mode handles it, as you discovered).

Once you install MultiMarkdown, restart ghostwriter, and then you should see it as an available option in the HTML Preview window's combo box and in the Exporter dialog window.

**Comment by nonplayer** [comment]
Okay a follow up question. I got this to work - thanks!

However, with that option I can not export to DOCX. Is that a ghostwriter limit, or a pandoc limit?

**Comment by wereturtle** [comment]
> However, with that option I can not export to DOCX. Is that a ghostwriter limit, or a pandoc limit?

Do you mean, *pandoc*, or *Multimarkdown*?  (I presume that since it's working, you meant to say "Multimarkdown".)  If Multimarkdown, then, yes, it is a limitation of Multimarkdown.  It just doesn't export to DOCX.  Pandoc does, however.  I know, it's hard to get all the right features together!

But you can use Multimarkdown to export to ODT, and then use LibreOffice to export to DOCX.  Not as convenient, but it works.

**Comment by nonplayer** [comment]
Great, thanks! I've basically just gone back to using pandoc multimarkdown again instead, it's a lot easier to just export and then delete the metadata at the top than go through the round-about flow of passing through multiple apps.

Thanks again for the tips though.
