### ISSUE TITLE
Provide 'readability' metrics, based on established conventions

### ISSUE THREAD

**Issue by brylie** [wereturtle/ghostwriter#139]
# Context

Currently, GhostWriter counts the number of complex words (presumably by syllable count). This helps authors to decide whether to use simple words throughout their text.
# Feature request
## Original request

The original request was to extend the count of complex words and provide a count of complex sentences. E.g. complex sentence counts could be derived by counting the _number of syllables_ or _complex words_ per sentence. Some threshold would be defined, above which a sentence is considered complex.
## Revised request

It would be helpful to have one or more 'readability' metrics. This would help authors who want to improve the readability of their writings.
# Related

As per discussion, it was decided to find examples of 'readability' metrics that are based on academic research. The following metrics are available, with public domain documentation.
## Primary source(s)

These resources provide or summarize primary references.
- [How complex is that sentence?](http://ai1.ai.uga.edu/caspr/D-Level-Poster.pdf)
## Secondary source(s)

These sources provide secondary research material, general descriptions, etc.
- [Automated readability index](https://en.wikipedia.org/wiki/Automated_readability_index)
- [Coleman–Liau index](https://en.wikipedia.org/wiki/Coleman%E2%80%93Liau_index)
- [Dale–Chall readability formula](https://en.wikipedia.org/wiki/Dale%E2%80%93Chall_readability_formula)
- [Flesch–Kincaid readability tests](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests)
- [Gunning fog index](https://en.wikipedia.org/wiki/Gunning_fog_index)
- [Pearson’s Text Complexity Measure](http://www.impact-information.com/PearsonsTextComplexity.pdf)
- [SMOG](https://en.wikipedia.org/wiki/SMOG)

The Wikipedia article on [readability](https://en.wikipedia.org/wiki/Readability), contains the following statements related to research in readability:

> "Shorter sentences and concrete terms help people to make sense of what is written."
> - attributed to Professor L. A. Sherman
> 
> "the main blocks to comprehension are unfamiliar words and long sentences."
> - attributed to Nikolai A. Rubakin
## Code libraries
- [Qt Readability](https://github.com/bdentino/Qtino.Readability) - wrapper for QtReadabilityApi
- [TextStatistics.js](https://github.com/cgiffard/TextStatistics.js) - library with syllable counting functions and several text analysis formulas

**Comment by wereturtle** [comment]
Well, technically, ghostwriter isn't counting syllables.  I didn't want to be too English-centric, and it is rather difficult to get the right libraries for C++ to break words into syllables (not to mention the right dictionaries for some of the algorithms out there).  ghostwriter is instead counting word length per the LIX and Coleman-Liau algorithms.  (I nearly added ARI, too, but that had wild swings between Kindergarten and Rocket Science reading levels on various test inputs.)

But more to the point, what criteria should be used to determine sentence complexity?  Is it length of characters?  Number of words?  What researched algorithms exist at the sentence level?  What percentage of complex sentences is considered a good indicator of sentence length variation (which is more important than how many sentences are complex)?

I'd need a tried a true method of determining this.  Do you have any good suggestions?  (Yes, I looked at the TextStatistics.js you referenced, but it didn't look like it had anything for sentence complexity.)

**Comment by brylie** [comment]
The sentence complexity could be a count of words and syllables. 

Is it possible to import a JavaScript library into a Qt project?

The goal here would be to simply highlight the complex sentences, so that the author can decide what they wish to do.

**Comment by brylie** [comment]
A quick search indicates that [JavaScript can be imported into QtQuick documents](http://doc.qt.io/qt-5/qtqml-javascript-imports.html).

**Comment by brylie** [comment]
I agree that we should avoid being English-centric. Multi-lingual readability metrics would admittedly be quite difficult. The proposal is to include an existing library, rather than going down the rabbit hole ourselves, which may mean less than optimal support for some languages.

**Comment by wereturtle** [comment]
Sorry for the late reply.

I am aware that JavaScript can be imported, but the editor is a C++ widget, and not QML.  Even with calling the JavaScript routines and incorporating the results into the C++ editor, it's probably easier to just port the algorithm to C++ (particularly the sentence complexity algorithm).  But that isn't my greatest issue of concern.  The bigger issue is that the JavaScript library you pointed me to doesn't actually count sentence complexity.  It counts syllables per sentence, but it doesn't grade whether a sentence is actually complex.  What is the proposed threshold of number of syllables or words as to when a sentence is considered complex vs. simple?  Does a standard for determining that exist?  (I'm guessing not, based on my internet searches.)  I'd prefer getting a clear threshold from an academic study rather than just making one up.

**Comment by brylie** [comment]
I have renamed this issue to make it a bit more generic, since the 'syllable count per sentence' is under dispute.

I will add references to one or more 'readability' metrics, with accompanying publications where possible.

**Comment by brylie** [comment]
What are your thoughts on [Qtino.Readability](https://github.com/bdentino/Qtino.Readability)?

**Comment by wereturtle** [comment]
Sorry for the late reply.  Unfortunately [Qtino.Readability](https://github.com/bdentino/Qtino.Readability) shut down its service, so I can't see what it's actually doing.

I'm going to close this issue for now.   I probably won't have the time to fiddle with this feature.  I'll reopen it if someone expresses interest in helping.  (I'll still  need some sort of standard for the part with determining when a sentence is too complex.)
