### ISSUE TITLE
Provide helpful suggestions for improving writing

### ISSUE THREAD

**Issue by brylie** [wereturtle/ghostwriter#140]
As a writer, 
I would appreciate suggestions for improving my writing
so that I can improve the readability of my text

# Feature
Provide specific suggestions as to how authors can improve their text, such as:
- avoid passive voice
- omit 'so' from beginning of sentences

These suggestions might also indicate which line of text could be improved, e.g. via line number or highlighting.

The author can enable/disable the feature.

# Related resouces
- [Write Good](https://github.com/btford/write-good) is an NPM package for 'linting' English language.

**Comment by wereturtle** [comment]
I'd prefer not to be too English-centric.  Not to mention, it's not easy getting nice English parsing libraries for C++.  I could hack something on my own, but it won't be as clever.
