### ISSUE TITLE
Linux - Backspace does not work when "Hemingway" mode is active

### ISSUE THREAD

**Issue by silentwarrior** [wereturtle/ghostwriter#141]
Hi.

 Backspace does not work for deleting text when "Hemingway" mode is active.

I have only tested it on Linux.

Turning it off makes backspace work again, I can select several lines and use backspace to delete successfully. When Hemingway mode is active, nothing happens. Only select + re-type does anything.

**Comment by brylie** [comment]
That may be by design.

**Comment by wereturtle** [comment]
That, my friend, is precisely what Hemingway mode is.  This mode purposely disables the backspace and delete keys.  Its purpose is to simulate a typewriter and remove the temptation to go back and edit while free-writing.

**Comment by brylie** [comment]
Documentation can help with issues such as this.

@wereturtle where is *Hemingway mode* documented?
