### ISSUE TITLE
Save As Keyboard Shortcut?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#142]
Dear @wereturtle,

What do you think?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/19002190/21453b26-874b-11e6-9b2a-f5757ec0cf49.png)

**Comment by wereturtle** [comment]
That's strange.  It's showing up as `Ctrl+Shift+S` on Mint.  I'll trying loading Ubuntu with Unity in VirtualBox and see what's up with that.  But I'm afraid there probably isn't going to be much I can do.  Incidentally, on Mint 17, the `Ctrl+H` shortcut for the find and replace dialog wouldn't appear, but it does now on 18.  What a headache!

![image](https://cloud.githubusercontent.com/assets/10375170/19018404/37b5a138-8814-11e6-9452-2a260429c3c0.png)

**Comment by orschiro** [comment]
How weird! Thanks for investigating. 

Let me please know if I can help you somehow.

-Robert

**Comment by wereturtle** [comment]
Well, I am honestly stumped.  I can definitely replicate the issue in VirtualBox with the Unity desktop.  I can't for the life of me figure out why it only happens on some desktop environments and not others.  I am presently coding ghostwriter such that Qt gets the standard shortcuts I specify from the operating system.  This normally works, except when it doesn't.  As I said earlier, "Ctrl+H" for find and replace wasn't working on Linux Mint, until one day after an update it mysteriously did again.  I'm not sure if it's the Qt libraries at fault or the GTK+ based desktop environments not being configured properly with Qt.

I'd suggest filing a bug report against Ubuntu, and see where it goes.  Perhaps they can better determine which entity is at fault.  I do wonder if it has to do with the global menus in Unity.  I know you are probably disabling the global menus for your Qt5 apps just to have shortcut keys for the menus working, but I wonder if disabling the global menus has other side effects, such as Qt not being able to get correct standard keyboard shortcuts from the OS.

I could workaround it by forcing "Ctrl+Shift+S" for Save As, but that violates the editor's cross-platform agnosticism.  I'd prefer not to do that.

**Comment by orschiro** [comment]
Thanks for investigating this!

I can file the bug. But before doing so, how can I check if I have global
menus disabled?

**Comment by orschiro** [comment]
Interesting.

appmenu-qt5 is already the newest version (0.3.0+16.04.20151130-0ubuntu1).

And still some shortcuts like CTRL+O are working.

**Comment by wereturtle** [comment]
Right, I'm thinking some shortcuts are still working, but maybe the workaround for the global menu bug with Qt5 is causing other issues, like missing Ctrl+Shift+S.  But since I once saw Ctrl+H missing before in a non-Unity desktop, that's probably not the case.  I'm honestly stumped.

**Comment by orschiro** [comment]
I just updated to Ubuntu 16.10 and now none of the shortcuts work anymore again...

**Comment by wereturtle** [comment]
Oh no!  That's not good.  Try installing appmenu-qt5 again and see if Canonical fixed the global menu.  Something has changed with 16.10's Unity under the hood to take away all the shortcuts.

**Comment by orschiro** [comment]
I re-installed appmenu-qt5 and now no keyboard are working anymore on
Ubuntu 16.10.

**Comment by orschiro** [comment]
Dear @wereturtle,

I did some follow-up [here](https://bugs.launchpad.net/appmenu-qt5/+bug/1380702) but now I am really confused and don't understand most of the conversation over there. 

Are there any take home messages for us and this issue with Ghostwriter?

**Comment by wereturtle** [comment]
I think the workaround for 16.10, based on the thread, is to launch the Qt app with appmenu-qt5 installed from the command line (in a terminal window) with a certain environment variable unset, like so:

    env UBUNTU_MENUPROXY= ghostwriter &

This is supposed to disable the global menu just for that application.

Hopefully they'll work out a patch for 16.10 and backport it.  Looks like they're close.  Let me know if the above worked, so that others using Unity can know if it helps.

**Comment by orschiro** [comment]
For me this command starts Ghostwriter with the global menu and without
shortcuts working.

**Comment by wereturtle** [comment]
Drat.  Well, I'm afraid this is something that I won't be able to help much with.  I'd advise keeping Canonical up to date with your experiences via that issue thread.  Perhaps someone will come up with a different workaround that will help.

**Comment by orschiro** [comment]
I will do so. Thank you. :-)

**Comment by wereturtle** [comment]
It looks like on further research this might be an issue with the desktop not quite registering as Gnome.  At least, that's all I can think of.  Cinnamon does the same thing, for example.  Here is what is supposed to happen, according to the Qt documentation:

![image](https://user-images.githubusercontent.com/10375170/56474651-850e6900-6431-11e9-9ec1-f87ae019dbb2.png)

Some platforms don't even have a Save As keyboard shortcut, so Qt must be thinking on some desktop environments that it is one of those platforms.  I'm thinking of leaving it as is.  These shortcut keys *should* be determined by platform, and if that isn't happening then that is an issue either with Qt or the desktop environment for not registering with Qt properly (i.e., for not identifying as Gnome if it is Gnome-based).
