### ISSUE TITLE
Open PDF after export?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#144]
Dear @wereturtle,

What do you think of directly opening the PDF after export?

Maybe an optional setting?

**Comment by wereturtle** [comment]
I think that should be easy to do.  In fact, I'll just try doing it with all file formats.

Note to self:

Here's the Qt call to open a file with its default application:

    QDesktopServices::openUrl(QUrl("file:///home/user/fileName.pdf"));

**Comment by orschiro** [comment]
Perfect, thanks for your feedback!

**Comment by nonplayer** [comment]
This would be useful, but definitely should be optional.
