### ISSUE TITLE
Option to toggle between preview and editor

### ISSUE THREAD

**Issue by mlinchitstest** [wereturtle/ghostwriter#145]
It's more convenient usually to have just one window. Having the previewer in a separate window feels kind of clumsy. I don't necessarily need a dual pane editor (though that would be nice), but it would be a big improvement to be able to toggle between view/edit _within_ one window. It would also be good to be able to define which mode opens by default. So if you're using the program to mostly view files, it will just default to the preview mode. Having to juggle multiple windows takes up screen space and is kind of a hassle.

very good program otherwise

**Comment by wereturtle** [comment]
> Having the previewer in a separate window feels kind of clumsy.

It wouldn't feel clumsy if you had dual monitors.  :smile: 

I chose a separate window to be the most flexible to all users with minimal hassle for me to support all the layouts a user could possibly want.  I may in the very distant future decide to support all the possible combinations a user could want, but it's not very likely given my limited time.

Regardless, thank you for your input.
