### ISSUE TITLE
Print dialog: two pages per side?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#146]
Dear @wereturtle,

Is it possible to add an option for printing multiple pages per side?

Thanks!

![image](https://cloud.githubusercontent.com/assets/170947/19213133/4f0abd9c-8d63-11e6-90e4-7ec49f8611c1.png)

**Comment by wereturtle** [comment]
That would be the "duplex printing" option under the "Options" tab you are looking for.  You can set it to long or short instead of none, and that should do the trick.

![image](https://cloud.githubusercontent.com/assets/10375170/19216410/6fe4a8e6-8d6f-11e6-9cb4-a05eecca2670.png)

**Comment by orschiro** [comment]
I see, thanks! 

I didn't know what Duplex Printing was. 

So, basically it's the same like this in LibreOffice, correct?

![image](https://cloud.githubusercontent.com/assets/170947/19218173/6d36d2d4-8df3-11e6-86c9-3e99e4097384.png)

**Comment by wereturtle** [comment]
Oh, no, it's not pages per sheet.  I misunderstood you, then.  It's double-sided printing.  I should have read more carefully.

That's a complicated feature to add, so it's probably not going to happen.  In fact, it's probably better that you export to your preferred format (such as ODT) and use the default application for it to print multiple pages per sheet.

**Comment by orschiro** [comment]
I see, thanks!

When exporting to odt, it always exports as Letter.

How can change this to default to A4?
​

**Comment by wereturtle** [comment]
You really can't I'm afraid.  Pandoc has limited options.  There is some experimental support for creating an ODT template and having Pandoc use that when generating the final ODT, but I understand it's a bit finicky.  It's just easier to fix in in LibreOffice after the export is complete.

**Comment by orschiro** [comment]
Alright, done!

Thanks. :-)
