### ISSUE TITLE
Export failed > jump to cursor position in the text

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#147]
Hi @wereturtle,

What do you think of jumping directly to the cursor position that produces the error?

![image](https://cloud.githubusercontent.com/assets/170947/19261197/cbd039a0-8f8f-11e6-8617-a08f5fd56649.png)

**Comment by wereturtle** [comment]
I'm afraid Pandoc doesn't provide that information for me to be able to parse the position where the error occurred.  Even if it did, by the time the text is passed through to the LaTex engine, it's been converted to an intermediate format, so the error position wouldn't be the same anymore.

**Comment by orschiro** [comment]
I see, thanks!
