### ISSUE TITLE
Select word with Ctrl+Shift+arrow key right

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#151]
It selects more than just the word but also the space after the word.

![ghostwriter](https://cloud.githubusercontent.com/assets/170947/19761308/9e136b2e-9c35-11e6-8eb6-df0c200c4eac.gif)

**Comment by wereturtle** [comment]
I'm afraid that is Qt itself doing that.  I'd suggest filing a bug report against Qt's QPlainTextEdit class, but even if the Qt devs fixed the issue immediately, you wouldn't likely see the fix arrive in Ubuntu 16.04.

**Comment by orschiro** [comment]
Thanks!

I hope I reported it correctly: https://bugreports.qt.io/browse/QTBUG-56812

Even if it's not being implemented in Ubuntu 16.04, I hope this will be addressed for the future. :-)
