### ISSUE TITLE
Images are not shown in the preview window on Windows 10.

### ISSUE THREAD

**Issue by kalkin7** [wereturtle/ghostwriter#152]
![Image error on ghostwriter](https://cloud.githubusercontent.com/assets/1732652/19834188/9772b95e-9e98-11e6-9ac4-edc47395048f.png)

Like above image, on the preview window images are now shown.
How can I fix this problem?

**Comment by wereturtle** [comment]
This is due to your image URL being https.  Try http instead.  Unfortunately, WebKit (which handles the preview) can't do https within Qt.
