### ISSUE TITLE
Feature request: Table of Contents

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#153]
I plan to use ghostwriter to write ebooks. It would be very helpful if ghostwriter had a way to add a ToC. Other than that, great job.

**Comment by wereturtle** [comment]
I assume you're using Pandoc.  I'll look into hardcoding the ToC generation into the export for Pandoc for generating ebooks.  Would that be sufficient?  It does rather make sense that users would want to always generate a ToC for an ebook by default.

**Comment by JohnBlood** [comment]
Sounds good to me.

**Comment by orschiro** [comment]
Really excellent idea to support `[TOC]`. :-)
