### ISSUE TITLE
Request: Tabbed Window

### ISSUE THREAD

**Issue by firedrow** [wereturtle/ghostwriter#155]
I use GhostWriter with MultiMarkDown extensively at work, love having it for taking notes, prepping reports, etc.  But I generally have 2 or 3 windows open while I work on different reports or notes.  Having a tabbed window would help immensely.

**Comment by suhr** [comment]
For taking notes, look at [QOwnNotes](https://github.com/pbek/QOwnNotes). It has distraction-free mode too.

**Comment by wereturtle** [comment]
Sorry, @CAtoDC, but I meant for ghostwriter to be for focusing on writing a single piece, and not so much for note taking.  While having tabs for the plain text isn't such a big deal, having them for each web preview begins to hog system resources very quickly, and I meant for the app to be efficient.

**Comment by CAtoDC** [comment]
Totally understand.  Thanks so much for creating this.  Still **very**
useful.  Happy Holidays!
