### ISSUE TITLE
Accessing a remote bookmark

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#156]
Hello all, 

Is it possible to access a remote bookmark from Ghostwriter's dialogue windows?

![image](https://cloud.githubusercontent.com/assets/170947/20891924/891341a4-bb0c-11e6-8f56-c9d073757778.png)

![image](https://cloud.githubusercontent.com/assets/170947/20891927/8fd10d3c-bb0c-11e6-9a03-35c59f9517eb.png)

**Comment by wereturtle** [comment]
Hi @orschiro ,

Canonical (or possibly Debian) forgot to add a dependency to the packaging for Qt that allows native GTK file dialogs.  This is why you are seeing the non-native Qt file dialog, which does not show your bookmarks.

I put instructions for the fix in the wiki [here](https://github.com/wereturtle/ghostwriter/wiki/GNU---Linux-Troubleshooting-for-Qt5-Applications).  It's just a quick package installation.

**Comment by orschiro** [comment]
Nice one!

That worked. :-)

Thank you.
