### ISSUE TITLE
[Request] "Live check" preview

### ISSUE THREAD

**Issue by cemetary** [wereturtle/ghostwriter#161]
I would like to know if something like "live check" (see gif below) can be implemented in Ghostwriter.

![peek 2016-12-16 13-51](https://cloud.githubusercontent.com/assets/10538213/21277310/4edf7a6a-c39b-11e6-99e9-5010438c6e6a.gif)

Cheers

**Comment by wereturtle** [comment]
Sorry, but that would require a massive rewrite of the application.
