### ISSUE TITLE
Czech localization of Ghostwriter

### ISSUE THREAD

**Issue by pafri** [wereturtle/ghostwriter#162]
Attached the archive with the Czech translation file for Ghostwriter. Please commit it. Best regards,  Pavel Fric.

[ghostwriter_cs.ts.zip](https://github.com/wereturtle/ghostwriter/files/659096/ghostwriter_cs.ts.zip)

**Comment by wereturtle** [comment]
Thank you!  I'll be sure to include this in the next release!
