### ISSUE TITLE
Close Outline HUD with escape [low priority]

### ISSUE THREAD

**Issue by ix5** [wereturtle/ghostwriter#163]
This is an **enhancement proposal**.
When you have opened the outline HUD(most likely with `CTRL-L`), the only way to hide it is to use the mouse and click the 'close' button.

To me, this HUD is mainly a navigation tool and not something I want cluttering the screen when writing. After I have used it, it should be gone again.

I'd envision either using `CTRL-L` to 'toggle' the HUD visibility or closing it with escape, either seems intuitive to me.

Thoughts?

**Comment by wereturtle** [comment]
Don't worry.  Issue #93 has already been created for this.  I'll be sure to add the Escape key as another means of closing the currently focused HUD.
