### ISSUE TITLE
create file if not existing

### ISSUE THREAD

**Issue by joede** [wereturtle/ghostwriter#165]
If ghostwriter is called with an file(name) that is not existing, an error is reported. IMO it would be better to simply create the file.

**Comment by suhr** [comment]
I think, better to create file on save.

**Comment by joede** [comment]
@wereturtle Would you except a pull request with an implementation?

**Comment by wereturtle** [comment]
Sure!  That would be very helpful!  But please be sure to have error handling in case file creation permissions are lacking.

**Comment by joede** [comment]
OK. I'll give it a try. Hope to find some spare time for that. ;-)

**Comment by joede** [comment]
@wereturtle  I've done some coding on that topic, but I have some problems. (1) the newly opened windows starts without modifications (that's my preset in `DocumentManager::createEmptyFile()`). After a second, this changes to modified. (2) Since the file doesn't exist, it isn't possible to use `QFileInfo` in `TextDocument::setFilePath` to set the basename and the full path. Do you have an idea how to handle that?
My changes are in my fork in the branch `feat--create-missing`).

**Comment by wereturtle** [comment]
It's okay.  I'll just code it.  You don't even have to touch DocumentManager or TextDocument.  Just the spot in MainWindow where it is logging the error needed to do a touch to create an empty file first, and then the app could continue as before.  I don't really have time to explain Qt APIs, so please don't be offended.  It's just faster if I do it.  It's one of those time management issues.  But thank you for offering to help!
