### ISSUE TITLE
Feature Request: File tree sidebar

### ISSUE THREAD

**Issue by thejambi** [wereturtle/ghostwriter#167]
Ghostwriter looks like one of the best markdown editors for Linux I've seen. But all of them lack a file tree sidebar - having this turns the app into a full writing environment. When you don't have to open every single file in your project (or list of notes, or whatever) because you have them all right there available to you, it's amazing, efficient, and cuts down on distraction, etc. 

Is this a possible feature for Ghostwriter? (Or is it there somewhere and I missed it?) 

For examples of apps that have this, look at Lightpaper or the super-popular Ulysses app.

Thanks!

**Comment by wereturtle** [comment]
I am considering a HUD for something like this.  I was thinking more of a "Favorites" HUD, where you can bookmark both individual files and folders, and expand your favorite folders to see all your files within, and open them from there.  It's going to be a long while before this feature gets implemented, however.

My only trepidation with implementing this, however, is that people will keep asking for tabbed file viewing for multiple files, and then for split panes, and then I'll wake up realizing I've reinvented Sublime Text.  I do have to put on the brakes somewhere, and keep this app focused on zenning out on that one document.

**Comment by thejambi** [comment]
Nice. I don't think tabs/multiple documents is a priority because of what you said, too. But I do think the folder/favorites idea would be awesome. It really does enhance the "zenning out" distraction-free feeling of the app because there's no file dialogs, etc.

**Comment by Julianoe** [comment]
Is this still open to discussion or is this very low priority feature?

For me and other users that work with multiple documents on a project it's really a very good feature to have a filetree sidebar. I'm not talking about multiple opened files or nothing. But the possibility to switch from file to file just clicking on that sidebar, having the different chapters of a book project, parts of a list of articles, different sections of a big documentation or anything like that.

Honestly i've used Typora a while until i discovered it was not a FOSS. Ghostwriter is all i want from a slick a minimal editor. But the single feature i miss from that software is the filetree view that allowed me times to times to see where i was on my project and switch from chapters to chapters very easily.

**Comment by wereturtle** [comment]
@Julianoe 

> But the single feature i miss from that software is the filetree view that allowed me times to times to see where i was on my project and switch from chapters to chapters very easily.

Yes, it is a low priority feature at this time.  However, the app was engineered with large, multi-chapter/section documents in mind.  I was personally disappointed in many editors that slowed down if I tried putting in 100,000+ words.  I like having my work all in one giant file (sans references, of course).

I would suggest experimenting with having all your chapters in one file, and using the Outline HUD to navigate.

**Comment by Julianoe** [comment]
I guess that's a matter of how to organize files and how one works. I will try to merge some of the files and try to work this way i guess for now :)

Thanks for the answer :+1:
