### ISSUE TITLE
Explain Hemingway mode somewhere

### ISSUE THREAD

**Issue by nsrosenqvist** [wereturtle/ghostwriter#169]
Thanks for a great app! No doubt the best Markdown app I've found so far!

I couldn't find what Hemingway was supposed to do anywhere in the app, or in the documentation. Please provide at least a more informative tooltip but preferably add a guide under the help menu (not just Markdown syntax) since I had to google and find the explanation in a Github issue. I also found more evidence pointing to me not being the only one confused (https://github.com/wereturtle/ghostwriter/issues/141).

Thanks!

**Comment by suhr** [comment]
Btw, it's a bit broken: you can always select some text and replace it with a new one.

**Comment by wereturtle** [comment]
It's coming.  I've been working on a website update to showcase the features better.  I'll also be sure to add a tool tip to the button.

@suhr, I don't mind if you can still replace text through roundabout ways.  The point of Hemingway mode is to disable two particular keyboard keys that people tend to habitually press to edit.  So, yes, it's working as intended.  :smile:

**Comment by wereturtle** [comment]
I finally got around to completing the website revamp.  Hemingway mode is now explained there.  Cheers!

**Comment by nsrosenqvist** [comment]
Awesome, great job!

**Comment by Symbian9** [comment]
There os good article on this
> On Writing: Hemingway Mode
> 
> Hemingway Mode: A Story of Never Looking Back (At Least During Drafting)
* https://wspucla.wordpress.com/2017/01/23/of-never-looking-back-at-least-during-drafting/
