### ISSUE TITLE
Non standard keyboard shortcuts

### ISSUE THREAD

**Issue by nsrosenqvist** [wereturtle/ghostwriter#170]
I was expecting to close the window by pressing Ctrl+W which is an universal keyboard shortcut on the Linux desktop to close the currently focused window, however in Ghostwriter it previews the HTML. I also fail to see how Ctrl+W would in anyway reference "preview" or "html". Could this behavior be changed to adhere to common standards?

**Comment by wereturtle** [comment]
Sorry about that.  I hadn't realized that Ctrl+W was a universal keyboard shortcut.

I had picked "W" for the "W" in "Previe**w**".  I think "M" should be available.  I'll try for that one in the next release.

**Comment by revanmj** [comment]
Have a similar problem - I got used to Ctrl + K being used for adding a link, not strikethrough text.
