### ISSUE TITLE
Feature Request: Popup Shortcuts list with F1 key

### ISSUE THREAD

**Issue by nonplayer** [wereturtle/ghostwriter#172]
More of a minor UX request. Being able to quickly scan through the various keyboard shortcuts would be pretty damn sweet. F1 to bring up a popup with the list, then F1 again to close.

**Comment by wereturtle** [comment]
Great idea!  And easy to implement, which I like.  😄

**Comment by nonplayer** [comment]
Hooray! Thanks!
