### ISSUE TITLE
Error in syntax highlighting

### ISSUE THREAD

**Issue by pygoliae** [wereturtle/ghostwriter#181]
The fancy_lists extension of Pandoc allows ‘#’ to be used as an ordered list marker in place of a numeral, like this:

#. one
#. two

But ghostwriter misunderstand this syntax, and render each line of this ordered list as a first level header.

**Comment by wereturtle** [comment]
Technically, Pandoc is the only Markdown processor that understands that particular numbered list syntax.  I deliberately chose not to support highlighting for it as a warning for users that it isn't very portable.  I rarely support Markdown extensions in the highlighting (such as piped tables), and only if they are popular enough to be somewhat portable.  I hope that makes sense.
