### ISSUE TITLE
List indent should decrease counter

### ISSUE THREAD

**Issue by waynenilsen** [wereturtle/ghostwriter#19]
I want to start by saying I love this program and it's definitely the best on windows right now even in this somewhat early stage. so CONGRATS! I have one thing that I found that you may think is a bug.

The automatic list creation is great but somewhat flawed in my opinion. When typing the text `1. hi there` then hitting return you end up with 

```
1. hi there
2. <cursor here>
```

which is perfect, but when you hit tab at that point, you get 

```
1. hi there
  2. <cursor here>
```

but I think it should probably (intuitively) be 

```
1. hi there
  1. <cursor>
```

Thanks again for making such a great program. I wish I wasn't terrible at C++ so I could just implement this as a PR

**Comment by wereturtle** [comment]
Hi Wayne,

Thanks for stopping by, and good catch!  I'll be sure to fix that for the next release, which I plan to push out before November.  But don't worry!  It's a pretty easy fix.  The code for handling bullet point indenting is very similar.

Thank you also for the compliment.  I've spent over a year tinkering with this, until I finally had to take my software engineer perfectionist hat off, put on my manager hat, and force myself to release it.  There's always something to tweak, after all.  Glad to know it's working out for you so early on.
