### ISSUE TITLE
Elastic tabstops

### ISSUE THREAD

**Issue by suhr** [wereturtle/ghostwriter#193]
http://nickgravgaard.com/elastic-tabstops/

Proportional fonts are *great* for writing, but they doesn't combine well with markdown tables. Elastic tabstops can fix that.

**Comment by wereturtle** [comment]
Sorry, I'd like to, but unfortunately the QPlainTextEdit and QTextEdit classes for the editor are too limited to do this.  Perhaps in the distant future I'll come up with some way to auto-align the columns using spaces.
