### ISSUE TITLE
Keyboard command to Search & Replace?

### ISSUE THREAD

**Issue by amsheppard** [wereturtle/ghostwriter#202]
* Elementary OS 0.4 (Loki)/Ubuntu 16.04 derivative, amd64
* ghostwriter v1.4.2

Is there a keyboard shortcut/option/toggle/setting to search & replace text? I don't see it listed next to  it within the menu.

**Comment by wereturtle** [comment]
It's `CTRL+F`.  However, I believe Elementary is using a similar hack to the Unity desktop in getting Qt 5 applications' menus to appear in the global menu bar.  Unfortunately, that hack only works with Qt 4 applications, and on Qt 5 applications removes the shortcut keys.  Please follow the instructions for Unity users in the README.md file and see if the workaround works for you.

**Comment by amsheppard** [comment]
I can confirm CTRL-F pulls up "Find" using stock Elementary OS. Is there an expected "Find & Replace" keyboard command (eg: CTRL-R) if I were to purge ```appmenu-qt5``` per your note in README.md? Currently, there's no such indication in the pull down menu for Edit.

**Comment by wereturtle** [comment]
Oh, sorry, brain misfired there.  It's `CTRL+H`.  I have noticed sometimes on Ubuntu bases that either the standard `CTRL+H` or `CTRL-A` mappings won't always show up.  It's quite frustrating.  I've had it on Mint in the past here my `CTRL+H` wouldn't show up in my Qt 5 applications, even though they were definitely mapped.  I think there is some packaging bug or configuration issue.  For me, it actually fixed itself on some update or other.  But it's very random as to whether it will pop up on your installation or not.  Another user was having an issue with `CTRL+A` (for Save As) some time ago in Unity, but `CTRL+H` was fine.

I'm thinking it might be time to file a bug with Canonical about this.  I think they just aren't packaging or configuring something right for Qt 5.

**Comment by amsheppard** [comment]
I can confirm a **lack** of ```CTRL+H``` appearing in the menu. ```CTRL+A``` is not listed in the menu next to _Save As_ nor does it operate as you describe... it's mapped to _Select All._ {_Rename, Reload From Disk, Insert Image, Spellcheck, Cheat Sheet HUD, Document Stats HUD, Session HUD_} are also missing. I assume there's no keyboard mappings intended for _Settings_ or _Help._

If you think it will help your ticket, please find the following:
```
Linux machine 4.4.0-71-lowlatency #92-Ubuntu SMP PREEMPT Fri Mar 24 14:04:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
dpkg -l | grep "qt5"
ii  libqt5concurrent5:amd64                        5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 concurrent module
ii  libqt5core5a:amd64                             5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 core module
ii  libqt5dbus5:amd64                              5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 D-Bus module
ii  libqt5gui5:amd64                               5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 GUI module
ii  libqt5network5:amd64                           5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 network module
ii  libqt5opengl5:amd64                            5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 OpenGL module
ii  libqt5printsupport5:amd64                      5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 print support module
ii  libqt5qml5:amd64                               5.5.1-2ubuntu6                                            amd64        Qt 5 QML module
ii  libqt5quick5:amd64                             5.5.1-2ubuntu6                                            amd64        Qt 5 Quick library
ii  libqt5sql5:amd64                               5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 SQL module
ii  libqt5sql5-sqlite:amd64                        5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 SQLite 3 database driver
ii  libqt5svg5:amd64                               5.5.1-2build1                                             amd64        Qt 5 SVG module
ii  libqt5webkit5:amd64                            5.5.1+dfsg-2ubuntu1                                       amd64        Web content engine library for Qt
ii  libqt5widgets5:amd64                           5.5.1+dfsg-16ubuntu7.2                                    amd64        Qt 5 widgets module
ii  libqt5x11extras5:amd64                         5.5.1-3build1                                             amd64        Qt 5 X11 extras
```

**Comment by wereturtle** [comment]
See issue #142 for reason for closing.  I haven't seen this issue for CTRL+H crop up on newer Ubuntu bases (i.e., Bionic), so I think it's mostly fixed?
