### ISSUE TITLE
Organizing sections via Outline HUD

### ISSUE THREAD

**Issue by FadedStardust** [wereturtle/ghostwriter#204]
One thing that FocusWriter can do, that I would love to see implemented in Ghostwriter, is organizing header sections in the Outline HUD via either drag'n'drop or keyboard shortcuts, possibly ctrl+up/down arrows. This would allow moving large amounts of text in the document without cutting, finding the correct place and pasting the text back in. This is the one feature that keeps me from being able to stick with just Ghostwriter.

Thanks for creating such an amazing app!

**Comment by amsheppard** [comment]
What a great suggestion! It'd be amazing if the ```[TOC]``` (#153) was simultaneously updated.

Can keyboard shortcuts be toggleable on such, should I want to set different shortcuts (eg: a-la-_vim-keys (jkl)_)?

**Comment by jmhibben** [comment]
@amsheppard #153 should be functional as of v1.5.0; I just checked its status, and it seems to have officially made its way in.
