### ISSUE TITLE
message -- document has been modified

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#209]
Hi ... First off ... thanks for creating this SW. I know sometimes it seems to be a thankless job, but we all REALLY do appreciate the SW and the time you put into it.

I've noticed a bug and don't see any open issues relating to it . There's a closed issue https://github.com/wereturtle/ghostwriter/issues/112 that says it's gone away with 1.4.2 but that's what I'm using.

When I do my first save (even if it's IMMEDIATELY) after opening a document, I get the message "The document has been modified by another program. Would you like to reload the document?" This occurs even if I haven't changed anything and just do a Ctrl-S or File > Save. I then get a prompt asking me to discard the changes I've made (even if I haven't made any).

As a work-around, I find it best to do an immediate Ctrl-S as soon as I open the document so that I don't have to discard any changes.

I'm running on Windows 10. The SW is ver 1.4.2

Thanks ... Jeff

**Comment by wereturtle** [comment]
Hi Jeff,

Thank you so much for the kind words.

Unfortunately, being still on Windows 7, I cannot reproduce the issue on my end.  I will leave this issue open, and hopefully more people who might be experiencing it will post here.  Maybe then we can narrow down what is going on.

However, I am going to try a fix for the upcoming 1.5 release.  I noticed there might be a corner case in the code where the last modified time of a file on the disk might be greater than the internal timestamp used for comparison, which could be triggering the issue.  I have patched that corner case, and hopefully that fixes the issue.  If it doesn't, please let me know.

Release 1.5 is about a month out (or less).  So we'll know soon.

If you're feeling really adventurous, you can compile the fix off the master branch and take it for a spin before it is formally released.

**Comment by wereturtle** [comment]
Hi @jeff9315, did the new Release 1.6 fix the issue for you?

**Comment by jeff9315** [comment]
I had completely missed the 1.5 release until now. It seems to have fixed it. Let me use it for a couple of days to see if any Use Cases cause it to happen again. Thanks once again for a WONDERFUL tool.

**Comment by wereturtle** [comment]
Hi @jeff9315, you are welcome!  Glad to hear it's working better so far.  Let me know in a few days if it is now safe to close this issue.  Thanks!

**Comment by jeff9315** [comment]
I think it's working perfectly so I'll close this item.

**Comment by wereturtle** [comment]
Thanks, Jeff!
