### ISSUE TITLE
Suggestion to enhance Ghostwriter

### ISSUE THREAD

**Issue by oscaretu** [wereturtle/ghostwriter#210]
I've begun to using Ghostwriter and I have some suggestions to enhance the program:

- Add option to show (optionally) line numbers
- Add  option to search in the HTML preview. I have huge documents, and when I want to check the resulting rendering of a part of the document that has changed it can be very difficult to find it.
- Add options for different ways of preview. For example, when I generate HTML versions from command line, I use the command line

pandoc -f markdown -t html5 --toc -s my_file.md --highlight-style pygments --number-sections -o my_file.html

and I can't configure this options when I see the preview.

**Comment by wereturtle** [comment]
> Add option to show (optionally) line numbers

There was an issue about that a while back, but the person who volunteered to try implementing it disappeared, so I closed the issue.  Let's just say it isn't a trivial feature.  I think it's possible, but simply painful, and hence not my highest priority.

> Add option to search in the HTML preview.

In about a year, I'll be porting the current WebKit library used under the hood to the Chromium library.  You might end up with this feature for free.  I'll definitely keep it in mind when I port.

> Add options for different ways of preview.

I try to keep the preview options simple.  Pandoc comes with so many options that it can be overwhelming for the end user.  Not to mention that I would have to keep up with every new version of Pandoc that could add or remove options.  What I tend to do is to pick nice default options for Pandoc.  I do, however, have some improvements to both the export and preview options planned for the future.  I will likely be adding an option to generate a table of contents with Pandoc for both the preview and the export.  However, you probably won't be able to see *all* your favorite options.  But it will get better.
