### ISSUE TITLE
Documentation request: Update Linux instructions for Snap package

### ISSUE THREAD

**Issue by amsheppard** [wereturtle/ghostwriter#215]
I was 'bumping around' uappexplorer.com & saw [ghostwriter](https://uappexplorer.com/app/ghostwriter-casept.casept)! Very cool! I didn't see it listed on the Linux install instructions of this github repo.

**Comment by casept** [comment]
Hi, I'm the author of that package! It's not listed in the install instructions because it's not an official package, I mostly made it for my personal use.

**Comment by amsheppard** [comment]
@casept 
I am corrected!

**Comment by wereturtle** [comment]
Hi @amsheppard, as @casept said, I'm not the author of the Snap package.  I'm holding off on officially supporting a Snap package until sandboxing issues can be overcome.  The two valiant attempts the community has made thus far at creating a Snap package still cannot do things like invoke Pandoc to process the Markdown.  Given that part of *ghostwriter*'s core functionality is to interact with other applications, I am wondering if Snap or Flatpak are more trouble than they're worth.  But time will tell.

**Comment by amsheppard** [comment]
@wereturtle 
Copy that! Last nite, I tried installing Discord via snap. It wouldn't see my PulseAudio devices... but 'bare-metal' worked. Ah, the joy of early days, yeah?
