### ISSUE TITLE
Copy/Paste makes word count jump

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#219]
I use Ghostwriter to write articles and when I'm done I paste what I wrote into Grammarly to check for errors. When I'm done correcting, I paste it back into Ghostwriter. When I paste it back into Ghostwriter, the word count doubles. I need to reopen Ghostwriter to get a the correct word count.

**Comment by wereturtle** [comment]
Never fear!  This issue already happens to have a fix that will be released with the upcoming version 1.5.0.  This new version will release either this weekend or next.  (That is my goal, anyway.)

**Comment by JohnBlood** [comment]
Thanks. This is my favorite Markdown editor. I have it installed on all my computers. :+1:
