### ISSUE TITLE
Shortcuts for headings

### ISSUE THREAD

**Issue by johncja** [wereturtle/ghostwriter#225]
Excellent editor. I have tried a lot (Typora, WriteMonkey and some others) and this one is the best.

One thing which I'm missing is shortcuts for headings. 

Ctrl-1 - Convert current line to 1st level Heading
Ctrl-2 - Convert current line to 2nd level Heading
and so on.

Why it's useful? For example, I have some document with 3 chapters across 3 levels of nesting:

```
# Chapter 1
  ## Chapter 1.1
  ## Chapter 1.2
# Chapter 2
  ## Chapter 2.1
     ### Chapter 2.1.1
     ### Chapter 2.1.2
  ## Chapter 2.2
# Chapter 3
  ## Chapter 3.1
     ### Chapter 3.1.1
     ### Chapter 3.1.2
  ## Chapter 3.2
```

And now I want slightly reduce levels of nesting. In other words, I want change

```
       from                      to
------------------------------------------
### Chapter 2.1.1    -->    ## Chapter 2.2
### Chapter 2.1.2    -->    ## Chapter 2.3
### Chapter 3.1.1    -->    ## Chapter 3.2
### Chapter 3.1.2    -->    ## Chapter 3.3
```

To quicky accomplish this task, I would

1. Open outline HUD and click on the "Chapter 2.1.1". I see, that my caret changed it's position and is currently on the desired line. Excellent!
2. Now I just press Ctrl-2 on my keyboard and this line instantly changes it's level from "3" to "2". I don't need to manually erase redundant "#".

```
      before                     after
---------------------------------------------
# Chapter 2                # Chapter 2
  ## Chapter 2.1             ## Chapter 2.1
     ### Chapter 2.1.1       ## Chapter 2.1.1
```

Chapter names, like "Chapter 2.1" and "Chapter 2.1.1" were picked by me just for examples. So, in real life it would be like this:

```
      before                     after
-------------------------------------------------
## Animals          ## General info about animals
   ### Cats         ## Cats
   ### Dogs         ## Dogs
```

That's all. What do you think about it? :smiley: 

Upd. Also, it will be good if Ctrl-0 (Control-zero) will remove any formatting:

```
## Foo    -->   Foo

1. Foo    -->   Foo

> Foo     -->   Foo

etc
```

**Comment by nonplayer** [comment]
This would be fantastic. I got so used to the header shortcuts in GDocs and OneNote that I keep finding myself attempting to use them here and then facepalming when they fail.
