### ISSUE TITLE
Compiled under ARM64 (a.k.a. aarch64)

### ISSUE THREAD

**Issue by JulienAFrozenMiddle** [wereturtle/ghostwriter#227]
I am running linux (xenial) alongside chromeOS (and Android) on my Samsung Chromebook Plus, wanted to give ghostwriter a spin. Compiled from sources.

Downloaded sources, unzipped, cd-ed to that folder and did the following (following the readme):
```
sudo apt install qt5-default
sudo apt install qtbase5-dev
sudo apt install libqt5svg5-dev qtmultimedia5-dev libqt5webkit5-dev libhunspell-dev pkg-config libqt5concurrent5 libqt5printsupport5 libqt5svg5
qmake
make 
sudo make install
```
Worked like a charm and initial testing seems to be all good. Will try the Asus C201 next, which runs an armhf (32 bits) kernel.

**Comment by wereturtle** [comment]
Great to hear!  Thanks!

**Comment by adrian7** [comment]
I managed to compile an older version only on my Pinebook 1080p (KDE Neon/aarch64): 
```bash
sudo apt install hunspell
wget -O ghostwriter-1.6.2.zip https://codeload.github.com/wereturtle/ghostwriter/zip/v1.6.2
unzip ghostwriter-1.6.2.zip
cd ghostwriter-1.6.2
sudo apt install qt5-default
sudo apt install qtbase5-dev
sudo apt install libqt5svg5-dev qtmultimedia5-dev libqt5webkit5-dev libhunspell-dev pkg-config libqt5concurrent5 libqt5printsupport5 libqt5svg5
qmake
make 
sudo make install
```
