### ISSUE TITLE
Complete Task keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by abhinavk** [wereturtle/ghostwriter#229]
Hitting Ctrl+D which is the default key combination for toggling task completion is non-functional. Is there a way to change the key mappings?

Running the latest build on Neon 5.10.2 with Qt 5.9

**Comment by wereturtle** [comment]
Hi, it's working on Antergos with Qt 5.9 / KDE Plasma.  I suspect you may have a Plasma-level shortcut set to use Ctrl+D.  You might want to check your Global Shortcuts dialog under Plasma and see if anything is set.

**Comment by nickcorona** [comment]
Even using the >Edit >Toggle Task(s) Complete button doesn't work. I don't think it's a problem of just the shortcut not working.

Distro: Arch Linux
