### ISSUE TITLE
Can't Get Document Processros Other Than Sundown to Work

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#233]
Recently, I had to reinstall Windows after my hard drive crashed. I installed Ghostwriter and I installed Pandoc and MikTex. At that point, it worked fine. That was two days ago. Now, I can only get Sundown. I reinstalled MikTex and install MulitMarkdown and commonmark, but still only have Sundown. I;d like to be able to convert to something other than HTML.

**Comment by wereturtle** [comment]
Check your Windows environment variables, and make sure the PATH variable includes the directory paths to the Pandoc and MultiMarkdown executables.

**Comment by JohnBlood** [comment]
I reinstalled Pandoc for all users and now it seems to be working.
