### ISSUE TITLE
Redesigned icon

### ISSUE THREAD

**Issue by MarukuSensei** [wereturtle/ghostwriter#237]
I really enjoy using GhostWriter. It's one of the best distraction-free writing apps I've ever used so far.

I can't really support the project, I just don't have the money. What I can do though, is helping out, and making the icon of the app a bit more attractive and modern.

I have no idea if I'm posting this in the right place, and I do apologize if I'm not : I never use github. I don't even know how it works properly.

![ghostwriter icon](https://user-images.githubusercontent.com/16121344/28241097-f7d5505c-698d-11e7-95b8-212b38b05851.png)

**Comment by wereturtle** [comment]
Thank you for your beautiful icon!  I do like the shadow on the original, but don't despair!  Have you ever considered donating your artistic talents to various Linux desktop icon themes?  Various icon theme developers redesign application icons to match a theme, and Linux desktop users can select the theme to give their application icons a new look.  Not too many themes out there have a matching *ghostwriter* icon.  Yours would fit pretty well in several themes I've seen.

The [Moka icon theme](https://snwh.org/moka), which has its GitHub repo [here](https://github.com/snwh/moka-icon-theme) would be an example of a project to which you could donate your icon (as well as other artwork for other applications).  And remember, this is just one theme of many that needs a *ghostwriter* icon.  Having *ghostwriter* icons for the most popular Linux icon themes would be amazing!
