### ISSUE TITLE
Increase shortcut does not work on Windows

### ISSUE THREAD

**Issue by jenstornell** [wereturtle/ghostwriter#241]
`Ctrl + =` does not work. It gives `1)`.

**Comment by wereturtle** [comment]
I suspect this is an issue with Qt 5.5.  I have an experimental build with Qt 5.9 in Windows, and the `Ctrl+=` shortcut is working (i.e., it's increasing the font size).  So this should be fixed with the next release.  Of course, this might be a while.

Thank you for your report.
