### ISSUE TITLE
Fedora 26 version ?

### ISSUE THREAD

**Issue by bepolymathe** [wereturtle/ghostwriter#242]
Hi,

I would be a very great progress to have a fedora version for ghostwriter. 
At this time, only this [fedora copr depo](https://copr.fedorainfracloud.org/coprs/abn/ghostwriter/) exist for fedora 25. 
Any plan for this ?

**Comment by wereturtle** [comment]
Hello, I am not the maintainer for the Fedora version.  I'm afraid I only have enough energy to maintain the Ubuntu PPA at this time.  However, if you are interested in volunteering to maintain a Fedora version, I would be happy to link to your repo.

Thanks!

**Comment by bepolymathe** [comment]
unfortunatly i don't have competences for that. Thanks for reply
