### ISSUE TITLE
Allow single backspaces to correct typos in Hemingway mode

### ISSUE THREAD

**Issue by paramjit** [wereturtle/ghostwriter#243]
Firstly, I love you. Thanks for this amazing piece of software. This is exactly what I needed to write whenever I want to just pour my thoughts.

Now coming to the issue, it will be nice if we can have single or two (three?) backspaces in Hemingway mode, so that we can correct immediate typos instead of having to manually toggle Hemingway mode. I know this is supposed to emulate a typewriter, but then again, people are much more faster on a keyboard than on a typewriter (saying from personal experience) and hence more likely to make typos.

An optional autocorrect feature might also solve the problem, but that may not be ideal as it limits the vocabulary to the dictionary.

**Comment by wereturtle** [comment]
Hi @paramjit!  The point if Hemingway mode *is* to disable the backspace and delete keys, to force the writer to not be tempted to edit the document while writing.

Happy writing!

**Comment by paramjit** [comment]
Oh! Now I get it, so that the writer doesn't edit during writing. Damn. Thanks for the time.
