### ISSUE TITLE
Session word goals

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#244]
What do you think about configurable session word goals like focus writer has them. Perhaps not with a history, but with a kind of progress bar or pie-chart for the current session like Ulysses. It helps to stay motivated and keep the daily pace up.

![](https://i2.wp.com/www.agdaws.com/wp-content/uploads/2015/12/Blue-Panel.png)

**Comment by wereturtle** [comment]
The feature is somewhere on my to do list.  I agree it is a nice feature, but it falls closer to my bucket list than the urgent-must-do-soon list.  It would definitely be useful for NamoWrimo.

**Comment by JohnBlood** [comment]
I second the motion for this feature. Maybe it would be displayed in the document statistics window.
