### ISSUE TITLE
Calculate WordsPerHour

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#245]
I find the metric `words / hour` more meaningful than `words / minute`, especially when you're working on a text in long sessions, it helps more to estimate the overall session quality and progress.

Perhaps we can display display it next to the WPM value?

**BTW:** Does it really make sense, to calculate the WPM value just for the non-idle time? So it does not fit into the rest of the stats when you just see the total time and the words written. It also would make more sense to use the total-time, because this is no typing-trainer. Writing involves thinking and that falls into the idle time.

**Comment by wereturtle** [comment]
I prefer the conventional WPM statistic.  I like knowing how fast I'm actually typing, so I can push myself to go faster.
