### ISSUE TITLE
Usability: Find and replace could be combined?

### ISSUE THREAD

**Issue by pedrodude** [wereturtle/ghostwriter#247]
I guess this could be related to #202 so my apologies if it should be there instead.

The Find dialog could simply be dropped?  The functionality is completely redundant given the Replace dialog exists.  Although given the discussion in the other issue, presumably multiple shortcuts could be directed at that single dialog to allow everyone to continue to use the keyboard combos they already know and love.

Btw, only recently discovered this application.  It's bloody good 🙂

**Comment by wereturtle** [comment]
Find plus find and replace dialogs are a GUI standard.  I'm sorry the shortcuts are spotty.  This seems to be some weird configuration thing depending on the distro configuration with Qt.  If it happens with one Qt app, it will happen with all of them.

Thanks for the compliment!

**Comment by pedrodude** [comment]
Fair enough; I found this interesting discussion on UX stack if you're interested: https://ux.stackexchange.com/questions/94295/why-do-most-programs-separate-find-and-replace-dialogs.  The "safety" justification seems a little thin to me but I can understand the urge to stick to convention.
