### ISSUE TITLE
Installing on Solus (no distro-generic tarball?)

### ISSUE THREAD

**Issue by navedcoded** [wereturtle/ghostwriter#248]
Hi!

I would love to use Ghostwriter -- but I really cannot find a way to install it on Solus. It does not support .deb or any of the volunteer provided methods. On the releases page, I can only find a source code tarball -- am I just missing something, or is there really no way to install officially on a non Ubuntu linux system?

**Comment by icaroperseo** [comment]
Hi!

You can find the source code tarball list [here](https://github.com/wereturtle/ghostwriter/releases) and download the last release from [here](https://github.com/wereturtle/ghostwriter/archive/v1.5.0.tar.gz).

Referring to the _ghostwriter_ installation, I suggest you:

1. _The better and painless way_: Try to contact the _Solus OS_ developers to ask them to provide an official package.
2. _If you want to go on your own or the_ `/dev/null` _way_: You can try the following:

```
tar -xvzf "foo.tar.gz"
cd "pkgname-pkgver"
lrelease translations/ghostwriter_*.ts
qmake PREFIX=/usr
make
sudo make install
```

Replacing _"foo.tar.gz"_ with the tar.gz file name and _"pkgname-pkgver"_ with the new dir name. Remember to comply with the dependencies, for this, you can have a look at [Arch Linux package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ghostwriter-l10n-git) especially at the sections:

+ depends
+ makedepends
+ optdepends

Best regards and good luck!

**Comment by navedcoded** [comment]
Thank you for your fast and comprehensive reply 👍 I'll try now, if it doesn't work I'll ask them to package it. Thanks again!
