### ISSUE TITLE
Feature request: Turn HUD into sidebar

### ISSUE THREAD

**Issue by nnvn** [wereturtle/ghostwriter#250]
First of all, thank you for this awesome app. 

Is it possible to convert HUD into a sidebar. This would help to get the editor focused while Alt-Tabbing. Thanks

**Comment by wereturtle** [comment]
That's strange.  The editor is the only window listed in *ghostwriter* when I Alt+Tab on Windows 7, as well as on Cinnamon, Gnome, and KDE Plasma 5 desktops.  Out of curiosity, what OS / desktop environment are you using?  Anyway, I have no plans for a sidebar at this time.  Sorry.  (But the good news is that I've put the HTML preview as a split pane now.  That feature is on the dev branch.  So things should get a little easier soon enough.)

**Comment by nnvn** [comment]
I'm using xfce on xubuntu. thanks.
