### ISSUE TITLE
Feature Request: Optionally show cursor position

### ISSUE THREAD

**Issue by estan** [wereturtle/ghostwriter#253]
As `row:column` in the status bar maybe, and optionally visible also in fullscreen mode.

**Comment by wereturtle** [comment]
Closing this issue.  Please read the [contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for details.  Thank you for your interest!

**Comment by estan** [comment]
Ah, sorry, I missed that! No worries.
