### ISSUE TITLE
Running Python or R code in dynamic documents

### ISSUE THREAD

**Issue by daacosta** [wereturtle/ghostwriter#254]
Hello,

Is there any way to run R or Python code as it is done in R Markdown?  I found the following R package RSP but I don´t have a clue as to how to invoke it from Ghostwriter and how to make it work to create dynamic documents... I don´t mind working with R Markdown but I happen to like Ghostwriter a lot...

Many thanks,

-D-

**Comment by wereturtle** [comment]
Hi @daacosta, ghostwriter cannot invoke Python or any other scripting language, I'm afraid.
