### ISSUE TITLE
Way to close last opened file, or start with a new one

### ISSUE THREAD

**Issue by sergeevabc** [wereturtle/ghostwriter#255]
Every time Ghostwriter is launched, the last opened file is loaded, which is not convenient sometimes. There should be a way to avoid this, which is usually accomplished by closing the last opened file (by File/Close or Ctrl+W shortcut). Then a new unnamed tab/window is expected.

**Comment by wereturtle** [comment]
Hello!  You can press `CTRL+N` to start a new, untitled document, so there is no need to have a "Close" shortcut.

Also, see issue #135, which is planned for the next release to make loading the last opened file optional.

**Comment by sergeevabc** [comment]
Hmm.

1. Open some file.
2. Press Ctrl+N.
3. Close Ghostwriter.
4. Some file is re-opened instead of new, untitled document.

**Comment by sergeevabc** [comment]
@wereturtle, err, hello? Have you tried to reproduce the steps?
