### ISSUE TITLE
Question about editing Wiki

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#256]
I created a short page for the wiki on how to add more document processors to Ghostwriters. The problem is that when I use GitHub for Windows to merge it, it says that I don't have editing authority. How can I edit/add to the wiki?

**Comment by JohnBlood** [comment]
@wereturtle , it looks like only contributors to the project can edit the wiki by default, but that can be changed. https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by wereturtle** [comment]
Done!  Edit away!
