### ISSUE TITLE
Is there a possibility to write in other languages?

### ISSUE THREAD

**Issue by ostrol** [wereturtle/ghostwriter#258]
Is there a possibility to write in other languages? For example, in British English, Russian or Polish?

**Comment by suhr** [comment]
Да, разумеется есть.

**Comment by abenson** [comment]
Yeah, just write... If you need spell checking, just install the right hunspell dictionary and change the language in Settings->Preferences->Spell Checking.

**Comment by Symbian9** [comment]
> Is there a possibility to write in other languages? 

Think, you your qeustion related to limited number of languages in menu "Settings > Language". This is list availiable locales at this momemt (language for UI). Soon more locales should be added.

You not limited in writing documents in any language! ;-)
