### ISSUE TITLE
Pandoc update broke exportation

### ISSUE THREAD

**Issue by sallirom** [wereturtle/ghostwriter#260]
Hi,

pandoc was updated 8 days ago. https://github.com/jgm/pandoc/releases/tag/2.0.2

It seems to be a slight change in the grammar of pandoc, or at least, I get this error message when I try to export the document:

>Export error: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.

Incidentaly, multimarkdown was also updated on the 13th of october. 
https://github.com/fletcher/MultiMarkdown-6/releases

When I try to export using multimarkdown I get:

>MultiMarkdown: invalid option "--smart" Try 'multimarkdown --help' for more information.

It is strange nobody else has said something about this, I am no expert, maybe I just messed all up.

Excuse me if that would be the case.

Thank you,

**Comment by wereturtle** [comment]
Thanks for the heads up!

Until I get to fixing it, you can turn off the smart extension when exporting by unchecking the option in the Export dialog.  Unfortunately, this won't help you with HTML previews, as that is baked in.

**Comment by sallirom** [comment]
Thank you very much!

you are the best :)

**Comment by Seraphli** [comment]
I'm wondering when the new version will release. It has been almost a month.

**Comment by jkruppa** [comment]
Unfortunately, I am forced to work on a Windows machine... I really liked your program, but I use mainly the Pandoc Preview, which is now not available...

Can you make a new version available?

**Comment by wereturtle** [comment]
Hi @jkruppa, the next version will be releasing Soon (tm).  In the meantime, try downloading an older version of the Pandoc zip from the Pandoc website and putting the Pandoc executables where the ghostwriter.exe is.  The app will find that version of Pandoc first, as it would be in the same directory.  (I assume you are using the portable version of ghostwriter, so you should not need to be an admin to do this.)

**Comment by andi-blafasl** [comment]
Is there a release date on the road-map for the next ghostwriter version? It looks like many people facing this Issue.
The statement from January "Releasing Soon (tm)" is not really satisfactory ;-)

**Comment by wzhangbeibei** [comment]
HI I got this reply
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
--normalize has been removed.  Normalization is now automatic.
Try pandoc --help for more information.


Then I use the recommended "pandoc -f markdown+smart -t markdown-smart"
and then I got this "pandoc: pandoc: openBinaryFile: does not exist (No such file or directory)"

Help me please---

**Comment by abenson** [comment]
Are you running the latest pandoc and latest ghostwriter?

**Comment by tecosaur** [comment]
I seem to be getting this issue with `Ghostwriter version: 1.7.4, release: 13` (quote my package manager) and `pandoc 2.2.1`.

> Export error: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.

**Comment by wereturtle** [comment]
@tecosaur I'm not seeing that issue with Pandoc 2.5 and ghostwriter 1.7.4.  The source code that figures this all out looks like so:

![image](https://user-images.githubusercontent.com/10375170/50541945-a3401880-0b65-11e9-8a70-daab9333ebbe.png)

The question is, does that particular version of Pandoc, as packaged for Solus, print out it's version in expected manner?  ghostwriter parses for a specific version format from the output of `pandoc --version`.  If it changed for any reason on Solus or in that particular version, you could end up in a case where ghostwriter thinks it's using Pandoc 1.x instead of 2.x.  If you can, please provide the exact output of `pandoc --version`, and I can see if something went wrong with the version parsing.

**Comment by tecosaur** [comment]
Here's my full output from `pandoc --version`.

```     
pandoc 2.2.1
Compiled with pandoc-types 1.17.4.2, texmath 0.11.0.1, skylighting 0.7.1
Default user data directory: /home/tec/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by tecosaur** [comment]
@wereturtle I'd be great to hear back from you. I'd really like to use a ghostwriter to integrate with my latex tools, and not being able to use Pandoc is somewhat ruining this for me. If you'd be able to help me figure this out I would really appreciate this as it absolutely crucial for my use case; It's killing me given how much I like using the app.

**Comment by wereturtle** [comment]
@tecosaur 
I've installed Solus in a VM with ghostwriter and pandoc on it, all up to date.  I could not replicate your issue.  Pandoc is working fine in the preview and for exporting.  Do you have any more specific steps I could follow?  You've used the normal Solus Software Center tool to install both ghostwriter and pandoc, correct?  Regardless, since things work on a fresh install of Solus, you might want to try reinstalling your OS to get things working.

**Comment by wereturtle** [comment]
@tecosaur 
Actually, were you trying to export to PDF with wkhtmltopdf?  I ask because the error message you got looks suspiciously like the one in issue #412.  If so, you can work around the issue by using the latex backend, or even export to ODT and then using LibreOffice to convert that to PDF.

**Comment by tecosaur** [comment]
@wereturtle Just got a fresh install of Solus and it worked. Thanks for going to all the trouble of setting up a VM to test it :smiley:

**Comment by wereturtle** [comment]
@tecosaur, that's great to hear! Thanks for the update!

**Comment by Korsani** [comment]
Hi,
I'm facing the problem on Windows 10 with pandoc 2.7.3 and ghostwriter 1.8.0
Disabling Smart on export is ok, but preview is broken...

**Comment by SobhanMP** [comment]
Hi

using mathjax instead of mathml fixes the issue.
should this be added as an option?
or is there some other reason to prefer mathml?
