### ISSUE TITLE
 Add an option to hide menu bar

### ISSUE THREAD

**Issue by belenos** [wereturtle/ghostwriter#261]
Please add an option to hide the menu bar and to show it by pressing the Alt key, like Abricotine does. That makes the UI cleaner.

**
I'm using Ubuntu 17.10 / Gnome Shell.

**Comment by suhr** [comment]
There's already an option to hide the menu on fullscreen.

**Comment by belenos** [comment]
I know. And I think it should work on windowed mode as well.
