### ISSUE TITLE
Bulleted List - slightly inaccurate behavior

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#263]
Hi ... First off ... thanks for creating this SW. Every time I stop using it for a while and come back to it, I remember why I LOVE it!

Copying a bulleted item

If I have this to start with

```
* Line one
* Line two
* Line Three
* Line Four
* Line Five
* Line Six
```

And I copy and paste Line five to another spot, the following is the result

```
* Line one
* Line two
* * Line Five
* Line Three
* Line Four
* Line Six
```

It's occurring because it first thinks I'm going to add a new bulleted line so it adds the *. And then it copies the line with the *. It should delete one of them during the paste operation.

Thanks again ... Jeff

**Comment by wereturtle** [comment]
It looks like you copied the entire line, including the asterisk, and then pasted it after hitting enter after a bullet point.  Is that correct?  Or is something else afoot?

**Comment by jeff9315** [comment]
Yes, you are correct.

**Comment by wereturtle** [comment]
I'm afraid then that the app is working as intended.
