### ISSUE TITLE
Multiple copies of the same document accidentally opened

### ISSUE THREAD

**Issue by jeff9315** [wereturtle/ghostwriter#266]
Hi ... I'm using Ghostwriter 1.5.0. I've lost my changes a couple of times. I suspect it's "operator error" due to the fact that I opened a document and then without realizing it opened it again. Then accidentally made separate changes to both copies. Or something like that.

It would be good if it only allowed you to open one copy of the document or warned you if you were opening a second copy.

Thanks for a WONDERFUL product ... Jef

**Comment by wereturtle** [comment]
I'm afraid that's pretty normal behavior for text editors if you mistakenly edit the document in both.  Thanks for reporting anyway!

**Comment by jeff9315** [comment]
A lot of times there's an option in the settings to open only 1 window and have a tabbed interface. In that case, I believe the normal behavior is to simply take you to the already opened tab.

**Comment by suhr** [comment]
Indeed, it makes sense to just notify the window instead of opening a new one.
