### ISSUE TITLE
Blockquote Color Too Light

### ISSUE THREAD

**Issue by DevelopRx** [wereturtle/ghostwriter#269]
On light-colored themes, the blockquotes font color fades from the base font and it's hard for me to see in the editor. This is especially problematic in custom light themes. 

I'm working around it by using the strong format after the blockquote:  `>**Bolded Block**`.  With this, I can see the text, but of course the formatting is off in HTML.

Ideally, it would be great to have blockquotes formatting options in the themes, but that sounds more like an enhancement. Would it be possible to just turn the `fadeColor` off with a special `blockquoteStyle` in ghostwriter.ini or something like that?

Thanks!

**Comment by wereturtle** [comment]
This will be fixed in the next release, which I should hopefully be able to kick out the door before the New Year.

**Comment by DevelopRx** [comment]
Excellent. Thank you.
