### ISSUE TITLE
Can it point to a custom pre-processor?

### ISSUE THREAD

**Issue by jeremydouglass** [wereturtle/ghostwriter#270]
Does Ghostwriter have a way of pointing to a custom preprocessor step that can be added before the main Markdown processor, and will affect realtime preview?

I am trying to find a Windows equivalent for what is available in e.g. Marked2 for macOS X:

http://marked2app.com/help/Custom_Processor.html

This is a request for information -- if it is currently not possible, either at the UI level or at the configuration file level, but it might be easy to hack in at the code-and-recompile level, then I would also be interested in suggested starting places in the code base.

**Comment by wereturtle** [comment]
Afraid not.  Sorry.
