### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by nickcorona** [wereturtle/ghostwriter#271]
Full Error: [WARNING] This document format requires a nonempty 

- Using "Pandoc" markdown converter
- "Smart typography" is unchecked

**Comment by G3A** [comment]
Hi nickcorona.  

At this time, you must install an earlier version of Pandoc 2.0 until this jewel is updated once from open source called ghostwriter. By the way, this is my first comment on github publicly after having registered many years ago :D

**Comment by wereturtle** [comment]
What @G3A said.  See issue #260 for further details.
