### ISSUE TITLE
Trying to surround a period in quotes sometimes results in a segfault

### ISSUE THREAD

**Issue by 4of92000** [wereturtle/ghostwriter#272]
I'm using Ghostwriter 1.5.0 with MATE on Debian 9. The steps reproduced below *always* result in a segfault, but the final step will sometimes do it in other circumstances. Unfortunately, it's pretty sporadic, so I can't be specific, but it happens pretty often.

**Steps to reproduce:**

1. Open a fresh instance of Ghostwriter.
2. Enable Focus mode.
3. Type a sentence ending in a period. (You can type multiple sentences, and it doesn't matter which one you select.)
4. From the sentences below, select a period that ends not just a sentence but a paragraph.
5. With the period selected, try to type a double-quote.

**What should happen:**

The period is surrounded in double-quotes. (This does happen if Focus is not on, usually.)

**What does happen:**

The program segfaults and I lose all my unsaved data.

Thanks for getting onto this. I find Focus to be particularly useful and would like to keep using it, but if that is going to happen then I'm going to have to leave it off.

Besides that, Ghostwriter is a really good app. Keep up the good work.

**Comment by suhr** [comment]
It would be helpful to provide a backtrace. This is how you can get it:

1. Open a terminal. Run `gdb ghostwriter` in it
2. Type `run` in the GDB command line, press enter
3. Ghostwriter will start. Now you should reproduce the bug
4. Ghostwritter crashed. Type `bt` in the GDB command line. This will print the backtrace, extremely useful for debugging.

**Comment by abenson** [comment]
I was able to recreate the crash, also on Debian 9.

Here is the [backtrace](https://github.com/wereturtle/ghostwriter/files/1605287/backtrace.txt).

**Comment by wereturtle** [comment]
Thanks for the backtrace!  The fix will go on the next release, which should release Soon (tm).  (I have to tie up a pretty bow first and then ask the translators to update the translations when they can.)
