### ISSUE TITLE
Indenting/Unindenting breaks numbered list sequence

### ISSUE THREAD

**Issue by Axatchaudhary** [wereturtle/ghostwriter#276]
When I am writing in numbered list, suppose I am at the 4th item, and if I to press "Tab" then my cursor moves forward and changes number from "4)" to "1)", then if I press "Shift+Tab" to unindent, the number does not change back from "1)" to "4)". I am not sure if it is supposed to work that way. See below sequence of actions.

I am at the 4th place.
![image](https://user-images.githubusercontent.com/7285865/34640468-1a5bd55a-f319-11e7-867a-1b2af63f2848.png)

I press Tab.
![image](https://user-images.githubusercontent.com/7285865/34640473-42f2a192-f319-11e7-8452-d3349a25d95c.png)

Then I press Shift+Tab
![image](https://user-images.githubusercontent.com/7285865/34640477-53270be8-f319-11e7-90f9-d3d3daaf64fb.png)

**Comment by felipehw** [comment]
@wereturtle 
To solve this bug in a simple way ... could we have an option to don 't increase the number in the markup of a numbered list?
I like to have my numbered list just like:
```
1. a
1. b
1. c
```
And the automatic increases of the numbers plus this kind of bug makes me fight with the editor ...
