### ISSUE TITLE
QWebkit

### ISSUE THREAD

**Issue by cascarpato** [wereturtle/ghostwriter#277]
Hi ,
i have a iMac OSX El Capitan and i'm giving a look at code, but i noticed that you use WebKit to render webpages. Webkit was deprecated in favor of webengine. Did you planned to switch at webengine? 
I Use qt 5.9  and i can't try to compile it.
My compliments for your  great work.

**Comment by wereturtle** [comment]
Hi,
Please see issue #78, which should answer your questions.  The final comment in the thread has a link to annulen's fork.  I have thus far had success dropping in the alpha version of that into a Qt 5.9 Windows build.  I would imagine it would work just as well dropping in the libraries for the Mac version.
