### ISSUE TITLE
"Smartiffy" it

### ISSUE THREAD

**Issue by licinioamendes** [wereturtle/ghostwriter#28]
Would be nice to have editor knowing when something ended, example:

![capture](https://cloud.githubusercontent.com/assets/1760921/10042001/7637f574-61e0-11e5-88cc-f062b81eb764.PNG)

When using `*` if the previous `*` is empty then the editor would remove the previous and actual `*` and add a empty line, result would be like:

![capture1](https://cloud.githubusercontent.com/assets/1760921/10042068/e1cb3350-61e0-11e5-8a73-5802989776be.PNG)

Same for other elements.

**Comment by wereturtle** [comment]
Your wish is my command!  It will be in the next release (1.2.0).  In the meantime, the change is already in the master branch, in case you want to build it yourself and have a sneak preview.
