### ISSUE TITLE
problem with windows focus

### ISSUE THREAD

**Issue by fockr** [wereturtle/ghostwriter#281]
When switching between windows - i.e. I use Alt+Tab to switch from Ghostwriter to Firefox and back - I cannot continue writing if a HUD is activated (i.e. session statistics). Instead the focus lies on the HUD window. When this happens I have to use the mouse and click the cursor back into the text to be able to continue to write - even though the focus before switching was on the text.

I'm using Linux Mint OS 18.2 64 bit.

Cheers!

**Comment by wereturtle** [comment]
Which desktop environment are you using?  Is it XFCE?  That one has some funny issues with alt-tabbing, I've noticed.  Otherwise, please let me know which one so I can try to replicate the issue.

**Comment by fockr** [comment]
Sorry for missing that one out... I'm using Cinnamon. So this issue normally shouldn't happen?

**Comment by Gizmaton** [comment]
Can confirm that this bug occurs on Windows 10 as well.
