### ISSUE TITLE
Add feature to HUB 

### ISSUE THREAD

**Issue by Iuritics** [wereturtle/ghostwriter#287]
Hello,
I am not a programmer. But I love the app. Sorry if this is not the place to ask for this. In tha case, just tell me and sorry. 

Could it be possible to add a feature to the HUB function in order it folds and unfodls the headings when there are too many of them?. Just as the outliners expand and collapse the nested contents to make the information saved more usable.
In such a case, could it be possible to collaborate?.

**Comment by wereturtle** [comment]
Sorry, in order for the app to be fast with large documents, it needs to stick with the plain text editor widget that it is using, and not use folding that could slow it down.

Thank you for your interest!

**Comment by Iuritics** [comment]
No wonder what you say. It makes sense. Thanks a lot for the app anyway. I will be following it, anycase, it is very useful and it feels great. Thanks again for the answer as well.
