### ISSUE TITLE
Menu bar not showing

### ISSUE THREAD

**Issue by knzudgt** [wereturtle/ghostwriter#288]
I installed ghostwriter in my Ubuntu 14.04 LTS machine with MATE as desktop environment.
The menu bar is not showing up, so I am unable to interact with ghostwriter.
Do you have any advice on this issue?

![screenshot from 2018-02-01 16 32 30](https://user-images.githubusercontent.com/15718033/35686961-d462b406-076d-11e8-908f-3900f7d38995.png)

**Comment by suhr** [comment]
> Do you have any advice on this issue?

It doesn't show up even if you move your mouse in the place where it should be? Does `F11` do anything?

**Comment by abenson** [comment]
Doesn't Ubuntu use the common menu bar at the top?

**Comment by knzudgt** [comment]
I tried to move the mouse all over the window and on any place where it should be, but it does not appears any menu. I also tried all the F1-F12 keys with no change.

**Comment by wereturtle** [comment]
Please confirm that `appmenu-qt5` is not installed on your system.  This particular library is used in Unity to put Qt apps' menu bars into the global menu bar.  While I realize you are using Mate with no global menu, it might still be installed.  Since your symptoms appear similar to what `appmenu-qt5` does, it's definitely worth a look.

**Comment by knzudgt** [comment]
@wereturtle appmenu-qt5 results installed

**Comment by abenson** [comment]
It seems to be a know and apparently unfixed [buy](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619).

You can remove the `appmenu-qt5` package. Or, you can try [unsetting `QT_QPA_PLATFORMTHEME`](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619/comments/9) or [fixing the file that sets it](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619/comments/22).

**Comment by knzudgt** [comment]
I chose to fix the `/etc/profile.d/appmenu-qt5.sh` file. Thanks @abenson , now it works.
