### ISSUE TITLE
Add dictionary for spellcheck

### ISSUE THREAD

**Issue by knzudgt** [wereturtle/ghostwriter#290]
Is it possible to add a non-English dictionary for spellcheck?

**Comment by abenson** [comment]
Any hunspell dictionary works.

**Comment by knzudgt** [comment]
@abenson where am I supposed to add my hunspell dictionary?
Under `Settings > Preferences > Spelll Check` is not possible.

**Comment by abenson** [comment]
If you are on Linux install through the package manager

**Comment by knzudgt** [comment]
@abenson Synaptic shows no hunspell italian dictionary. It lists many dictionaries, with hunspell-en-us installed, but not italian.
I have my own `it_IT.aff` and `it_IT.dic` files: is there any way I can install them myself?

**Comment by abenson** [comment]
Package name should be `hunspell-it`.

**Comment by knzudgt** [comment]
Yes, it is `hunspell-it` but it can only be found on xenial, zesty, artful and bionic.
Trusty (14.04LTS) has not a `hunspell-it` package.
See [Ubuntu packages](https://packages.ubuntu.com/search?keywords=hunspell).

**Comment by knzudgt** [comment]
For Ubuntu 14.04 LTS it is necessary to install the `myspell-it` package. Newer versions of Ubuntu have the `hunspell-it` package instead.

**Comment by PrSunflower** [comment]
Thanks for the instructions.

@wereturtle Could you indicate in the README.md how to install spellcheck dictionaries please?

I am a non-programmer using Debian 10 and it wasn't written in the Readme how to install dictionaries for other languages.
