### ISSUE TITLE
How does ghostwriter behave with large txt files?

### ISSUE THREAD

**Issue by knzudgt** [wereturtle/ghostwriter#291]
Is it possible to use ghostwriter for writing long novels in text format?
I am planning to use ghostwriter not as markdown editor but as writing software.
I started to use Bibisco, but when I reached 24736 words and 154834 characters (156.2 KB), Bibisco was unable to proceed, apparently for a bug with large files ([See Oh no! An error has occured · Issue #139 · andreafeccomandi/bibisco](https://github.com/andreafeccomandi/bibisco/issues/139)). I wonder how ghostwriter would behave with txt files of over 200,000 words and over 1,000,000 characters.

**Comment by abenson** [comment]
![Testing](https://user-images.githubusercontent.com/227317/35786046-43f1ebd8-09ea-11e8-8242-55e9714b1e3a.png) with [this](https://norvig.com/big.txt) file, which is 6.2M, ghostwriter seems to do fine. 

I was able to scroll, edit, and everything seems fine. It's a little slow to open but seems fine. The process is only taking up about 200M of memory, too.
