### ISSUE TITLE
.txt unformatted

### ISSUE THREAD

**Issue by aleksei-4an** [wereturtle/ghostwriter#292]
Hi. 
When I open a .txt with Notepad, for example, saved by GhostWriter, it is unformatted, with all paragraphs together, without breaking lines. I'm using Windows 10 Pro x64 1709.

**Comment by abenson** [comment]
Try opening it in a different editor, like wordpad. It sounds like the file
was saved using *nix line endings, which notepad does not support.

**Comment by aleksei-4an** [comment]
With Wordpad it opens right. Notepad is the fastest way to make a note or a correction in a .txt.
But that's OK. Thanks, man!

**Comment by wereturtle** [comment]
I think this may be an issue with Qt.  It's supposed to automatically put in the correct line endings based on the platform.  I'll see if the very near future upgrade to Qt 5.9 in the Windows package will fix it.

**Comment by aleksei-4an** [comment]
Great news.
Nice software. Simple.

**Comment by aleksei-4an** [comment]
Hi. It was working, now it's not again. Cheers anyway!

![1](https://user-images.githubusercontent.com/36139848/39087575-4b4c0560-4579-11e8-802a-6978d77776f9.jpg)
![2](https://user-images.githubusercontent.com/36139848/39087577-4ed6e5d8-4579-11e8-842c-4201ae4e5188.jpg)
