### ISSUE TITLE
Packaging: Fedora repo not maintained, could you do Flatpak instead?

### ISSUE THREAD

**Issue by deejf** [wereturtle/ghostwriter#293]
The Fedora Copr repo for ghostwriter hasn't been updated in over a year, and is for Fedora 25, while Fedora is on release 27.

Instead of having to continuously update for different distros and repos, you could do a [FlatPak](http://flatpak.org/) version, so that it's truly cross-platform. 

I say this in some frustration, because I'd *like* to write in ghostwriter over anything else, but am not enough of a tech-head to build from source every single release cycle. I'm a writer and editor, and wasting a day or two figuring out how to do a correct install every six months or so is not an option. The day I see ghostwriter listed on [Flathub](https://flathub.org/apps/) will be a happy day indeed.

**Comment by abenson** [comment]
I had been maintaining an el7 package for a while. I also maintain the Void
package now. I could probably part-time maintain an unofficial el7/fedora
package(s) as well, as that's relatively easy.

I'll look into that.

**Comment by wereturtle** [comment]
I will be doing a Flatpak sometime in the future.  In the meantime, yes, volunteers are very much wanted for packaging for other distros!

Thanks, @abenson, for stepping up.  Let me know in this thread what the link is that I should include for a Fedora package, so that I can direct users to it in the next release.

**Comment by wereturtle** [comment]
Thanks, @bavier!

**Comment by rugk** [comment]
See also discussion in https://github.com/wereturtle/ghostwriter/issues/345

**Comment by wereturtle** [comment]
ghostwriter is now on Flathub.  Enjoy!
