### ISSUE TITLE
Translation updates for release 1.6.0

### ISSUE THREAD

**Issue by wereturtle** [wereturtle/ghostwriter#294]
@suhr @dbelyaev @jggouvea @tajmone @piyo-gh @dhbwmawhd @pafri @pygoliae @cemetary @mleko69 @icaroperseo

Hello everyone!

Release 1.6.0 of ghostwriter is almost ready to be set loose into the wild!  All that remains is your help in providing updates to the existing translations.  I plan to release in roughly one month (or sooner if all of you complete your updates before then).  If you need more than one month to make updates, please let me know, and I will accommodate your schedule.  You may submit via pull request against the master branch, or else by attaching your .ts file to this thread.  (Please ensure that your .ts file is done against the master branch, as all code from the dev branch has been merged here.)

Thank you in advance for volunteering.  You have all been amazing!

**Comment by pafri** [comment]
Hi,
here is the file. 330 string (I've downloaded the zip archive - ghostwriter-master, and let run lupdate command)
Greetings, Pavel Fric
 

    On Saturday, February 10, 2018 11:48 PM, wereturtle <notifications@github.com> wrote:
 

 @suhr @dbelyaev @jggouvea @tajmone @piyo-gh @dhbwmawhd @pafri @pygoliae @cemetary @mleko69 @icaroperseoHello everyone!Release 1.6.0 of ghostwriter is almost ready to be set loose into the wild! All that remains is your help in providing updates to the existing translations. I plan to release in roughly one month (or sooner if all of you complete your updates before then). If you need more than one month to make updates, please let me know, and I will accommodate your schedule. You may submit via pull request against the master branch, or else by attaching your .ts file to this thread. (Please ensure that your .ts file is done against the master branch, as all code from the dev branch has been merged here.)Thank you in advance for volunteering. You have all been amazing!—

**Comment by tajmone** [comment]
A month deadline gives me good respite. Currently I'm entangled in a project I'm about to close, but hopefully it will be handled within this cominh week; after that, I'll be able to get down to the translation update work.

**Comment by dbelyaev** [comment]
Hello! [PR #295](295) with updated Russian translation added.

**Comment by tajmone** [comment]
Italian translation updated. I hope everything went right, this time I've found only a few non-translated strings, and a bunch of other strings for which QT Linguist had already suggested the translation. I was expecting more untranslated strings.

It's been a while I haven't used QT Linguist (and I always find it a very clumbsy app, with terrible small and non-adjustable fixed font size that strains the eye).

**Comment by tajmone** [comment]
Italian translation is now fixed and ready! 😹 

@dbelyaev helped me out with lupdate — I don't have teh full Qt dev package installed (and can't install it due to system conflicts), I have only Qt Linguist, which doesn't ship with lupdate. 

@wereturtle, please remember to run lupdate on the translation files whenever a new release is due — if you remember, we faced the same problem in the past, where I depended on you to run lupdate! Sorry for the unconvenience, but I really can't instal Qt 5 on this machine.

**Comment by dbelyaev** [comment]
@wereturtle 
I agree with @tajmone on this, `lupdate` on `ts` files should be a part of routines prior release, as not all the translators are also developers and have full Qt SDK with all the utilities installed on their machine.

**Comment by wereturtle** [comment]
Sorry about the `lupdate` trouble.  I always seem to forget something around release time!

**Comment by tajmone** [comment]
> Sorry about the lupdate trouble. I always seem to forget something around release time!

Maybe you could add a shell script to handle similar task in an automated way. Because of the time lapse between one release and the next one, it's easy to forget all the various tasks that need to be fulfilled.
