### ISSUE TITLE
Viewing parsed anchor tags in the HTML previewer

### ISSUE THREAD

**Issue by PrabuSiva** [wereturtle/ghostwriter#30]
Hi,
Using ghostwriter (v1.2.3) with pandoc. I'm having issue with viewing parsed anchor tags in the HTML previewer.
E.g.  
<div markdown="0">
[Foo](#foo) <br>
# Foo
</div>

The link doesn't work in the HTML previewer but works fine when exported to HTML.

**Comment by wereturtle** [comment]
Sorry about that.  The code that allows you to use the Outline HUD to navigate the HTML preview was butting heads with Pandoc.  (I was setting my own IDs for navigation.)  The next release will have my fix.  I just have to make some time to package it.
