### ISSUE TITLE
Add Keyboard Shortcut To Quit And Automatically Save 

### ISSUE THREAD

**Issue by Nightynal** [wereturtle/ghostwriter#301]
Can you add a keyboard shortcut like **Ctrl + Q** or customize one, and it is automatically saved it? It will be very useful in full screen.

Thanks,

**Comment by dbelyaev** [comment]
@Nightynal 
What will happen if you are writing a new document from scratch and push this shortcut? Should it automatically save with random name in working directory and quit or show "Save As" dialog?

**Comment by Nightynal** [comment]
@dbelyaev 
It is better with a "Save As" dialog. But as a new document, I always make a new file .txt the open it with the program. At the moment I quit by typing fast **Alt then F then Q**.

**Comment by abenson** [comment]
Ctrl-Q works here... it prompts to me to save, discard, or cancel.

--
AndrewB
Knowing is Half the Battle.

**Comment by Nightynal** [comment]
@abenson 

Is it something related to my system? Mine is Windows 7. I was trying Ctrl+Q and it did't work.

![ghostwriter](https://user-images.githubusercontent.com/34853625/36231834-1b715830-1212-11e8-801d-f1afc525d7bc.jpg)

**Comment by wereturtle** [comment]
My save shortcut on my Linux machine is `Ctrl+S`.  Perhaps try that one?

I've coded it to where the app uses the standard Qt shortcut, which is typically based on how your underlying OS is configured to set the shortcut.

**Comment by gerroon** [comment]
Hi

The Linux version has Ctrl+ Q but Windows version is missing it, can you please add it?

**Comment by wereturtle** [comment]
After some research, it appears differing shortcuts for Close, Save As, etc. are to be expected across different platforms.  Here it is in the Qt documentation:

![image](https://user-images.githubusercontent.com/10375170/56474614-0285a980-6431-11e9-9d57-039a1cddd95c.png)

I prefer allowing the OS/desktop environment decide rather than hard-coding shortcuts.

**Comment by bjesus** [comment]
Sorry to bump an old issue, but I've just starting using Ghostwriter on my Arch Linux and `Ctrl+Q` doesn't seem to do anything. It's also not presented as a quit shortcut when I look at the File menu. In fact, no shortcut is being shown. Any idea why? I guess I can get used to pressing `Alt+F, Q` to open the menu and then quit but it just feels weird.

**Comment by wereturtle** [comment]
No idea why.  `Ctrl+Q` works OK in Ubuntu.

**Comment by bjesus** [comment]
Just checked again and was able to fix this using `qt5ct` - on the interface tab you can set the keyboard scheme etc. Thank you!
