### ISSUE TITLE
Translation does not include default Qt elements (buttons etc)

### ISSUE THREAD

**Issue by dbelyaev** [wereturtle/ghostwriter#302]
Currently translation implementation includes only strings used in Application interface. But there are still default button labels and other elements that have string literals on their elements.

For example, simple `QDialog` by default will show "Ok" and "Cancel" buttons. If those strings were not redefined during `QDialog` instance initialization, they will be never translated and will always have default English strings.

Here is an example of how it looks now with enabled non English translation:

Theme Dialog:
- Russian language version
![image](https://user-images.githubusercontent.com/6915328/36228697-361ca65e-11d5-11e8-9a9e-2f738ff947f1.png) 
- Japan language version
![image](https://user-images.githubusercontent.com/6915328/36228727-5187dd50-11d5-11e8-9747-25519be0a03c.png)

Select Language Dialog:
- Russian language version
![image](https://user-images.githubusercontent.com/6915328/36228736-59504d10-11d5-11e8-8051-87ca0db11812.png) 
- Japan language version
![image](https://user-images.githubusercontent.com/6915328/36228743-5f979a5c-11d5-11e8-8cbf-9f01576e0321.png)

Qt supplies translation for those default elements. They can be found in `%QTDIR%\translations\qt_[locale].qm`.

In order to get those default elements translated, developer should include `qt_*` translation files and add additional instance of `QTranslator` that will load them into application. Example can be found [here in Qt documentation](http://doc.qt.io/qt-5/internationalization.html) (see section "Enabling Translation").

After implementing this functionality we'll achieve 100% translated UI:

Theme Dialog:
- Russian language version
![image](https://user-images.githubusercontent.com/6915328/36228822-96403172-11d5-11e8-8e32-fe9d633e7c1e.png)
- Japanese language version
![image](https://user-images.githubusercontent.com/6915328/36228827-99e48d8c-11d5-11e8-9333-5a63e5e20d2c.png)

Select Language Dialog:
- Russian language version
![image](https://user-images.githubusercontent.com/6915328/36228852-a653986a-11d5-11e8-8ea1-aa103b4cc87b.png)
- Japan language version
![image](https://user-images.githubusercontent.com/6915328/36228844-a1b7f0c6-11d5-11e8-8291-b70d5b514b8a.png)

**Comment by wereturtle** [comment]
Hi @dbelyaev, I've pushed a fix to the master branch as you've suggested.  Thanks for looking into this!  Please let me know if it's working now, as unfortunately on my Linux machine the default button text still isn't being translated when I switch locales.  I suspect the `qt_*` translation files are missing from my system.

**Comment by dbelyaev** [comment]
Hello, @wereturtle 

I did a check on my Ubuntu machine and it looks like: `QString defaultLocale = QLocale::system().name();` will return **en_US'' on my machine. It will contribute to search for ''qt_en_US.qm** file while there is only **qt_en.qm** existing.

Of course, we could do a truncate:
`defaultLocale.truncate(defaultLocale.lastIndexOf('_')); // e.g. "en"`

But why bother with it, if already have it available via: `appSettings->getLocale()`? :)

I added a small PR to fix this problem.

**Comment by dbelyaev** [comment]
I am also thinking about Windows installer. I am sure it comes pre-built with dll libraries and languages, so here we should include "qt_*.qm" for existing translations into installer and prepare code for it as in current version it will try to search for "qt_*.qm" only in library path.

I will test it on my Windows machine tomorrow.
