### ISSUE TITLE
Print Preview forgets page settings, Issue still existing although closed

### ISSUE THREAD

**Issue by phiL0co** [wereturtle/ghostwriter#306]
Hallo!

The issue [#1](https://github.com/wereturtle/ghostwriter/issues/1) still exists.
I'm using ghostwriter 1.5.0-2 from the AUR on Arch Linux and the page settings in the print preview still default to letter when I leave the settings screen.
The issue was closed in 2015, seems like the bug is still existing (or again??).

THX a lot in advance.

If you need any further information, let me know!

Best regards 

phiL0co

**Comment by wereturtle** [comment]
Is this happening for the HTML preview or for the plain text/markup?  (If for the HTML preview, I won't be fixing it because the next release is getting rid of the print preview for that.  Later this year I'll be porting away from QtWebKit to QtWebEngine, which does not presently have a print capability.  Hence why I will be abandoning the feature.)

**Comment by phiL0co** [comment]
It's happening for the HTML preview. If it also happens for plain text, I'd have to check because I never use it. But I'm not on a Linux machine at the moment. In the windows version it works fine.

> I won't be fixing it because the next release is getting rid of the print preview for that.  Later this year I'll be porting away from QtWebKit to QtWebEngine, which does not presently have a print capability

So in the future it won't be possible to print HTML output any longer?? 
That was one of the outstanding features of Ghostwriter. That would really be unfortunate. :-(

**Comment by wereturtle** [comment]
Unfortunately, yes.  However, I think the Qt devs are (slowly) working on bringing print support back to the new Chromium-based engine (QtWebEngine).  Sadly, QtWebEngine just isn't as flexible and feature-rich as the old and trusty QtWebKit.  But, it is the future.
