### ISSUE TITLE
Pandoc preview/export error

### ISSUE THREAD

**Issue by zoof** [wereturtle/ghostwriter#307]
There seems to be a problem with the integration of `ghostwriter` with the current version of `pandoc`.   If I switch the previewer window to `pandoc`, I get:

```
Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.
```

I assume it is just a matter of changing the call to `pandoc`.

**Comment by suhr** [comment]
See https://github.com/wereturtle/ghostwriter/issues/260.
