### ISSUE TITLE
Selected CSS not inserted into Export

### ISSUE THREAD

**Issue by daveskidmore** [wereturtle/ghostwriter#308]
It's very frustrating that I can style the preview output, but that the actual exported HTML doesn't include the applied style.  The selected CSS from the HTML Preview window should be inserted into a `<style>` tag in the HTML `<head>`; not a file reference to the source, but the full CSS, so that the exported HTML looks like the preview window output, regardless of load location.

**Comment by Lrochefort** [comment]
+1000 on that matter!

**Comment by stockphrase** [comment]
Pandoc can make "standalone" html exports (--standalone flag) that includes all the styling. This seems like a pretty simple enhancement.

**Comment by merlinuwe** [comment]
It seems that this is a bug.

**Comment by tonghuix** [comment]
A big bug!!!

**Comment by TomSaw** [comment]
Confirm... and it's still not fixed.

**Comment by wahyusa** [comment]
Same...
But, if you are technical people you can just download github.css files provide by [@sindresorhus](https://github.com/sindresorhus/github-markdown-css) or simple css by [@tuzz](https://gist.github.com/tuzz/3331384) it will replace our simple HTML tag in to github style

**Comment by wereturtle** [comment]
Closing as this feature is OBE due to being replaced with an adaptive CSS preview.
