### ISSUE TITLE
Add a parameter to configure line height in editor

### ISSUE THREAD

**Issue by glenux** [wereturtle/ghostwriter#316]
Depending on the font chosen for the editor, the line height might be insufficient or too wide.

It would be fonderful to have a setting to set it to a predefined value (100%, 150%, 200%) or to accept user input.

:)

**Comment by wereturtle** [comment]
Sadly, I'm afraid it isn't technically feasible to do this.  (The QPlainTextEdit class being used does not support this, and switching to QTextEdit will slow the application down big time.)
