### ISSUE TITLE
Make font definition a part of themes

### ISSUE THREAD

**Issue by glenux** [wereturtle/ghostwriter#317]
*It would be wonderful to make font parameter a part of theme definition*

Let me explain : i use ghostwriter for two things: writing code documentation (or computer science courses) and writing novels. 

When writing novels, I prefer to use Arial / Helvetica fonts that are comfortable for reading, plus an inspiring theme. When writing documentation, I use monospace fonts (because of the code) with a sober theme instead.

As I already change thes themes depending on the usage, automatically changing the font would be highly appreciated!

**Comment by suhr** [comment]
I don't like this idea. I often switch between color themes (light and dark), but I don't want to have my font changed.

**Comment by quicknquiet** [comment]
+1
I switch between light and dark themes depending on lighting conditions. And different fonts work better on light/dark background. It's an option, not a must. right? If somebody prefer the same font for different themes he just sets it this way.

**Comment by farvardin** [comment]
sure, the font is appearance, and as such, could be part of the theme (the inclusion of the font could be left optional so people could keep the same font across all their themes)
