### ISSUE TITLE
Word count: 1 plus 1 equal 1

### ISSUE THREAD

**Issue by aleksei-4an** [wereturtle/ghostwriter#318]
Hi.
One small—but important, for those who needs to keep track of the text´s word count sometimes—issue. 

Using precomposed ellipsis: … (ALT-0133) without space after, connecting two words, the ghostwriter counts as 1 word only. Different if you type ... (three individuals dots) without space after it as well.
For example: 
nono…nono (1 word — using: alt+0133)
nono...nono (2 words — using three times: . )

As always. Great app. Keep it up. Cya!

**Comment by aleksei-4an** [comment]
Hm. With the long dash (ALT+0151) too.

nono—nono (=1)

**Comment by miker** [comment]
This seems to make sense, an altcode would be treated as a single character, so in your examples, there is no break between words using an alt code character, so it's 1 long word that just happens to have an alt code in it.
Not sure how the devs would fix this without adding edge case exceptions for any alt code that should technically separate a word. Unless any alt code character should be considered a separator and not a character? 

My 2 cents
