### ISSUE TITLE
Can't compile on fedora

### ISSUE THREAD

**Issue by ggsalas** [wereturtle/ghostwriter#32]
Hi, I would like to compile on fedora 23 but I receive error on "qmake". I have installed all qt packages that I found but allways get error.

There is a compiled RPM to install?
How I can install qmake on fedora 23?

**Comment by wereturtle** [comment]
Try:  `yum install qt-devel qt-config`

**Comment by ggsalas** [comment]
Hi @wereturtle

Have same problem: "bash: qmake: didn't find the order"

**Comment by wereturtle** [comment]
Ah, it might not be adding it to your PATH automatically.  Try:

`export qmake=/usr/bin/qmake-qt4`

(Or it could be qt5 at the end if you're using Qt 5.)

If that still doesn't work, you might want to ask over at http://fedoraforum.org or http://ask.fedoraproject.org, as I'm afraid I don't have Fedora installed to help you out more directly.

Also, as a heads up, you'll need the Qt package that includes WebKit (named libqtwebkit4 or libqt5webkit5 on Ubuntu).  There may be another package you need as well, but I can't remember off the top of my head.  Don't worry, the linker will complain with exactly what it wants if anything else is missing.
