### ISSUE TITLE
Missing DLL (libxslt-1.dll) in 1.6.0 Windows installer

### ISSUE THREAD

**Issue by Erkhyan** [wereturtle/ghostwriter#322]
I just upgraded from 1.5.0 to 1.6.0 on Windows 7, and now Ghostwriter refuses to start. The error message says libxslt-1.dll is missing.

I have also downloaded and tried the Portable version, and ran into the same issue.

**Comment by wereturtle** [comment]
Fixed it now.  Try again.  Sorry about the mess!
