### ISSUE TITLE
Thanks for ghostwriter!

### ISSUE THREAD

**Issue by sbrl** [wereturtle/ghostwriter#323]
This isn't an issue, but I thought I'd let you know how useful ghostwriter has been in writing for my blog as a CS student. I blogged about _ghostwriter_, comparing it to 2 other markdown editors (hint: it comes out on top!) on my blog, and thought you'd like to know :-)

Link: https://starbeamrainbowlabs.com/blog/article.php?article=posts/292-Markdown-Editors-Compared.html

**Comment by suhr** [comment]
You're welcome.

PS: thing white text is hard to read on this background. Improve the contrast and consider other changes for text (bigger font, shorter line width, larger line height, different typeface and so on). This book may be helpful: https://practicaltypography.com/

**Comment by sbrl** [comment]
@suhr Yeah, I've heard about that issue. I'm looking into options to rectify it :-) That website looks interesting though - I'll give it a read!

@wereturtle :smiley_cat:
