### ISSUE TITLE
Menubar displaces text in fullscreen

### ISSUE THREAD

**Issue by caligari87** [wereturtle/ghostwriter#324]
Not sure if this should be considered a feature request or a bug, but it's annoying either way.

When I have Ghostwriter in full-screen mode and the menubar is hidden, hovering to show the menu displaces the document text in a rather distracting manner.

![ghostwriter menubar bug](https://user-images.githubusercontent.com/6425795/38786830-a01ea552-40e7-11e8-84a5-1b9ff46af238.gif)

As-is I think there's sufficient padding at the top of the document area to avoid displacing or overlaying any text. Leveraging this, the menu would only be visually hidden, instead of collapsed.

Running 1.6.2 on Linux Mint 18.

**Comment by suhr** [comment]
This is, but, a regression. Ghostwriter v1.5.0 doesn't have this.

**Comment by wereturtle** [comment]
Feature, not bug, I'm afraid.  I changed it on purpose.  The old way I was using to make the menu bar disappear was a bit risky, especially for HiDPI displays.  It used black voodoo magic with QGraphicsEffect.  The new way is simpler and carries less risk of breaking/not working on different Qt versions/systems.  (It's now just setting the menu bar height to zero to hide it.)  I can't remove the menu bar completely, as that will remove shortcuts to the menus and actions as well.

I know it's not ideal, but to be fair, some other editors displace the text when hiding the menu bar, such as Sublime Text.  For the menu bar, I'll try playing around with setting the top margin height of the text editor to be bigger when the menu bar is hidden, to negate the displacement.  Maybe that will work?  I can't guarantee that it will, though.

**Comment by caligari87** [comment]
I don't know much about Qt, but is it not possible to use `SetVisible()` in this case?

**Comment by wereturtle** [comment]
> I don't know much about Qt, but is it not possible to use menubar->SetVisible(false) (or something to that effect) in this case? Just curious.

Oh, that works, all right.  But it removes the menu bar shortcuts.
