### ISSUE TITLE
Ghostwriter crashing on start Windows 10

### ISSUE THREAD

**Issue by futurerob** [wereturtle/ghostwriter#326]
Even after uninstalling and reinstalling ghostwriter fails at open.  Any ideas?  

Log Name:      Application
Source:        Windows Error Reporting
Date:          4/16/2018 10:02:04 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-7VG281G
Description:
Fault bucket 1305613746628990847, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: ghostwriter.exe
P2: 0.0.0.0
P3: 5ad3d8fd
P4: ghostwriter.exe
P5: 0.0.0.0
P6: 5ad3d8fd
P7: c0000005
P8: 0002f714
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER966E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9825.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9833.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9863.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ghostwriter.exe_a3d6c968ebc4100f382ad59c88cac5f166676a_b0cd6170_2c8ba255

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3b7b7294-fdb8-4c19-869f-40a89566a5a8
Report Status: 268435456
Hashed bucket: 6896f995cfe156ab721e78c8fdb0177f
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-17T05:02:04.793322500Z" />
    <EventRecordID>16726</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-7VG281G</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1305613746628990847</Data>
    <Data>1</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>ghostwriter.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5ad3d8fd</Data>
    <Data>ghostwriter.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5ad3d8fd</Data>
    <Data>c0000005</Data>
    <Data>0002f714</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER966E.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9825.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9833.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9863.tmp.txt</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ghostwriter.exe_a3d6c968ebc4100f382ad59c88cac5f166676a_b0cd6170_2c8ba255</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>3b7b7294-fdb8-4c19-869f-40a89566a5a8</Data>
    <Data>268435456</Data>
    <Data>6896f995cfe156ab721e78c8fdb0177f</Data>
  </EventData>
</Event>

**Comment by wereturtle** [comment]
Sorry, I only have Windows 7, and thus cannot replicate this error.  Just to confirm, you are on version 1.6.2, correct?  If you open the Command prompt and execute ghostwriter from the command line, does it print anything to the console before crashing?  Also, are there any other dialog windows popping up with other errors?  Finally, does the portable version do the same?

Is anyone else out there who is using Windows 10 seeing ghostwriter crash like this?

**Comment by jeff9315** [comment]
I have Win 10 and do NOT have this issue.

**Comment by futurerob** [comment]
Yes, I was trying to run 1.6.2.  Command prompt does not print anything to the console before crashing.  The portable version seems to works fine.

**Comment by wereturtle** [comment]
I wonder if it's a permissions issue running under C:\Program Files ?  Does the issue persist if you run as administrator?

Well, at least you have a workaround with the portable version in the meantime.  Whew!

**Comment by Obero** [comment]
Hi, same problem here (Windows 10, v1803, build 17134)
Ghostwriter is crashing immediately at start printing nothing on my terminal.

More info: this problem appeared after an OS update, I don't know if it is bad luck or a clue. Before this update, everything was working fine.

Portable version is still launching and okay too.

**Comment by craigim** [comment]
Same problem here (Windows 7, SP1), Ghostview 1.6.2, installed version.

What I've found is that if I open Ghostview, immediately select "new", and then try to edit the new file, it crashes. If, however, I open an *existing* file, edit it, undo the edit, and *then* select "new", everything works just fine.

**Comment by jj-zhu** [comment]
I'm on Windows 10 and can't get it to launch. I replaced the files with the portable version and was able to launch it once. Then the same behavior happened again.

**Comment by ChickenFur** [comment]
Same problem here it won't launch, tried uninstall and reinstall.  Windows 10.  It was working fine then just stopped working.  Maybe a windows update?

**Comment by dinogoja** [comment]
I have the same problem in Win10. Not starting at all. Portable version works fine.

**Comment by wereturtle** [comment]
Hi all,

Please try out the new 1.7.0 release of *ghostwriter*.  I don't expect it will necessarily solve this problem.  However, some of the reports you have left me sound suspiciously like a bug in Qt 5.10 that caused a crash on opening a new file after another one was already open (see release notes;  I had to work around the issue by setting the editor's cursor position to zero before clearing the editor contents to make a "new" file).  I am curious if this will at least fix even a few people's problems.  (I'd love it if it fixed *everyone's* problems, but dare to dream....)

Please provide your feedback here.

**Comment by craigim** [comment]
That fixed my issue. Thanks!
