### ISSUE TITLE
Print HTML preview - no longer possible?

### ISSUE THREAD

**Issue by ghost** [wereturtle/ghostwriter#327]
I appreciated being able to print the HTML preview in versions prior to 1.6.2. With the dual pane preview, is this no longer possible? Am I missing something? Thanks!

**Comment by wereturtle** [comment]
Please read the release notes.  The feature needs to be reworked for the upcoming port to QtWebengine.  I was having difficulty trying to put in a context menu option for right clicking on the preview with QtWebkit.  I'll try it again when I port.

In contrast to what I last wrote on the release notes, it does appear that recent versions of QtWebengine now support printing.  It originally didn't.  So there's hope for the future.

**Comment by rvaliant** [comment]
Thanks for the response. Export to HTML works just fine for printing in the meantime. I'm very thankful your work - I was a big fan of Uberwriter, too.
