### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by mulander** [wereturtle/ghostwriter#328]
Please consider adding a source release tarball, the automatically generated github source downloads are not guaranteed to be immutable and are an issue for systems packaging ghostwriter from source (like OpenBSD).

More information on the issue caused by automatic downloads:
https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

I noticed you already do separate uploads for the portable zip and the installer, doing the same for the source repo for releases instead of relying on github automatic downloads would be amazing.

**Comment by RealOrangeOne** [comment]
Release files are also not guaranteed to be immutable, they can be changed at will. Using the GitHub-provided ones should work fine, as theyre linked to a tag, just as the related files are? The only real way of getting something immutable is to pin down the version by commit, but even then the commit could vanish.
