### ISSUE TITLE
Pandoc export does not work for file/directory with spaces

### ISSUE THREAD

**Issue by zhidayat** [wereturtle/ghostwriter#33]
If the directory of the markdown file or the file name contains space, exporting the document using pandoc failed. Message:
Export failed.
pandoc: <endoffilename>.ext: openFile: does not exist
(No such file or directory)

Info:
Windows 7 64bit
ghostwriter 1.2.4
pandoc 1.15.1.1

**Comment by wereturtle** [comment]
Thank you for reporting this bug.  Version 1.2.5 now has a fix for this.
