### ISSUE TITLE
Is it possible to scale the font in the html preview window

### ISSUE THREAD

**Issue by asmwarrior** [wereturtle/ghostwriter#330]
I see that I can zoom-in or zoom-out the fonts in the edit control, but is it possible to zoom in the html preview window? Thanks

BTW: In CuteMarkEd(another markdown editor), I can use the CTRL+ScrollUp/Down to do the zoom of the html preview window.

**Comment by miker** [comment]
That would be a nice feature to be able to zoom just the HTML preview.

**Comment by wereturtle** [comment]
Version 2 will now allow selecting the font size for the preview.  :)
