### ISSUE TITLE
custom code blocks render support, such as sequence and flowchart diagram

### ISSUE THREAD

**Issue by asmwarrior** [wereturtle/ghostwriter#331]
Hi, can ghostwriter adding some feature to support customized code blocks render, some thing like: [markdown-preview-enhanced/diagrams.md at master · shd101wyy/markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/diagrams.md) or [Draw Diagrams With Markdown](http://support.typora.io/Draw-Diagrams-With-Markdown/), so that if people can write flowchart diagram using those code:

```
​```flow
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
​```
```

**Comment by asmwarrior** [comment]
Ok, it looks like this need a "filter", just like this one: [pandoc-mermaid-filter - npm](https://www.npmjs.com/package/pandoc-mermaid-filter). We need to change the command line option passed to the pandoc, any ideas how to do this? Thanks.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
