### ISSUE TITLE
Line wrapping on an indented task list doesn't inherit indent

### ISSUE THREAD

**Issue by tutchmedia** [wereturtle/ghostwriter#332]
When adding text to an indented task item(3/4 indents) and when the text wraps onto a new line, the text doesn't inherit the indent from the first line. Instead it seems to start from the left hand margin.

**Comment by wereturtle** [comment]
This is a limitation of using Qt's QPlainTextEdit for a plain text editor.  Unfortunately, switching to QTextEdit (the rich text editor) has performance limitations on large files with the live spellchecker and setting themes, and also has a limitation where setting line wrap indentation messes with the undo/redo stack.
