### ISSUE TITLE
Menu appears and disappears when hidden for fullscreen mode while writing letters using AltGr

### ISSUE THREAD

**Issue by mrowa** [wereturtle/ghostwriter#333]
OS: Windows 10 x64
Version: 1.6.2

AltGr (right Alt) is often used to write diacritics (like in Polish, Macedonian, Dutch, etc.). Alt (left Alt) is commonly used as a shortcut-key modifier and it toggles visibility of menu in fullscreen.

When menu is hidden in preferences (for fullscreen), it's still possible to show it (and use shortcuts from it) by using AltGr, and while writing diacritics with AltGr it shows and hides the menu all the time. This makes the fullscreen mode with hidden menu unusable for writing in some languages. There is a good list of languages and characters on [wikipedia about it](https://en.wikipedia.org/wiki/AltGr_key).

I really like ghostwriter and if there would be a possibility to fix that I would be very glad :)

I may also help with testing in any case.

**Comment by cigno5** [comment]
Hi I have the same issue but on Ubuntu 18.04/Gnome Shell using the Alt key.
I use it to switch between windows and when Ghostwriter is in full screen the menu appear and disappear and sometimes the focus remains stuck on the menu, and thus I'm not able to write unless I click on the text (or I press again Alt key)

**Comment by wereturtle** [comment]
Hi @mrowa,

I just want to confirm, would the fix for this really to be to have ghostwriter only show the hidden menu bar only when the left Alt key is pressed, rather than either when the left or right Alt key is pressed?  In other words, that the right Alt key is reserved for AltGr functionality?

**Comment by wereturtle** [comment]
@mrowa 

The plot thickens.  Running in Linux with Qt 5.11.0, and the right Alt key is detected as AltGr when using a Hungarian keyboard layout.  Hence, the issue does not appear there.

However, on Windows, it does.  As I suspect this is a Qt issue with Windows, I have sumbitted [QTBUG-69317](https://bugreports.qt.io/browse/QTBUG-69317).  You can follow that to see what is up.  Hopefully a Qt dev gets back with us.

**Comment by mrowa** [comment]
@wereturtle menu bar showing only when the left Alt key is pressed is exactly what I meant. Thank you very much for digging into that, much appreciated :)
