### ISSUE TITLE
WYSIWYG or something similar?

### ISSUE THREAD

**Issue by jsuarez1** [wereturtle/ghostwriter#334]
Fist, excuse me if you plans for your app are to keep it "geeky". If so, surely youll want to forget this post. But if you want a broader public, please consider adding a WYSIWYG option like [Uncolored](https://raw.githubusercontent.com/n457/Uncolored/master/project/docs/assets/uncolored-large-screenshot-win.png), or at least "pseudo" WYSIWYG, like [Abricotine](https://github.com/brrd/Abricotine).

Markdown is ideal for elaborated notes, drafts and brief documents that don't need as many features like lot of pages and references, footnotes, comments, wrapping texts, etc. Besides you can edit them with any thing thats able to write text, even a simple SMS application 😄. But being forced to type code, even if easy, doesnt help to popularize MD; for this, editors should be as easy to use that common users, accustomed to work in a totally visual way in text processors, mail composers, etc, could use them without the need to "study" before. Think if your aunt would feel comfortable taking notes of her vacations having to remember "**", "#", "__", "  ", "()[]" etc... I think most users would like an user friendly interface. All this, in case you are interested in making GW for as many people as possible. Obvously, the program is yours and you are entitled to want a more techy public, of course.

But if you are open to consider my point of view, please take a look to [telegra.ph](http://telegra.ph/), the online publishing tool by Telegram, or to Uncolored, mentioned before. They cant be easier: no code views, no "occult" stuff behind weird symbols. Just type, select text, and a floating menu appears to provide the tools you need to format your text or insert media files; and in every moment you see what you are doing without the need of two panels that clutter your desktop and confuses you (when I say "you" am obvously referring to the "average Joe").
BTW, those floating menues is something you could implemente even if don't want to add the WYSIWYG option. Having the pertinent tools at your "cursortip" instead having to "travel" to open a pop up menu and then click on whatever option, is a nice improvement for efficience: saves time and avoids distractions.

Im proposing all this WYSIWYG thing as an option, not as a substitution, of course. The code view must be kept, advanced users prefer it, and once you are familiar with the syntax it's some times faster, and you know exactly "what's happening" with your text. But in general, using the mouse to select text, click a button, and there you have your format or your link inserted is faster.

I'm not very experienced in Github's "etiquette", but I hope you don't feel offended because of constructive criticism (that's what I want to think this is. I'm using your software since some days ago, and I'm liking it, but it would be also nice to "liberate" relatives and friends from proprietary software; for their own sake but also to be coherent with that usual complaint in the Linux world: *With 2 - 3% of the market share we'll never have good device support, no good job opportunities for Linux experts beside the servers and investigation fields, and never ever Autocad/Photoshop/whatever for Linux*.
All that is true, but how to liberate or beloved ones and also increasing the number of Linux/BSD/whatever if they find things on FLOSS more complex than necesary? It's understandable that they end turning back to One Note, G. Keep, etc; not because they think those are better, but give them less headaches.

BTW, I love your comment in [the projetc's site](https://wereturtle.github.io/ghostwriter/) about giving something back to the community. I can't give anything to community since my profession has nothing to do with computers nor know a word about programing, but can, and I do, give some money for projects I like. so, as a frequent FLOSS donor I'd like to suggest you to add dome donation button on Ghostwriter's site, preferably accepting Liberapay or Faircoin.

Cheers. and forgive the lenght of this post. But I think it's better to write a long and explaining post than a brief one, and then other 2 more to explain what wasn't well explained in the first one. 😬

**Comment by suhr** [comment]
The whole point of Markdown is to *not* be WYSIWYG. The markup is lightweight enough to read it raw, and you're not artificially separated from it.

> Think if your aunt would feel comfortable taking notes of her vacations having to remember "**", "#", "__", " ", "()[]" etc...

The editor provides not only menu entries and hotkeys to enter the markup, it also provides you a visual feedback (titles are large, bold text is bold). So you don't even have to remember anything.

> I'm liking it, but it would be also nice to "liberate" relatives and friends from proprietary software

If you want to move people from MS Word to markdown, it is not going to work. Even with WYSIWYG.

**Comment by wereturtle** [comment]
Since I am occasionally asked this question over and over, I decided to make [a Wiki page](https://github.com/wereturtle/ghostwriter/wiki/Why-Not-WYSIWYG%3F) to answer it.  I hope this more than answers your question.

**Comment by wereturtle** [comment]
By the way, the vast majority of Markdown editors have been for MacOS / OSX and even iOS.  This isn't just a geeky Linux trend.  Linux is just now catching up to Mac with editor options.  While many of the popular (and some very expensive) editors for Mac have a WYSIWYG mode, they primarily advertise the syntax-highlighting mode in their website screenshots.  Ulysses III and iA Writer come to mind.  For whatever reason, people are paying top dollar on Mac to write with `#`, `*`, and `>` symbols.  There must be enough geeky writers out there for these apps to be turning a profit.
