### ISSUE TITLE
Feature request: hyperlinks

### ISSUE THREAD

**Issue by glauber-experian** [wereturtle/ghostwriter#335]
Would you consider adding support for inserting hyperlinks `(<a href...>)` using a dialog?

Thanks,

glauber

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

Also, markdown already has hyperlinks with `[this syntax](http://yourlinkhere.com)`.
