### ISSUE TITLE
Bad position of hud outline

### ISSUE THREAD

**Issue by nick87720z** [wereturtle/ghostwriter#336]
For me HUD outline looks like positioned between pixels. I tried to make two solutions in HudWindow.cpp, paint event handler: 1 - Setting Pen to "cosmetic" type (what it really does is keeping same visible line width on different scales), and 2 - modifying pixmap.drawRect calls by adjusting coordinates by 0.5. However, nothing worked.

On screenshots below it is visible, that line side parts are transparent and on two pixels, while rounded part is much sharper. I noticed, that paint event handler operates with pixel ratio (i thought that qt should handle this... could not find, where corner position is affected really).
![ghostwriter-hud-nocomp](https://user-images.githubusercontent.com/3896190/40058541-e0d3eb1c-586a-11e8-9f41-1d80bc20bef8.png)
![ghostwriter-hud-comp](https://user-images.githubusercontent.com/3896190/40058549-e847157c-586a-11e8-9b09-ae1f345aae64.png)

**Comment by wereturtle** [comment]
I think what you are seeing on the corners is antialiasing.  The antialiasing makes the corners look a bit thinner.  I don't think that's a defect.

The pixel ratio is for HiDPI scaling.  Unfortunately, Qt makes the programmer handle DPI scaling on the application side.

**Comment by nick87720z** [comment]
Hm. I looked same image zoomed - it seems, it is not exactly betweem pixels. Somewhere between edge and middle. Obviously, correction would be not =0.5.
