### ISSUE TITLE
Feature Request: Start at the center

### ISSUE THREAD

**Issue by chaseaucoin** [wereturtle/ghostwriter#337]
I absolutely LOVE this editor. I like that once you get to the middle of the screen it keeps the text there to make it easy to focus. I'd love an option to start like that from the beginning of writing instead of having to get a few paragraphs in that way I can keep my eyes centered on the screen the whole time.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

Also, the editor that comes with Qt doesn't allow you to scroll into whitespace, so it might not be possible without much pain and suffering to add the padding to the top of the editor to center the text vertically when at the start of the document.
