### ISSUE TITLE
Feature: flag to start ghostwriter in preview mode only

### ISSUE THREAD

**Issue by phil00000001** [wereturtle/ghostwriter#338]
dear Wereturtle 

Big thanks for finally giving to us a beautiful and fast markdown editor on Linux (at least)! 
REALLY!

Here is the feature request:
- allow us to start ghostwriter as a simple Markdown viewer : no editor view and allow for window/fullscreen.

many thanks

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
