### ISSUE TITLE
Add "Browse current directory" option to "File" menu

### ISSUE THREAD

**Issue by kocielnik** [wereturtle/ghostwriter#339]
TLDR: "File" -> "Browse current directory"

So many times every day I find myself lacking space on my desktop and in my mind to keep the file manager window open for adding and managing new graphics for the articles I write.

What would you think about an option in the "File" menu to quickly open the document directory in the default file manager? This would allow closing the file manager right after the action to save mental and desktop space.

**Comment by wereturtle** [comment]
Try going to Edit -> Insert Image in the menu bar.  It will open a file browser to the currently open document's directory location, so that you can select images that might be there.  It will also insert the image with a relative path.
