### ISSUE TITLE
HTML Preview in Separate Window 

### ISSUE THREAD

**Issue by Spacetchi** [wereturtle/ghostwriter#340]
I suppose this is a feature request, though the feature has existed before. Nevertheless, I understand if it gets closed. 

I just really liked how the HTML preview used to be in a separate window. I do see the convenience of the new pane style in 1.6. Will the separate window style ever make a comeback as an option?

**Comment by wereturtle** [comment]
Yeah, sorry.  I decided to go with what is more standard.
