### ISSUE TITLE
Get it into Linux distro's

### ISSUE THREAD

**Issue by rugk** [wereturtle/ghostwriter#346]
It would be nice to have it as an official package into many Linux distro's, so people can easily get & install it.

**Comment by abenson** [comment]
That's more a function of the distro than of the package.

**Comment by rugk** [comment]
Sorry, but what?

**Comment by devhell** [comment]
FWIW, we have it packaged for NixOS [NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/ghostwriter/default.nix) :)

**Comment by abenson** [comment]
I maintain it for Void, as well.

**Comment by sbrl** [comment]
For Debian* distributions, I'd recommend setting up a PPA (_personal package archive_). That way you can keep the package up-to-date - as many Debian-based distributions don't allow feature updaates after release.

**Comment by rugk** [comment]
I think only Ubuntu sopprts PPAs, not Debian itself.

Anyway there are more distros: What about Fedora e.g.? There you get fast "feature updates" in any case…

**Comment by sbrl** [comment]
@rugk You can still add additional `sources.list` entries on Debian itself :smiley_cat: 

Indeed. I think Arch* already has an AUR entry (Yep! [Found it](https://aur.archlinux.org/packages/ghostwriter/)), but Fedora and others would be good too.

**Comment by wereturtle** [comment]
I'm afraid I don't have time to become a maintainer for all the various Linux distros.  The bar can be pretty high, too, to become one.  Someone has to mentor you for a while before they trust you to upload things on your own, etc.  They rightfully want to make sure you're not a psychopath.

I'd rather spend the time working on development.  It is best that people volunteer to be a maintainer for the distro(s) they care about.  Perhaps you should consider it?  It would be a good learning experience.

I do believe someone has recently volunteered to package ghostwriter for Debian.  Last I checked, he's waiting for a sponsor for his package.  Hopefully we'll start seeing current ghostwriter versions rolling along on Sid and testing soon.  In the meantime, you can follow progress [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894260).

**Comment by rugk** [comment]
Of course, I did not say _you_ should maintain these packages. So, you can tag this as "help wanted", of course, but you have to leave it open, otherwise others won't find this issue.

**Comment by finn0** [comment]
@wereturtle Since `ghostwriter` is now available for [Debian](https://tracker.debian.org/pkg/ghostwriter), isn't it a good idea to mention this in [Linux  installation](https://github.com/wereturtle/ghostwriter#linux) section of `README.md`?

If you're agree, I can make a pull request for this.

**Comment by suhr** [comment]
I would link https://repology.org/project/ghostwriter/versions instead.

**Comment by finn0** [comment]
@suhr Indeed, that would be good idea; but like Fedora, ArchLinux, Debian is a popular GNU/Linux distribution and mentioning it would take hardly 2-3 line in README.md file.
