### ISSUE TITLE
HTML Preview themes?

### ISSUE THREAD

**Issue by sbrl** [wereturtle/ghostwriter#347]
Hello,

I was wondering if it's possible to theme the HTML preview? I'm using the dark theme, but the HTML preview doesn't seem to follow suit - making it rather harsh on the eyes.

**Comment by wereturtle** [comment]
In the menu bar, go to Settings -> Style Sheets.  Then select the "+" button to add any CSS stylesheet on your machine, and click OK.

![image](https://user-images.githubusercontent.com/10375170/41442042-40be0af8-6fea-11e8-87f0-82b7f1d4af4c.png)

**Comment by sbrl** [comment]
Now that I know how to use it, I thought you'd like to see my dark version of the default GitHub theme that's here in this repo @wereturtle. Link: [github-dark](https://gist.github.com/sbrl/3de32f86be4bdb6dde7729bc42df16a0)

**Comment by wereturtle** [comment]
Looks really nice!  I take it you'd be interested in it being added to the default available style sheets in the next release?  If so, I can arrange for that.  :smile:

**Comment by sbrl** [comment]
Indeed! I could send a PR, if you like :D

**Comment by sbrl** [comment]
@wereturtle Opened #349
