### ISSUE TITLE
Is it possible to not start Ghostwriter opening the last edited file?

### ISSUE THREAD

**Issue by octygen** [wereturtle/ghostwriter#348]
I write some pretty intense journal entries that I would not want to accidentally pop up when I'm using ghostwriter to take notes in a meeting on a big screen. Is there some sort of parameter I am missing on startup or a setting to start ghostwriter blank?

**Comment by wereturtle** [comment]
You can uncheck the "Remember file history" option.  However, that will also have the side effect of not remembering any recently opened files at all (in the File->Open Recent menu).  The next version will remember if the last opened file was just a "new" file, as part of coding the hot exit feature.
