### ISSUE TITLE
Position of HTML preview window and separate preview window

### ISSUE THREAD

**Issue by boschkundendienst** [wereturtle/ghostwriter#350]
Hi,

I know that you are currently porting everything to QT5 but I want to remember that having an external preview window is really helpful. In my case I have 3 monitors and I place the preview window sometimes on a single screen (left or right monitor) and sometimes besides the editor window. This totally depends on my current workflow.

If I already have a workflow where I need 2 monitors but need to write documentation using ghostwriter I place edit and preview side-by-side on a single monitor.
If I just configure a new Linux system and document the commands I usually place the editor on one monitor, the preview on the other and the SSH shell of the server on the 3rd one.

In the current version of ghostwriter the preview window is always right-of the editor but my personal preference was to have it left-of the editor which is currently no longer possible.

Don't understand me wrong, I !!! love !!! ghostwriter but I hope you can re-implement a separate window for the preview, at least make the position changeable from left to right and vice versa.

Thank you for this great piece of software.

Regards

Peter

**Comment by wereturtle** [comment]
Sorry, I probably won't be reverting back to the separate window solution.  I decided to just stick with what is standard among Markdown editors with separate previews.
