### ISSUE TITLE
Single line break preview differs from GitHub

### ISSUE THREAD

**Issue by estan** [wereturtle/ghostwriter#354]
@wereturtle Many thanks for this great tool!

The behavior of Ghostwriter's preview in Pandoc GitHub-flavored Markdown mode with regards to single line breaks in the Markdown source does not match that of GitHub. When entering a single line break in the source Markdown, a line break is shown in the preview. On GitHub, you need two line breaks to get a line break in the output.

**Ghostwriter - Line break in the output**

![ghostwriter](https://user-images.githubusercontent.com/86675/42154116-3e00266c-7de5-11e8-9f2d-f33c01792e9e.png)

**GitHub - No line break in the output**

![github_edit](https://user-images.githubusercontent.com/86675/42154158-555cbac8-7de5-11e8-986a-bb4b546f4c85.png)
![github_preview](https://user-images.githubusercontent.com/86675/42154174-598415e2-7de5-11e8-88e2-7a322aa47e17.png)

This makes it cumbersome to work with Markdown files where the policy is e.g. 79 columns in the source file. Pandoc seems to have an option to disable this (`-f markdown_github-hard_line_breaks`). I suggest running with that by default, and make it an option (sorry it's turning out to be a feature request-ish!) to insert hard line breaks in the output.

**Operating System:** Kubuntu Linux 18.04
**Desktop Environment:** KDE
**Steps to Reproduce:** Insert single mid-line line break in source
**Sample Markdown:**
```md
This is a
line
```

**Comment by estan** [comment]
See also https://github.com/jgm/pandoc/issues/3268

**Comment by pazos** [comment]
@estan: Can't reproduce on linux, Ubuntu 18.04

![sin nombre](https://user-images.githubusercontent.com/975883/42178275-06d03c7c-7e30-11e8-9a64-dfa7ab9c3242.png)

**Comment by pazos** [comment]
Ah, I understand now, you are using the printer preview ,but that just print your markdown file without conversion. If you want to see how your markdown will look as html use (Ctrl + M) to enable previsualization in html.

**Comment by wereturtle** [comment]
Hi @estan,

> See also jgm/pandoc#3268

It sounds like you answered your own question.  ghostwriter is just showing what Pandoc produced.  While supporting the command line parameter referenced in the above Pandoc issue would result in the desired behavior, I'd prefer to keep Pandoc options simple for now.

**Comment by estan** [comment]
@wereturtle Okay, hm. But if an option complicates Ghostwriter too much, wouldn't it make sense to use that option by default, so that the behavior is the same as for `README.md` and wiki pages on GitHub?

I think that most people when they pick "GitHub flavored" in the Preview Options, they will expect the formatting to match that of GitHub README.md / wiki pages, not that of GitHub comment fields?

**Comment by wereturtle** [comment]
@estan 

FYI, it looks like Pandoc 2.0 is disabling hard line breaks (`-f markdown_github-hard_line_breaks`) by default.  However, for the sake of older versions of Pandoc, I'll be sure to have ghostwriter force disabling the hard line breaks.  I just thought I'd mention this so you could perhaps install a newer Pandoc version in the meantime.

**Comment by estan** [comment]
@wereturtle Aha. I'm using pandoc 1.19.2.4 which is the one that comes with Ubuntu 18.04. Not sure why they're using such an old version (compatibility reasons I guess).

**Comment by estan** [comment]
Thanks!

**Comment by estan** [comment]
(And I can confirm that running Ghostwriter with `PATH="/path/to/pandoc-2.2.1/bin:$PATH"` in the environment solves the problem, but good to know it'll work out of the box with pandoc 1.x now.)
