### ISSUE TITLE
[Bug] Ghostwriter does not export with Pandoc

### ISSUE THREAD

**Issue by AuroraMartell** [wereturtle/ghostwriter#356]
Running Ghostwriter 6.0 and the latest pandoc release, I can't seem to get a file exported even though both pieces of software appear to be perfectly installed on Windows 7. Has anyone ever run across this?

**Comment by wereturtle** [comment]
Okay, please provide the following details, and I'll see what I can do.

1. If on Windows, is this the portable version or the neatly installed-on-your-system version?
2. What does your PATH environment variable look like?
3. Do you have Pandoc in the same folder as the ghostwriter executable (versus relying on the PATH environment variable)?
4. Are you able to get the live preview working with Pandoc?
5. Did any export file format options even show up for Pandoc?
6. Did ghostwriter provide any error message when you tried to export?

Thanks in advance.

**Comment by AuroraMartell** [comment]
On both Windows and Ubuntu Mate, ghostwriter gives me this error:
Failed to execute command: pandoc -f markdown${SMART_TYPOGRAPHY_ARG} -t odt --standalone -o ${OUTPUT_FILE_PATH}

**Comment by wereturtle** [comment]
@AuroraMartell 

Have you tried ghostwriter v1.6.2?

Also, what version of Pandoc are you using?

**Comment by AuroraMartell** [comment]
I'm using v 1.6.2 and Pandoc 2.2.1 on Windows.

**Comment by wereturtle** [comment]
@AuroraMartell 

Okay, I ran 1.6.2 against Pandoc 2.2.1, and it gave an error message for me, as well.   However, the error message looks awfully familiar to me.  So I tried the new 1.7.0 release of ghostwriter that just came out, and now it's fine.  I must have fixed it already and forgot to add it to my release notes.  Please give ghostwriter 1.7.0 a try, and let me know how it goes.

**Comment by AuroraMartell** [comment]
It works now, (at least on Linux) thanks.
