### ISSUE TITLE
add a logger

### ISSUE THREAD

**Issue by pazos** [wereturtle/ghostwriter#358]
I notice that ghostwriter is almost silent on console. This is great by default but I thinking about adding a basic logger to handle qDebug et al statements.

Maybe add a parser before QApplication constructor to catch valid flags (like -d or --debug). Then set logging categories and remove those arguments from QApplication arguments (to prevent breaking the current implementation for open files)

Thinking about 3 possible "loggers": a verbose logger by default on debug builds, and two loggers for release builds: normal (logs qinfo, qwarning, qcritical and qfatal), and quiet (logs just qcritical and qfatal).

Of course I'm willing to do the job, I've done this previously on qt projects so I can implement it quickly.(Adding statements is other thing, but this can be done later on).

**Comment by wereturtle** [comment]
Thanks for the offer, but I think it's good as is.  I rarely need that level of debugging in a GUI app, unless a new Qt release is out and it's crashing somewhere funny.  But that's what the debugger and breakpoints are for.
