### ISSUE TITLE
OS X High Sierra Build Issues

### ISSUE THREAD

**Issue by taoteg** [wereturtle/ghostwriter#362]
I cloned the repo but I had to install qt with specific flags to get it to build without errors:

```brew install qt@5.5 --with-qtwebkit```

Passed the qmake and make steps fine.
After copying into /Applications and symlinking into /usr/local/bin if called from cli, throws this error:

```
±: ghostwriter
objc[37850]: Class NotificationReceiver is implemented in both /Applications/ghostwriter.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets (0x1010ce8b8) and /usr/local/Cellar/qt@5.5/5.5.1_1/lib/QtWidgets.framework/Versions/5/QtWidgets (0x1082e18b8). One of the two will be used. Which one is undefined.
objc[37850]: Class QCocoaPageLayoutDelegate is implemented in both /Applications/ghostwriter.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x100b8ce98) and /usr/local/Cellar/qt@5.5/5.5.1_1/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x107d9be98). One of the two will be used. Which one is undefined.
objc[37850]: Class QCocoaPrintPanelDelegate is implemented in both /Applications/ghostwriter.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x100b8cee8) and /usr/local/Cellar/qt@5.5/5.5.1_1/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x107d9bee8). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fd7224116e0) is not the object's thread (0x7fd722603e80).
Cannot move to target thread (0x7fd7224116e0)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Available platform plugins are: cocoa, minimal, offscreen.

Reinstalling the application may fix this problem.
[1]    37850 abort      ghostwriter
```

Tried setting the value of the ```QT_PLUGIN_PATH=/usr/local/Cellar/qt@5.5/5.5.1_1/plugins/``` but still no go.

**Comment by pazos** [comment]
@taoteg: 

brew install qt@5.5 does include webkit.

In any case brew doesn't try to link qmake to /usr/local/bin, so you'll need to export /usr/local/Cellar/qt@5.5/5.5.1_1/bin to your PATH. If you are using bash try:

`export PATH=$PATH:/usr/local/Cellar/qt@5.5/5.5.1_1/`



then build the application. (do a clean build by removing the "build/release" folder ). The application should build cleanly, and then invoke the tool macdeployqt. On current master at the end it complains about it cannot find translations. This is normal.

you should be able to open the application (from terminal `open build/release/ghostwriter.app`). If you can open the application this way, then follow to the next step. If not then please do:
```bash
cd build/release/ghostwriter.app/Contents/MacOS
otool -L ghostwriter
```
and attach the output here.

If you are able to open the app with the `open` command from the console, then please remove qt from your PATH and try to run the application from commandline.

The message `is implemented in both...` is annoying but not critical. The critical bug is that qt can't find current platform.
