### ISSUE TITLE
Crash switching theme

### ISSUE THREAD

**Issue by finex** [wereturtle/ghostwriter#363]
Hi, I'm using ghostwriter v1.6.2 (from Archlinux AUR packages).

Changing ghostwriter theme make it crash with the following error:

> libpng warning: iCCP: known incorrect sRGB profile

If you need more details just ask :-)

**Comment by wereturtle** [comment]
Sorry I don't maintain the AUR package, and Qt 5.11 (the latest, bleeding edge Qt) doesn't have this issue changing the theme in Ubuntu/Mint.  Can you try compiling the recent 1.7.0 release, and see if that fixes your issue?  Let me know how it goes.

**Comment by 9Morello** [comment]
I'm having the same issue with Windows 7. Changing the theme with preview turned on instantly crashes the program. It works fine if I change themes with live preview turned off.
