### ISSUE TITLE
Crash on "Alternate row colors"

### ISSUE THREAD

**Issue by cashlionjp** [wereturtle/ghostwriter#364]
Ubuntu Linux

Settings > Preferences > HUD 

Checking "Alternate row colors" crashes the program.

**Comment by wereturtle** [comment]
Which Ubuntu version?  Also, which Qt version?  I can't replicate this on 16.04 with Qt 5.6.

**Comment by cashlionjp** [comment]
I can no longer recreate this after a reboot.

**Comment by wereturtle** [comment]
Good to hear! Thanks!
