### ISSUE TITLE
Windows Maintainers Wanted!  Sign up here!

### ISSUE THREAD

**Issue by wereturtle** [wereturtle/ghostwriter#367]
# Introductory Announcement

I'm sorry to announce that very soon, I will no longer be able to provide new releases of *ghostwriter* for Windows.  This is largely because I do not have Windows 10 and thus find myself increasingly unable to help those having problems that are specific to that version of Windows.  I was hoping to only make this announcement when Windows 7 support was dropped (or when my hard drive which has it installed died--whichever came first).  Alas, it was not meant to be.

If anyone is interested in providing Windows builds of *ghostwriter* and uploading both a portable and installable version for every release, please signal your interest in this thread.

Please note that there is more to maintaining the Windows version than building it.  Answering Windows users' questions, determining if a bug is only happening in Windows and not Linux, and even patching Windows-specific issues are all part of the job.  Please read the following notes to get a feel for some of the challenges you will need to face.

# QtWebEngine

Up until now, I have been using MinGW to build *ghostwriter* under Windows.  By the end of 2018 / early 2019, I will be transitioning from using QtWebkit to using QtWebEngine (Chromium) in the Live Preview.  QtWebEngine will require the Windows maintainer to use MSVC as the compiler instead of MinGW.  There *will* be some compiler and linker errors under MSVC that will need to be fixed.  In the meantime, however, MinGW builds will be sufficient, if that is your preference.

Here is a list of a few things that I know of that will need to be fixed to compile the source under MSVC:

* The version number (VERSION) in `ghostwriter.pro` needs to be purely numeric, i.e., `1.7.1` instead of `v1.7.1`.
* MSVC presently will not link with the provided Hunspell source files.  I believe this is because the header files are missing.  Try downloading the newest Hunspell, including all header files, and adding the header files to `ghostwriter.pro`.  MSVC should find and link to Hunspell then.
* There may be special character codes (for quotation marks) used in the spellchecking code from FocusWriter that are recognized correctly by MinGW but not MSVC.  If MSVC has compiler errors, you will have to find an alternative, cross-platform means of representing these characters.

# QtWebKit

You will need [annulen's fork of QtWebKit](https://github.com/annulen/webkit/releases) regardless of compiler until the port to QtWebEngine is complete.  Annulen has both MSVC 2015 and MinGW versions available, which can be dropped into your existing Qt installation.

# Windows Issues

Volunteers will also need to support users with Windows-specific errors that cannot be replicated on Linux.  You may need to provide a patch or workaround for a Qt bug every now and then.  Being willing to file bug reports with example code that replicates the bug for the Qt devs in Qt's bugtracker is also a plus.

# Builds

You can create the installer/packaging any way you want.  I presently use Inno Setup, but apparently it's causing some problems for Windows 10 users at the moment.  If you want my script to get you started, though, just let me know.  Or, you can use something else.  Since the project is GPL, the Qt license also permits building *ghostwriter* as 100% standalone with the Qt dependencies baked into the executables.  You will have to build Qt yourself, of course, but this is an option if it is your preference.

# Forks

I propose that volunteers work together to fork *ghostwriter*, figure out what patches you will need, and supply **small** pull requests that I can test in Linux.  Please **do not** submit pull requests for new features or massive rewrites.  Small patches to keep things running in Windows will suffice.  I can link to your download executables on each release when you are ready.

**Comment by Symbian9** [comment]
Why not just setup AppVeyor? For example:

- https://github.com/solvespace/solvespace/blob/master/appveyor.yml

**Comment by boardstretcher** [comment]
If you were to get a copy of Windows 10 would you continue working on it? Do you have a paypal or some other way to donate to you?

**Comment by michelolvera** [comment]
I think I can do it, but I prefer to wait until you have the stable version and test it to confirm you. I tried to compile Hunspell with MSVC and I didn't make it work, but I didn't try that hard either... I'll wait for your stable version and I'll conform you. Thank you.

**Comment by michelolvera** [comment]
I made a Fork for Windows, I already have version 1.7.3 for Windows if anyone is interested in downloading it, I hope you find it useful. https://github.com/michelolvera/vs-ghostwriter

**Comment by noobfish** [comment]
> I made a Fork for Windows, I already have version 1.7.3 for Windows if anyone is interested in downloading it, I hope you find it useful. https://github.com/michelolvera/vs-ghostwriter

Downloading now,thanks!

**Comment by michelolvera** [comment]
> 
> 
> > I made a Fork for Windows, I already have version 1.7.3 for Windows if anyone is interested in downloading it, I hope you find it useful. https://github.com/michelolvera/vs-ghostwriter
> 
> Downloading now,thanks!

You're welcome

**Comment by wereturtle** [comment]
@michelolvera Thank you so much!  I'll put a link to it in the releases page.
@boardstretcher @thehacker00 Honestly, I don't have a lot of time in general.  I'd just rather not dual boot anymore, or even use a VM.  It's a hassle to maintain something for an OS you're not even using.

**Comment by michelolvera** [comment]
> 
> 
> @michelolvera Thank you so much! I'll put a link to it in the releases page.
> @boardstretcher @thehacker00 Honestly, I don't have a lot of time in general. I'd just rather not dual boot anymore, or even use a VM. It's a hassle to maintain something for an OS you're not even using.

You're welcome, I already have the executable version 1.7.4, do I release it now or do I wait for you to release the version?

**Comment by wereturtle** [comment]
@michelolvera Sorry for the delay!  I got sidetracked.  I just released 1.7.4, so you can release your build as well.  Thanks!

**Comment by michelolvera** [comment]
Done!

**Comment by TigersWay** [comment]
@michelolvera Could it be possible to get a portable version too?

**Comment by wereturtle** [comment]
@michelolvera FYI, version 1.8.0 now has QtWebEngine instead of QtWebKit.  Since you are already using MSVC, it should be an easy transition (knock on wood).  Let me know (here or via pull request) if anything needs to change to accommodate the Windows build.  Thanks!

**Comment by michelolvera** [comment]
> @michelolvera Could it be possible to get a portable version too?

In the next release of course.

**Comment by michelolvera** [comment]
> @michelolvera FYI, version 1.8.0 now has QtWebEngine instead of QtWebKit. Since you are already using MSVC, it should be an easy transition (knock on wood). Let me know (here or via pull request) if anything needs to change to accommodate the Windows build. Thanks!

I am working on it.
Sorry for being late.
