### ISSUE TITLE
Dependecy problem on PPA

### ISSUE THREAD

**Issue by perqbn** [wereturtle/ghostwriter#372]
Hi,

I added the official PPA and set with Xenial, when i tried install the package the system tell me that i have a lost dependecy: libhunspell-1.3, but... I have installed **libhunspell-1.4**. What happen here?

**Comment by wereturtle** [comment]
On my Xenial-based system, libhunspell-1.3 is what is available for the distro.  The PPA builds for what is available.  Have you perhaps installed another PPA package that has upgraded you to libhunspel-1.4?  These things can happen with PPAs.

**Comment by perqbn** [comment]
But i don't understand why the new version of libhunspell is all that i need.

**Comment by perqbn** [comment]
@wereturtle the problem it's so weird, 'coz i can install **ghostwriter v1.5.0**  with libhunspell-1.4, but it's no posible install  ghostwriter v1.7 from xenial ppa. Why? How is possible install GW 1.5 and no GW 1.7 with the same newer version of dependency?

**Comment by wereturtle** [comment]
I'm not sure why.  However, perhaps you can try downgrading the libhunspell package back down to 1.3?  You'll have to do an online search on how to do that.  Just a warning though:  If you choose to downgrade hunspell, you might break whatever app it was that upgraded it.
