### ISSUE TITLE
Asciidoc support (asciidoctor flavor)

### ISSUE THREAD

**Issue by jcayouette** [wereturtle/ghostwriter#377]
I would love to make this my dedicated tool if either of the following were options.

1. Write in Asciidoc instead of markdown
2. Export to Asciidoc from markdown

**Comment by john-cj** [comment]
https://github.com/wereturtle/ghostwriter/issues/64

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
