### ISSUE TITLE
Sidebar for referenced documents?

### ISSUE THREAD

**Issue by deknos** [wereturtle/ghostwriter#378]
Hi,
could there be a feature like the side bar with zim-wiki http://zim-wiki.org/screenshots/zim-normal.png ? I want to migrate to ghostwriter (due to zim being python and gtk2), but i use that sidebar quite frequently  with using a journal (where i create daily entries based on a custom date/timeformat for the filenames). 

This is not a bug, more an enhancement. my usecase is that i use zim as a personal desktop wiki and i am under the impression i could do that with ghostwriter as well :-)

Anyway, i really like your software! :)

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
