### ISSUE TITLE
fractional scaling causes blurry font in editing area

### ISSUE THREAD

**Issue by gloomy-ghost** [wereturtle/ghostwriter#379]
STR:
Launch with QT_SCREEN_SCALE_FACTORS=1.5
![2018-10-08_17-11](https://user-images.githubusercontent.com/13086421/46593140-f8036280-cb25-11e8-9739-9224d4d81fc4.png)
For some reason it scaled the font in the editing area (but not in preview), and it only occurs when the scale factor is a fractional value between 1-2.

Debian Buster, KDE Plasma 5.13.5 with Qt 5.11.1

**Comment by wereturtle** [comment]
Looks like a Qt bug.  I'll have to file a bug report for the Qt devs to look at.  Thanks!

**Comment by wereturtle** [comment]
This issue seems to have gone away on ghostwriter 1.8.0, possibly due to removing the faded text effect at the bottom of the editor (but I'm not entirely sure why that would fix it).  Can you confirm on your end that 1.8.0 resolves this issue?

**Comment by gloomy-ghost** [comment]
confirmed

**Comment by wereturtle** [comment]
Great, thanks!
