### ISSUE TITLE
IME selection window is displaced

### ISSUE THREAD

**Issue by gloomy-ghost** [wereturtle/ghostwriter#382]
![default](https://user-images.githubusercontent.com/13086421/46656405-776a6200-cc0a-11e8-9145-e4f3955380f2.png)
The used IME framework is fcitx (4.2.9.6-5), issue persists with different language.

Debian Buster, KDE Plasma 5.13.5 with Qt 5.11.1

**Comment by gloomy-ghost** [comment]
everything seems to work if I just let QPlainTextEdit to draw the cursor....

**Comment by iclementine** [comment]
I have the same issue with ghostwriter(1.74 & 1.80) and fcitx（4.2.9.6） in openSUSE 15.1. 
Qt 5.9.7, plasma 5.12.8.
