### ISSUE TITLE
[Feature request] Advanced markdown formatting

### ISSUE THREAD

**Issue by sbstn87** [wereturtle/ghostwriter#384]
Hi,

will be it possible to add some more advanced markdown formatting to ghostwriter? What I mean is the functionality presented here:
https://mdp.tylingsoft.com/

The most important features would be:
- equations
- check boxes
- subscripts
- emojis and fontawesome
- programming syntax highlighting
- mermaid charts

Best regards,
Sebastian

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
