### ISSUE TITLE
Can't find the binary for MacOs

### ISSUE THREAD

**Issue by ploum** [wereturtle/ghostwriter#387]
Although the README talks about MacOS support (and testers needed), I can't find the link to a binary to install. Not sure if that binary exists or not. If yes, it would be awesome to make a cask so ghostwriter is available through brew.

**Comment by tommyboylab** [comment]
I would also be interested. I tried to compile on both High Sierra and now Mojave using Qt but I am receiving an error on both: Project WARNING: Qt requires at least version 10.14 of the platform SDK, you're using 10.13.4. Please upgrade.
Project WARNING: Qt has only been tested with version 10.13 of the platform SDK, you're using 10.13.4.
Project WARNING: This is an unsupported configuration. You may experience build issues, and by using
Project WARNING: the 10.13.4 SDK you are opting in to new features that Qt has not been prepared for.
Project WARNING: Please downgrade the SDK you use to build your app to version 10.13, or configure
Project WARNING: with CONFIG+=sdk_no_version_check when running qmake to silence this warning.
Project ERROR: Unknown module(s) in QT: webkitwidgets

**Comment by pazos** [comment]
@ploum  @tommyboylab You can grab a build from https://github.com/wereturtle/ghostwriter/issues/368

**Comment by tommyboylab** [comment]
I have successfully build the latest version of Ghostwriter (1.7.4) from source. @ploum you can grab it here. In the future if you would need/want to compile it yourself I found the way to install Qt 5.5 from here.

https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-high-sierra-1013-macos-sierra-1012-el-capitan-1011-and-yosemite-1010


And the DMG.
https://mega.nz/#!diwjHQ7A!vWMHRACt2Ih6vVzkx6V5lp2shp4iWC6QhIviwlYJTNE
