### ISSUE TITLE
How to Add Extra Export Formats - question for portable version (no-admin rights)

### ISSUE THREAD

**Issue by sorashadow** [wereturtle/ghostwriter#388]
Question about wiki page [How to Add Extra Export Formats](https://github.com/wereturtle/ghostwriter/wiki/How-to-Add-Extra-Export-Formats):
You say we need to install any of those converters on the page for it to work; however, I have no admin rights in my machine at work, so I can't do install anything.

Is there any way I can tell ghostwriter to "look for a path" instead of a pre-compiled one?

Thanks in advance

**Comment by wereturtle** [comment]
You can put the executables for, say, Pandoc (example) in the same folder as the ghostwriter executable.  The app should be able to find it there.
