### ISSUE TITLE
Avoid automatching of some characters

### ISSUE THREAD

**Issue by suhr** [wereturtle/ghostwriter#39]
Since triple grave accent is used  to start a code block, and `>` also means “greater than”, you want to avoid automatching on these characters.

**Comment by wereturtle** [comment]
I disagree.  Many other Markdown tools automatch the grave accent and the `<` character.  It's annoying when you meant to start a code block or just want to do math, but on the other hand I and many others use this automatch feature.  The automatch feature can always bee disabled through the Settings menu.

**Comment by suhr** [comment]
Ok, what about automatch customization?

**Comment by wereturtle** [comment]
That sounds reasonable.

**Comment by wereturtle** [comment]
Close for now due to lack of time.  Can reopen if there is more interest in the future.

**Comment by wereturtle** [comment]
Feature implemented in commits 3087acd0bb01c60b62f1194e95d2e0a841b0082f and 5f76e04beb4ddfd9cd43fae6ec915772417f0f59.  Closing this issue.
