### ISSUE TITLE
Suggested enhancement: allow pasting RTF auto convert to md

### ISSUE THREAD

**Issue by dgk4201** [wereturtle/ghostwriter#394]
This is a feature I use all the time with Ulysses. My process is to copy RTF text from powerpoint, use the "PASTE FROM RTF" into Ulysses, and then copy from the resulting md to the clipboard as html. I past the HTML into an SQL database. My app (ixploreYellowstone) can then display formatted text.

I'm moving from macOS to Linux and Ulysses isn't available. My workaround is to use dropBox's PAPER to past in RTF text and then export to a md file. I can then open the md file with ghostwriter and copy the html to the clipboard. It would be great to be able to do this all in ghostwriter.

Thanks

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
