### ISSUE TITLE
Cursor keys do not work (Ubuntu, XRDP connection from Windows)

### ISSUE THREAD

**Issue by noncom** [wereturtle/ghostwriter#395]
I am encountering the following problem with Ghostwriter when connecting to Ubuntu 16.04.5 through xRDP from a Windows 10 PC using the standard `mstsc` Windows client:

- The cursor arrow keys do not work except for the `Down` arrow which works differently
- The `Down` arrow acts as if pressing the `Return` key, ie. it starts a new line
- The `Backspace` button works
- The `Delete` button does not work
- The `Return` button on the numpad does not work

It would be nice if this issue could be addressed. I am happy to provide any additional information if needed.

**Comment by wereturtle** [comment]
This sounds more like an RDP issue than a ghostwriter issue.  I'm afraid there isn't much I can do to help.
