### ISSUE TITLE
Edit pane loses focus after scrolling HTML preview pane

### ISSUE THREAD

**Issue by Kzer-Za** [wereturtle/ghostwriter#397]
If you scroll over the HTML preview pane, then edit pane stops receiving keystrokes until you click on it. What makes it even more confusing, is that the cursor does not disappear from where it was in the edit pane or stop blinking. It makes me every time stop for a second until I realize why nothing appears of what I try to type.

You can't even return focus to the edit pane by scrolling it, you have to actually click somewhere in it, so it's rather inconvenient: you can lose the focus by scrolling over the HTML preview pane, but you cannot return focus the same way. And since clicking somewhere in the edit pane takes the cursor there, you have to click exactly where your cursor is if you want to continue working from where you stopped before you started scrolling.

I have Ghostwriter 1.7.3, Linux, XFCE.

**Comment by jeff9315** [comment]
I've also noticed this on Windows 10, Ghostwriter 1.7.3. I think it also occurred in previous versions but I never reported it.

**Comment by wereturtle** [comment]
This is probably more of an issue with Qt, since the WebKit widget is it's own thing that isn't quite native to Qt.  As such, I don't think there's much I can do about it.
