### ISSUE TITLE
[MacOS] HTML is the only export option

### ISSUE THREAD

**Issue by king-gheedorah** [wereturtle/ghostwriter#398]
I don't believe Pandoc is integrated in the build, as the only export option is HTML.

Using the build from [Issue #368](https://github.com/wereturtle/ghostwriter/issues/368).
Mac OS Mojave, v. 10.14.1

Thank you for your work on this app, would love to use this in my workflow between Linux & MacOS.

**Comment by tommyboylab** [comment]
Latest release from #387

**Comment by king-gheedorah** [comment]
Installed the latest release, the issue still stands.

@tommyboylab thanks for the updated version!
