### ISSUE TITLE
libhunspell error

### ISSUE THREAD

**Issue by eternaltyro** [wereturtle/ghostwriter#399]
Arch Linux package upgrade bumped up `libhunspell` version and ghostwriter is refusing to start.

```
~ » ghostwriter
ghostwriter: error while loading shared libraries: libhunspell-1.6.so.0: cannot open shared object file: No such file or directory
```

I had to create a symlink to work around it.
```
ln -s /usr/lib/libhunspell-1.7.so.0 /usr/lib/libhunspell-1.6.so.0
```

It'll be better if the link was to `libhunspell.so` unless there's a hard version dependency.

**Comment by abenson** [comment]
Did you install using AUR? You'll need to rebuild it to link against the new library.
