### ISSUE TITLE
single column table is not highlighted

### ISSUE THREAD

**Issue by dmarrazzo** [wereturtle/ghostwriter#401]
single column table is not correctly highlighted

e.g.

|    id    |
|----------|
|    1     |
|    2     |
|    3     |

**Comment by data-man** [comment]
Works with cmark-gfm and MultiMarkDown at least.

![Screenshot_20200706_200113-cmark-gfm](https://user-images.githubusercontent.com/1754269/86608207-a9694d80-bfc3-11ea-9485-36b5ed4fda6e.png)

![Screenshot_20200706_200206-mmd](https://user-images.githubusercontent.com/1754269/86608221-aff7c500-bfc3-11ea-9925-b00901b2f976.png)
