### ISSUE TITLE
[Feature Request] Edit Pandoc flags in settings

### ISSUE THREAD

**Issue by tecosaur** [wereturtle/ghostwriter#408]
Hi,

I'm quite new to this, but looking at the issues page it seems that quite few of the issues created can be resolved by changing Pandoc flags, I myself am also currently an issue that relates to Pandoc flags.

As a result, to me it looks like it could be a good idea to add something like a text box in the settings pane that shows the Pandoc flags and allows them to be modified.

Let me know what your thoughts are.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

**Comment by tecosaur** [comment]
I see, since the indefinite length of the 'no more features for now' bit is particularly vague, do you have any (rough) idea of when you might become open to feature requests and PRs?

Even an orders-of-magnitude style answer would be nice (days, weeks, moths, etc.)
:)
