### ISSUE TITLE
Export to docx with automatically numbered headlines?

### ISSUE THREAD

**Issue by merlinuwe** [wereturtle/ghostwriter#413]
How is it possible to export to docx with automatically numbered headlines?

Example:

1 First level headline
1.1 Second level headline
1.2 Second level headline
1.2.1 Third level headline
2 First level headline
2.1 Second level headline
...

**Comment by wereturtle** [comment]
It's not currently possible via ghostwriter, but you can always use the command line with pandoc to do so.  The interface was really meant to stay out of the way and encourage formatting the docx file after you've exported.
