### ISSUE TITLE
Ensure newline at end of file

### ISSUE THREAD

**Issue by estan** [wereturtle/ghostwriter#414]
Hi,

I think it would be great if Ghostwriter could ensure there's a newline at the end of file like text editors do (Kate, gedit, Emacs, ...). [According to POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), the definition of a line includes a newline character.

This would help annoying `\ No newline at end of file` in Git diffs when working with both text editors and Ghostwriter and forgetting to put in the last newline manually.

Example:

- Start Ghostwriter
- Type in `# Test` (don't hit Return)
- Save as `foo.md`
- Count lines with `wc`: 
    ```
    $ wc -l foo.md 
    0 foo.md
    $
    ```
- Do the same in any text editor and the line count is 1.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
