### ISSUE TITLE
Doubled scaling on hi-DPI screens

### ISSUE THREAD

**Issue by fbruetting** [wereturtle/ghostwriter#418]
v1.7.4

As you see below, the text on my UHD screen is scaled too much. When I drag it to my external HD screen, it gets scaled correctly.

![bildschirmfoto von 2019-02-15 00-27-05](https://user-images.githubusercontent.com/10520767/52824429-cd6b7c80-30b8-11e9-95e5-2081ee0c1031.png)

**Comment by wereturtle** [comment]
What is your distro/desktop environment? Note that some don't play well with mixed monitor resolutions.  

Have you noticed whether other Qt apps behave similarly?

Also, would you please open a terminal and type the following command and give me the results?

```
$ echo $QT_SCALE_FACTOR
```

Finally, please try the following set of commands to manually change the scaling factor to something better:

```
$ export QT_SCALE_FACTOR=2
$ ghostwriter&
```

You can try setting the above to 1.5 if 2 is too big, or whatever suits you.

**Comment by fbruetting** [comment]
I run Fedora Silverblue 29 with Gnome 3.30, so about the latest stable version of software I can get. Almost all applications scale well, with the exception of some very few, like Ghostwriter. And this is the sole Qt application I run.

To be precise: On my HD screen everything is doubled in size. On my UHD screen all text elements are too big by a factor of 4, while the window is correctly sized (because it is doubled on the HD screenn and then doesn’t adapt to the UHD screen).

`echo QT_SCALE_FACTOR` returns nothing and running the application after exporting `2`, scales just all text elements by an additional factor of two, while the window isn’t affected at all.

**Comment by wereturtle** [comment]
Okay, would you please try installing another Qt5 application and seeing if the problem is common to Qt apps?  This sounds very much like a Gnome issue or a configuration issue with Qt.  Also, are you running Wayland?  If so, try X and see if the situation improves. If you can confirm that other Qt apps behave similarly, then I think it would be best for you to file a bug report with Gnome or Wayland (depending on which is the culprit).  Otherwise, I will keep investigating.

**Comment by fbruetting** [comment]
Do you have an example Qt app from Flathub?

**Comment by rusty-snake** [comment]
@fbruetting  io.github.qtox.qTox, org.shotcut.Shotcut, org.videolan.VLC, org.openshot.OpenShot, info.bibletime.BibleTime, org.clementine_player.Clementine, io.github.cloose.CuteMarkEd, org.flatpak.qtdemo, org.keepassxc.KeePassXC, org.filezillaproject.Filezilla

**Comment by fbruetting** [comment]
FileZilla shows up correctly on both of my displays.

**Comment by rusty-snake** [comment]
@fbruetting Uhh sorry. It looks like filezilla is not using QT. So just try an other one.

**Comment by fbruetting** [comment]
Ok, KeePassXC has similar issues. Does these applications then use XWayland?

**Comment by rusty-snake** [comment]
I'm running Fedora 29 (not Silverblue) with GNOME and Wayland.
By default my keepassxc (installed with dnf) run under XWayland.
But you can force it to use Wayland:
  * The application must use QT5
  * You must install qt5-wayland (not for flatpak)
  * You must set `QT_QPA_PLATFORM=wayland`

**Comment by fbruetting** [comment]
Has the same issues. Ghostwriter now even doesn’t scale consistently throughout the content. The headings are WAY bigger than the text. Crazy Qt.

![Bildschirmfoto von 2019-03-25 23-48-29](https://user-images.githubusercontent.com/10520767/54959179-96f70c00-4f58-11e9-9ece-8e8bf56c8e58.png)

![Bildschirmfoto von 2019-03-25 23-09-03](https://user-images.githubusercontent.com/10520767/54959215-af672680-4f58-11e9-864f-e450c1c1e1a9.png)
