### ISSUE TITLE
Tabs are not correctly rendered

### ISSUE THREAD

**Issue by fbruetting** [wereturtle/ghostwriter#419]
`v1.7.4`

The content `\t- ab\ta` is rendered as `    - aba` instead of `    - ab    a`. For some reason, I need to type `\t- ab\t\ta` for achieving the intended output column format (and I set a mono font).

**Comment by wereturtle** [comment]
Are you referring to the HTML preview rendering?  Do you have more specific content that I can paste?  What processor are you using?  (Sundown?  Pandoc?  etc.)

**Comment by fbruetting** [comment]
Ah, that seems to have been the font spacing. So there was maybe just 1px to the next tab stop, so the renderer just moved the text forward by 1px due to the tabstop.
