### ISSUE TITLE
Highlighting TODO & FIXME

### ISSUE THREAD

**Issue by fbruetting** [wereturtle/ghostwriter#420]
`v1.7.4`

Would be cool if those keywords could get highlighted (in for example bold red), like in IDEs. :)

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
