### ISSUE TITLE
Bold Option not Highlighting Correctly

### ISSUE THREAD

**Issue by gelatinbomb** [wereturtle/ghostwriter#421]
Hello
It looks that bold visualization in the editor is not working, the rest of options appears in the editor except the bold one.

![screenshot_20190219_210253](https://user-images.githubusercontent.com/31792239/53063482-e80f6e00-3489-11e9-96bc-b57d5e91d09e.png)

**Comment by Reinis** [comment]
As far as I can see, there is no option for underlined text (double tildes is for strikethrough). Bold is working fine for me with Ghostwriter 1.7.4 on Gentoo Linux.
![ghostwriter-1 7 4-r1_gentoo_2019-02-21_14-04-02](https://user-images.githubusercontent.com/1250117/53168182-c37ad980-35e2-11e9-8685-f8939ed57522.png)

**Comment by rusty-snake** [comment]
Ghostwriter: 1.7.4
OS: Fedora 29
Install: with dnf

Bold works, underline with `<u>Underline</u>`

**Comment by Reinis** [comment]
It would be nice if underline in Markdown would work, e.g., like in Discord [1], without a need to resort to inserting HTML tags.

[1] https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by gelatinbomb** [comment]
I'm using ghostwriter 1.7.4 in kubuntu 18.04, maybe there is something that i missing, but i don't know what it is. I'm using the ppa.

**Comment by gelatinbomb** [comment]
About the "underlined", i used bad the word, i was talking about the "strikethrought" word, my english is really bad, sorry :P

**Comment by abenson** [comment]
What font are you using?

**Comment by gelatinbomb** [comment]
I'm using DejaVu Sans Mono.

**Comment by wereturtle** [comment]
> I'm using DejaVu Sans Mono.

@gelatinbomb I was just going to ask you that.  Some monospaced fonts don't have a bold font available.  However, DejaVu Sans Mono *does*.  In fact, I'm using it right now, and bold is working, so something else is afoot.

I'm on Mint 19, which is based on 18.04.  I am also using my own PPA.  Maybe it's a Kubuntu packaging thing?  What happens if you select a different font?  Does the bold type show correctly?

**Comment by gelatinbomb** [comment]
@wereturtle I tried noto sans and is working!, :thinking:

**Comment by wereturtle** [comment]
Well, since it's working with a different font, I'm going to close the issue.  It seems limited to something in Kubuntu anyway.  Glad you were able to find a workaround!
