### ISSUE TITLE
Data loss with .md file and associated .md.backup

### ISSUE THREAD

**Issue by starchy** [wereturtle/ghostwriter#422]
When opening a file of running notes I've been keeping with ghostwriter for over a month just now, I was surprised to find the file empty. Looking in the directory on disk, both `file.md` and `file.md.backup` appear to be 0 bytes.

Both "Auto save" and "Backup file on save" are enabled.

**Comment by wereturtle** [comment]
What OS / distro / desktop environment / Qt version / etc. are you running?

**Comment by starchy** [comment]
Apologies for the late reply. I'm running Debian stretch with i3wm. Precise
versions wouldn't match what I had when I saw this issue, and it hasn't
recurred since my initial report.
