### ISSUE TITLE
MultiMarkDown File Transclusion

### ISSUE THREAD

**Issue by Foadsf** [wereturtle/ghostwriter#426]
I have asked this question [here](https://www.reddit.com/r/writing/comments/b0ywcw/free_markdown_editors_with_live_preview_for/) in more details. Basically I want to merge / include / import MD files without compiling and have live preview. I have explained the my requirements [here ](https://stackoverflow.com/questions/55153499/using-html-to-include-import-merge-markdown) in more details. I was wondering if this feature could be added to GhostWriter?

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
