### ISSUE TITLE
feature request: preview right click jump to edit

### ISSUE THREAD

**Issue by SmilingHorse** [wereturtle/ghostwriter#427]
Workflow wise, sometimes you go over the preview proofing for typos and whatnot and then spot an issue you want to edit. It would be nice if you could just right click there and the editing cursor would jump to where you clicked.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
