### ISSUE TITLE
Better distinction between heading levels

### ISSUE THREAD

**Issue by fbruetting** [wereturtle/ghostwriter#428]
In notes and other documents, which are highly structured in levels but have not that much content, it’s not that easy to differentiate between the headings. So a layer 2 heading inside of a list of level 3 headers can easily be overseen. Could you please make this more obvious? E.g. by:

* Adding an underline for first level headings,
* stop colouring beginning with heading level 3,
* stop bold markup or reducing the font size by a larger step for heading levels 4 and below
* make heading level 5 italic.
* Additionally it could be useful to vary the heading font sizes by a larger degree in general.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
