### ISSUE TITLE
Indenting multiple lines of indentations

### ISSUE THREAD

**Issue by fbruetting** [wereturtle/ghostwriter#429]
Do you like to do automatic indentation of multiple lines of indented content like this:

![Bildschirmfoto von 2019-03-22 17-11-07](https://user-images.githubusercontent.com/10520767/54836977-9e52b700-4cc5-11e9-92e5-a6240ac2046e.png)

**Comment by wereturtle** [comment]
I'm afraid it's a limitation with both QTextEdit and QPlainTextEdit.  It just isn't possible (at least not without wrecking the undo stack).
