### ISSUE TITLE
unwanted paragraph space in live preview

### ISSUE THREAD

**Issue by brainchild0** [wereturtle/ghostwriter#430]
**Description:**

Live preview shows paragraph space before recently-edited lines even when the line does not follow a blank line and the previous line ends with a pair of space characters.  Such lines should, following MarkDown conventions, be separated from the preceding line  only by a line break, not paragraph spacing.

 **Steps to reproduce:**

1.  Download ~~[this MarkDown file](https://gist.githubusercontent.com/brainchild0/1199a329d88b0ec48b4a2e0a14262919/raw/e593cedc36d861f7d16fcd8371b3c232588e0577/lines.md)~~ [this   file](https://gist.githubusercontent.com/brainchild0/1199a329d88b0ec48b4a2e0a14262919/raw/a0723539c66de59ec316fe9ab15c9df77d8623cc/lines.md).
1.  Open in Ghostwriter.
     *Notice that each line ends in a pair of space characters preceding the line break, causing each  paragraph to be formatted as a new line, with no paragraph spacing.*
1.  Make a change to any line in the middle of  a group of lines, for example, by correcting   one of the instances of "fou rth" by removing the space character.

The live preview now incorrectly displays paragraph spacing before the edited line, as seen in this screen capture of the initial part:

 ![screen_capture.pnp](https://user-images.githubusercontent.com/34869175/55001328-bb7bd400-4faa-11e9-8844-7672438b2381.png)

**Version information:**

* ghostwriter v.1.7.4
* Qt version: 5.9.5
* OS: Linux Mint 19.1

**Comment by tonghuix** [comment]
I cannot reproducing this bug, tried every step you provided. And I also tried other Markdown flavor and other style sheets..

**Comment by brainchild0** [comment]
Did you test with the same release?

Would it help if I gave details of my configuration?  I can try to restore to factory defaults, but I see no option for doing so, and would like to be able to restore back to the current state afterward.

**Comment by tonghuix** [comment]
Yes same release, but Ubuntu 18.10.

I don't think it is caused by your configuration.

**Comment by brainchild0** [comment]
In your test you see three groups each of ten lines, and you can edit any line freely without affecting the apparent grouping of lines in the preview?  If so, it is not what I have seen over the last several weeks since beginning to use the software on my system.

Please let me know what you suggest.

**Comment by tonghuix** [comment]
![](https://user-images.githubusercontent.com/423703/55005978-efd9a980-5017-11e9-8390-fb8e1c37cbc5.png)

Please note that, I am doing Chinese translation, so you will see there are some Chinese char on UI.

**Comment by brainchild0** [comment]
I understand now.  Github condensed the whitespace when I copied from local clipboard and saved into the Gist.  The issue appears only when the lines end with a pair of space characters, which were not present in the version I originally included.

Please repeat with [this file](https://gist.githubusercontent.com/brainchild0/1199a329d88b0ec48b4a2e0a14262919/raw/a0723539c66de59ec316fe9ab15c9df77d8623cc/lines.md).

Please confirm *first* that the input lines each end with a pair of space characters, *and* appear as separate lines in the preview.  Otherwise the specific issue I describe is irrelevant.

**Comment by tonghuix** [comment]
I could **CONFIRM** the bug!!!

![](https://user-images.githubusercontent.com/423703/55009441-82307c00-501d-11e9-95ef-3ee823167d5c.png)

And I also find how to resolve it (workaround), just change to other Markdown flavor or style sheet, it will trigger refresh the preview frame, so it would regenerate correctly.

**Comment by brainchild0** [comment]
Yes, this incorrect formatting has short memory, but is still very annoying.  I am glad you can confirm.

**Comment by brainchild0** [comment]
Is  any workaround available in current versions that is easier to invoke?  For example, a keyboard shortcut that simply refreshes the preview pane?

**Comment by Garbulix** [comment]
I also have this problem - here is a short screencast. Look at the weird empty lines, that finally doesn't exist in Firefox (first two headers and added informations about "UWAGA")
https://youtu.be/rSO2Auk_rvU
