### ISSUE TITLE
very large preview text

### ISSUE THREAD

**Issue by brainchild0** [wereturtle/ghostwriter#432]
**Description:**

Using some common style sheets in public distribution, the preview text appears very large, compared to the intended appearance of text using the same style sheet, as viewed in other display software.

 **Steps to reproduce:**

 Download, [Splendor](https://raw.githubusercontent.com/markdowncss/splendor/master/css/splendor.css), from John Otander's *Markdown CSS* collection, and make it the preview style for Ghostwriter.

Notice very large type size in preview, especially for headings.  *While the text size in a screen capture will not appear as originally, the body text seen in the application  plainly appears   larger than general body text normally appears.* 

![Screenshot from 2019-03-27 15-49-18](https://user-images.githubusercontent.com/34869175/55107524-f0ba1c00-50a7-11e9-91b7-0b3cbee2bb4e.png)

**Version information:**

* ghostwriter v.1.7.4
* Qt version: 5.9.5
* OS: Linux Mint 19.1

**Comment by tonghuix** [comment]
Yep, I could confirm this. In preview pane, it is larger than css defined.

**Comment by brainchild0** [comment]
Some style sheets use `px` units, which I consider strange.  I wonder whether the issue is related to unit conversion.

**Comment by wereturtle** [comment]
It does this in QtWebEngine (Chromium) as well.  It's possible it's due to the code that's setting the DPI of the browser to be that of the system's DPI, but without this code, people with custom DPI will be stuck at 96 DPI, which is undesirable.  I would suggest editing the stylesheet to correct its font units.
