### ISSUE TITLE
Remove italics on second press of Ctrl+I

### ISSUE THREAD

**Issue by owenshen24** [wereturtle/ghostwriter#433]
Currently, if I am trying to un-italicize text, hitting Ctrl+I will instead add another pair of '*' to the selection, turning it bolded instead.
Changing the Italic function to check for already italicized text and un-italicizing in response would be a greatly appreciated modification.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
