### ISSUE TITLE
yaml block handling inconsistent

### ISSUE THREAD

**Issue by brainchild0** [wereturtle/ghostwriter#434]
Currently, Ghostwriter implicitly supports YAML header blocks, due to Pandoc being one of the means to render previews and to export documents.  However, whether a preview will display these blocks as YAML versus Markdown content  depends on which preview mode is selected.  More significantly, these blocks are always processed as Markdown in the editor pane, meaning that they will display incorrectly from the standpoint of a user who includes them in documents for the purpose of generating results that include title and author information in published output.  A triplet of dashes, which closes a YAML block, is interpreted as a heading marker for the previous line, which is correct Markdown processing, but incorrect if a similar triplet of dashes was previously used to mark the beginning of a YAML block.  As YAML headers in Markdown documents is an increasingly widespread convention, and as a variety of features in Ghostwriter already make heavy use of Pandoc, which famously utilizes this approach, it would be useful if support in Ghostscript were more friendly to the user.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
