### ISSUE TITLE
Exports Do Not Contain Local Image

### ISSUE THREAD

**Issue by JonathanKryza** [wereturtle/ghostwriter#436]
When exporting a file to docx or PDF, the image(s) are not exported with the document. 

![image](https://user-images.githubusercontent.com/3247900/56385637-5d2ac580-61e5-11e9-9ae2-2b8616b5ba03.png)

![image](https://user-images.githubusercontent.com/3247900/56385691-83e8fc00-61e5-11e9-88f9-8ac4e6df8f45.png)

Windows 10
GhostWriter v.1.7.3

**Comment by wereturtle** [comment]
This is an issue with Pandoc.  Please file a bug report at Pandoc's issue tracker [here](https://github.com/jgm/pandoc).  As a workaround, try using either a relative path to the markdown file's location, or else a full path that does not contain `file:///`.
