### ISSUE TITLE
pdflatex not found

### ISSUE THREAD

**Issue by spmima** [wereturtle/ghostwriter#438]
Dear wereturtle,

I installed Ghostwriter (v.1.7.4) today on my LinuxMint (19.1. Cinnamon) and have a very positive feeling about it, you have been doing wonderful work on it. 

However, I have a rather strange problem. Whenever I try to export to pdf, I get an error saying that the export failed because pdflatex is not found. I should also try to pick another latex engine. However, my pandoc and pdflatex are on working normally. html export and even export to word and latex seems to be working correcly. My pandoc is version 1.19.2.4 and  pdfTeX 3.14159265-2.6-1.40.18.

Best wishes,

**Comment by wereturtle** [comment]
You have to install texlive-latex-extra package.  I also recommend using the `--install-recommends` flag (including when installing pandoc, but probably too late for that), since Mint doesn't include this option automatically like base Ubuntu does.

**Comment by spmima** [comment]
Thank you. I have texlive installed, texlive-latex-extra is the newest version for Linux Mint (2017.20180305-2). Do you suggest that I re-install pandoc with --install-recommends flag?

**Comment by wereturtle** [comment]
That might be a good idea.  I'm definitely not seeing the same issue.  (I'm also on Mint 19.1 with Cinnamon.)
