### ISSUE TITLE
Do not recommend installing qt5-default

### ISSUE THREAD

**Issue by perezmeyer** [wereturtle/ghostwriter#439]
Hi! With my Debian Qt maintainer hat on: making the user install qt5-default is a mistake as it will change the user's default Qt system for everything.

Please just call qmake -qt5. If you want more information, man qtchooser.

Thanks!

**Comment by PrSunflower** [comment]
Hi, I am running Debian 10 Buster and I tried what you said, it worked perfectly fine for me.

Commands I used:
```
sudo apt install build-essential
sudo apt install g++ qtbase5-dev libqt5svg5-dev qtmultimedia5-dev qtwebengine5-dev libhunspell-dev pkg-config libqt5concurrent5 qttools5-dev-tools
```
(Notice I didn't install `qt5-default` like mentionned in the README.md.)

```
cd ghostwriter/
qmake -qt5
make
make install
```

And Ghostwriter is working perfectly fine for me.

**Comment by PrSunflower** [comment]
@wereturtle Should `qt5-default` be removed from the README.md and `qmake` edited to `qmake -qt5`?

**Comment by perezmeyer** [comment]
You can even omit the -qt5 if you require Qt  to build it. In fact not many people has Qt 4 around anymore, and whoever wants to compile Qt stuff on a Linux distro should read qtchooser's man page.
So just removing qt5-default should be enough.

**Comment by PrSunflower** [comment]
Neat 👌

Keep up the good work! Thanks for this wonderful app which is Ghostwriter!
