### ISSUE TITLE
support non-URL URIs (1.8.0)

### ISSUE THREAD

**Issue by SmilingHorse** [wereturtle/ghostwriter#440]
Before 1.8.0 non-URL URIs were passed correctly to xdg-open. So:

`[test](about:reader?url=https://xuanji.appspot.com/isicp/1-1-elements.html)`

would have passed the full "about:reader?url=https://xuanji.appspot.com/isicp/1-1-elements.html" to xdg-open that passed it to exo-open or the likes that handled it as instructed, and in this case, passed it along to firefox.

Now it just opens a white page.

TBH Markdown's specs only specify URLs and relative references. But I figured since it used to work it might be an unintended regression due to switching engines... Crossing fingers :)

Refs:
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
http://edoceo.com/howto/xfce-custom-uri-handler

**Comment by wereturtle** [comment]
Sorry, I only ever intended basic HTML/CSS + Mathjax Javascript rendering in the preview.  Part of the issue as to why xdg-open isn't working is that a port from QtWebkit to QtWebEngine is not one-for-one.  The API is rather different.  But as long as the main intended functionality is there, I think it's good enough.  I'll always keep an eye out on how to bring that feature back, of course.  A future API change could make it easier.  You never know?
