### ISSUE TITLE
Equation preview on Ubuntu stopped working

### ISSUE THREAD

**Issue by cgoise** [wereturtle/ghostwriter#443]
Hi,

I do not know what has changed, but since shortly ghostwriter doesn't show equation previews any more. Preview settings are (probably) ok: pandoc.

For instance: $\mu$ is now displayed as '\mu'.  

I'm running Ubuntu 18.04, ghostwriter 1.8.0 from the ppa. Pandoc was tested in version 1.19.2.4 and 2.7.2 - both don't show the equations.

Thank you.

**Comment by cgoise** [comment]
Hi again,

this doesn't seem to be an ubuntu problem after all. 

The problem occurs only on KDE Neon (which is based on 18.04). On a _clean_ Ubuntu 18.04 install ghostwriter runs as expected.

**Comment by chopin2712** [comment]
Hello! I am having the same problem and I am not on KDE I am running Xubuntu. 
I have the same problem. I the package `libqt5webengine` couldn't be found in the Ubuntu repository, the only one I have is called `libqt5webengine5`. The version is 5.12.8.

So Ghostwriter is not compatible with that version?

Btw: I am running Ghostwriter 1.8.0.
