### ISSUE TITLE
Ctrl+K as shortcut for link

### ISSUE THREAD

**Issue by BNolet** [wereturtle/ghostwriter#444]
In many WYSIWYG editors (as well as some desktop editors) Ctrl+K is the hotkey for hyperlinking a selected piece of text. Can this become the default for Ghostwriter?

**Comment by BNolet** [comment]
Additional: 

An implementation of this could be that when pressing Ctrl+K with text selected, it puts the square brackets around the selected text, unselects it and moves the cursor between the following parenthesis

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
