### ISSUE TITLE
Parenthesis at end of URL results in erroneous link termination

### ISSUE THREAD

**Issue by BNolet** [wereturtle/ghostwriter#446]
See screenshot for example:

![image](https://user-images.githubusercontent.com/10198484/59000024-a60afd80-87d6-11e9-883e-d9cf2ee049bb.png)

**Comment by abenson** [comment]
Escape the parenthesis in the URL. This is the way it behaves in all of the Markdown implementations I've used.

     [M-42](https://en.wikipedia.org/wiki/M-42_\(Michigan_highway\))

[M-42](https://en.wikipedia.org/wiki/M-42_\(Michigan_highway\))

**Comment by BNolet** [comment]
:man_facepalming: Thank you, I'm an idiot.
