### ISSUE TITLE
email-link-building buggy

### ISSUE THREAD

**Issue by rdggithub** [wereturtle/ghostwriter#448]
E-Mail-Link-Building in HTML-preview/export doesn't work properly.

Reproduce some errors by pasting the following into a new document while having a look at HTML-output:

```
E-Mail: foobar@xyz.com  
E-Mail: foobarfo@xyz.com  
E-Mail: foobarfoo@xyz.com  
E-Mail: foobarfoobar@xyz.com  
E-Mail: foob@foobarfoo.de  
E-Mail: > foob@foobarfoo.de
```

output:

<p>E-Mail:<a href="mailto:%20foobar@xyz.com"> foobar@xyz.com</a><br>
E-Mail: f<a href="mailto:oobarfo@xyz.com">oobarfo@xyz.com</a><br>
E-Mail: fo<a href="mailto:obarfoo@xyz.com">obarfoo@xyz.com</a><br>
E-Mail: fooba<a href="mailto:rfoobar@xyz.com">rfoobar@xyz.com</a><br>
<a href="mailto:E-Mail:%20foob@foobarfoo.de">E-Mail: foob@foobarfoo.de</a><br>
E-Mai<a href="mailto:Mail:%20%3E%20foob@foobarfoo.de">Mail: &gt; foob@foobarfoo.de</a></p>

**Comment by wereturtle** [comment]
I presume you are using Sundown?  This looks like a bug with that.  Unfortunately, it's no longer maintained by anyone.  You can try installing Pandoc, MultiMarkdown, etc., and see if you get better output.
