### ISSUE TITLE
are there plans to support HUD tiling/docking?

### ISSUE THREAD

**Issue by frankist** [wereturtle/ghostwriter#449]
Is there a plan to make HUDs (e.g. outline) non-floating? Pop-up floating windows are kind of a hindrance for people using window managers like i3, as, at least in my case, floating windows stay visible when I change workspaces.

I couldn't find any info related to this, so apologies if this question has already been asked.

**Comment by wereturtle** [comment]
Not really.  I mean, someday I might get the itch to do that, but not in the near future.  Sorry.
