### ISSUE TITLE
[feature request] macOS support

### ISSUE THREAD

**Issue by semiopat** [wereturtle/ghostwriter#450]
Do you think about a macOS support one day? This could be great…

**Comment by wereturtle** [comment]
That's really up to volunteers to package it and provide an installation link.  Apparently, that's actually hard to do?  I'm not sure how packaging an installable, fully contained executable on MacOS actually works.  But kind volunteers have managed to create some very nice build and installation instructions in the README file.

**Comment by semiopat** [comment]
Ok I’ll test it; thanks!
