### ISSUE TITLE
Recent File list

### ISSUE THREAD

**Issue by DaleEasley** [wereturtle/ghostwriter#454]
I am using Ghostwriter 1.8.0 under Linux Lite.  When it opens, it does not restore my last opened file nor does it list recently opened files.  I made sure that under Settings -> Preferences -> Remember File History was checked.  In the past, this has operated correctly but now is broken, though I'm not sure at what point, though definitely around 4/27/2019 when the file that keeps opening was created.  Any ideas?  I checked, and other programs still show their recent file list.  BTW, thanks for the work.  I love the program.

**Comment by DaleEasley** [comment]
I used the terminal commands from your page:sudo add-apt-repository ppa:wereturtle/ppa
sudo apt-get update
sudo apt-get install ghostwriterInitially, everything worked fine, but recently, after updating (or maybe installing some other software?) It doesn't save the recently opened file list.  I wonder... where is the list stored? Could something have perhaps shifted it to read-only?  But I get no error message when closing Ghostwriter.  Still, I appreciate the program tremendously.  Don't spend a bunch of time on it---I can just open files from the file manager.Dale
    On Tuesday, August 27, 2019, 12:20:09 PM CDT, wereturtle <notifications@github.com> wrote:  
 
 
Are there any other details / steps that you could provide to help me reproduce this behavior? I am not having this issue on Ubuntu.

**Comment by wereturtle** [comment]
ghostwrite'rs configuration is stored under `~/.config/ghostwriter`

In particular, it's the `ghostwriter.conf` file within that directory that stores the file history.  Within, you should see a section like this:

```
[FileHistory]
1\cursorPosition=4595
1\filePath=/home/YourUserId/Documents/file1.md
10\cursorPosition=78
10\filePath=/home/YourUserId/Documents/file2.md
11\cursorPosition=413
11\filePath=/home/YourUserId/Documents/file3.md
```

If you're not seeing that, and the file isn't updating between sessions, then I'd definitely would check that it's not read-only or owned by someone else.

**Comment by DaleEasley** [comment]
Thanks for replying.  It's got plenty of entries, but the file date is 5/1/2019, so it hasn't been updating it nor, apparently, reading it when opened.  I tried uninstalling and then reinstalling---no joy.  Then I renamed it, reran Ghostwriter, and it created a new config file and ran fine, no problems with recent files, etc.    So problem fixed.  Thanks for your help.
I looked on ghostwriter but saw no place for donating, perhaps through paypal.  Did I miss it?


| 
| 
|  | 
ghostwriter

wereturtle

A distraction-free Markdown editor for the desktop
 |

 |

 |



Dale
    On Sunday, September 1, 2019, 05:37:46 PM CDT, wereturtle <notifications@github.com> wrote:  
 
 
ghostwrite'rs configuration is stored under ~/.config/ghostwriter

In particular, it's the ghostwriter.conf file within that directory that stores the file history. Within, you should see a section like this:
[FileHistory]
1\cursorPosition=4595
1\filePath=/home/YourUserId/Documents/file1.md
10\cursorPosition=78
10\filePath=/home/YourUserId/Documents/file2.md
11\cursorPosition=413
11\filePath=/home/YourUserId/Documents/file3.md

If you're not seeing that, and the file isn't updating between sessions, then I'd definitely would check that it's not read-only or owned by someone else.
