### ISSUE TITLE
Keyboard shortcuts displayed wrong on first use of menu bar

### ISSUE THREAD

**Issue by abenson** [wereturtle/ghostwriter#458]
Example:

![ghostwriter](https://user-images.githubusercontent.com/227317/64087773-148f2700-cd04-11e9-853f-a6dc0b6f63da.png)

It only happens on the first use of the menu bar. It's fine after that.

**Comment by wereturtle** [comment]
What platform/version/etc. are you on?  Also, is this with Flatpak, custom build, or PPA?

**Comment by wereturtle** [comment]
I did verify that this happens on Windows 10.  It's most likely a Qt bug, which I have no control over.  If you like, you can file a bug report at https://bugreports.qt.io/
