### ISSUE TITLE
Toggle soft wrap

### ISSUE THREAD

**Issue by Zack-83** [wereturtle/ghostwriter#459]
If the source code contains very long lines, they will be wrapped.

I know that good coding practice sets a limit to line length, but some special text parts such as tables are better visualised when wrapping is deactivated: scrolling with a horizontal slider is more comfortable.

So my request / suggestion (in the moment when you again have enough bandwidth): you could add a toggle to deactivate wrapping when needed.

Thank you for this very comfortable tool!

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
