### ISSUE TITLE
windows Platform's some issues

### ISSUE THREAD

**Issue by VKingi** [wereturtle/ghostwriter#460]
> Best md editor I've ever encountered, But can it support the following functions:
1. Syntax unsupported task list
2. File dragging is not supported
3. No file dir display

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
