### ISSUE TITLE
Devuan build fails

### ISSUE THREAD

**Issue by smeagolthellama** [wereturtle/ghostwriter#464]
OS: Linux, Devuan distro (debian fork without systemd)
Version: 1.7.4

I can run ghostwriter from flatpak, but that can't access my hunspell dictionaries (such as Hungarian). Therefore, I decided to build it myself. I installed all the dependencies, but after a successful qmake, make fails saying the following:
```
/usr/bin/ld: build/release/dictionary_provider_hunspell.o: in function `(anonymous namespace)::DictionaryHunspell::removeFromSession(QStringList const&)':
dictionary_provider_hunspell.cpp:(.text+0x11fe): undefined reference to `Hunspell::remove(char const*)'
/usr/bin/ld: build/release/dictionary_provider_hunspell.o: in function `(anonymous namespace)::DictionaryHunspell::addToSession(QStringList const&)':
dictionary_provider_hunspell.cpp:(.text+0x130e): undefined reference to `Hunspell::add(char const*)'
collect2: error: ld returned 1 exit status
```
I double checked, and libhunspell-dev is installed. Is there a c++-specific library that I need? Do I just have the wrong versions of some things? What's wrong????

A complete log of qmake and make output is coming as soon as it is finished.

**Comment by smeagolthellama** [comment]
[make.log](https://github.com/wereturtle/ghostwriter/files/3627942/make.log)

made by `make clean; make &> make.log`.

**Comment by Zatalyz** [comment]
I had the same error message on Debian Buster. I installed the "hunspell" package (not just hunspell-fr), recompiled and reinstalled ghostwriter. It worked. 

I don't know if the same thing can resolve your bug, but if it can help...

**Comment by smeagolthellama** [comment]
hunspell was already installed
