### ISSUE TITLE
Incorrect inline code rendering with pandoc

### ISSUE THREAD

**Issue by Kzer-Za** [wereturtle/ghostwriter#467]
When Pandoc or "Pandoc Multimarkdown" is selected as the renderer in "Preview options", there is a case when inline code is displayed incorrectly. See the picture, the line that starts with `"$@"`. If I select any other markdown renderer, it is displayed correctly. But I would rather continue using Pandoc because of its other features, if it can be fixed.

I use Linux, kernel 4.19, Ghostwriter  1.8.0-1, Pandoc  2.7.3-44.0.

![2019-10-03_13-11-14](https://user-images.githubusercontent.com/26425206/66121631-4edf3300-e5e6-11e9-9a33-77a3563855a0.png)

**Comment by wereturtle** [comment]
Hello,

Please report this issue at the [Pandoc issue tracker](https://github.com/jgm/pandoc), as this is an issue with Pandoc and not with ghostwriter.

Thanks!
