### ISSUE TITLE
[question/enhancement] In-document references (ankers)

### ISSUE THREAD

**Issue by theCalcaholic** [wereturtle/ghostwriter#469]
Is there an easy way to reference elements within the document (e.g. headings) with the markdown link syntax?

I'm picturing something like `[Chapter 1](#1._the_first_chapter_as_its_named_in_the_document)`

I know that I can do the same with inline html, but for a feature that is needed as frequently I'd prefer to have a markdown way :)

**Comment by wereturtle** [comment]
You might be able to do something like that with Pandoc as well.  Read up on its documentation and see!
