### ISSUE TITLE
Hide Markdown syntax

### ISSUE THREAD

**Issue by hfel** [wereturtle/ghostwriter#470]
Hi! It would be nice if it was possible to hide all Markdown symbols outside of the currently focused word, similarly to Typora for example. This has been requested before in #171 as well, however as that issue is from almost 3 years ago, I decided to open a new one. In case this request is rejected again, I would like to know why, as it would make the text significantly more aesthetic and less distracting to write.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

As for why (other than not having a lot of time), I just don't prefer Typora's way of doing things.  Might as well just use LibreOffice or Focuswriter with proper rich text editing at that point.  Plus, it would be a massive rewrite of code.  Typora works by having the editor be in a browser.  ghostwriter works by having the editor be actually plain text.  You have no idea how big of a rewrite that would be.
