### ISSUE TITLE
Building on MacOSX with Qt 5.13.2

### ISSUE THREAD

**Issue by katafrakt** [wereturtle/ghostwriter#477]
Hi! I just wanted to let you know that I was able to successfully build Ghostwriter (and so far it seems to work flawlessly) using "regular" Qt from Homebrew, without pinning to 5.5 version.

```
qt: stable 5.13.2 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.13.2 (9,861 files, 336.5MB) *
  Poured from bottle on 2019-11-04 at 11:50:30
```

So the process to build might be now as simple as:

```
brew install qt
brew link qt --force
cd /path/to/ghostwriter
qmake
make
```

**Comment by wereturtle** [comment]
The latest README.md file updates seem to have these new instructions that you suggest.  Thanks!
