### ISSUE TITLE
Sometimes ESC does not leave "accelerator mode"(?)

### ISSUE THREAD

**Issue by DarkTrick** [wereturtle/ghostwriter#486]
Platform (please complete the following information):

    Linux XUbuntu 19.10
    Desktop environment: xfce 4.14
    Input system: ibus 1.5.21, using ibus-anthy

ghostwriter installation (please complete the following information):

    ghostwriter version: 1.7.4
    installation type: deb file from official repos

**Describe the bug**
Pressing Alt,F would open the file menu.
Pressing Alt,F,ESC,E would open the edit menu.
Pressing Alt,F,ESC,ESC would leave the "accelerator mode" (I hope that's the correct name).

Sometimes it happens, that I'm stuck in the accelerator mode. No matter how much I click ESC, I cannot leave it. It's necessary click with the mouse inside the text window.

**To Reproduce** 
I can't tell how to surely reproduce it. I could never get this behaviour on purpose. I know this makes it hard to fix.

**Additional Information **
It often happens during a lot of app-switching with ALT+Tab.
I actually don't purposely use the accelerator mode to enter menus.

**Comment by wereturtle** [comment]
Not getting this in KDE with version 1.8.0.  Can you try upgrading to 1.8.0 from the PPA, and let me know if the error still occurs?

**Comment by DarkTrick** [comment]
Seems solved on my machine :)
Thank you!
