### ISSUE TITLE
Github flavored markdown 

### ISSUE THREAD

**Issue by gsbhasin123** [wereturtle/ghostwriter#487]
Does this exist, if so  how can I enable it on Ubuntu?

**Comment by gsbhasin123** [comment]
To clarify, I can export in it after getting PanDoc, but codeblocks are not colored and I can't use emojis

**Comment by wereturtle** [comment]
I'm afraid emoji's and whatnot don't work, since they aren't part of the Markdown processors themselves.

**Comment by gsbhasin123** [comment]
That sucks :(
Are highlighted codeblocks supported?
