### ISSUE TITLE
list only works after blank rule if preceded by text

### ISSUE THREAD

**Issue by cdbdev** [wereturtle/ghostwriter#490]
OS: Windows 10
Ghostwriter version: 1.8.0 (type full install)

Bug description:
If I create a list immediately on the next line, the list is not generated. 
So for example if I type:

Test list:
- val
- val2

The list will not be generated. 

But if I type (with blank line between 'Test list' and '-val'):

Test list:

- val
- val2

It does work.

Reproducing:
Test list:
- val
- val2

Expected behavior:
The list works even without a blank rule.

**Comment by wereturtle** [comment]
This is an issue with the Markdown processor you are using.  (I presume Sundown?)  I am not the maintainer of any of the Markdown processors that are compatible with ghostwriter.  Perhaps you can try installing Pandoc or MultiMarkdown instead?  They will most likely have the behavior you are expecting. (Remember to add their locations to your system PATH environment variable!)
