### ISSUE TITLE
can not browse to folders starting with a dot when opening file

### ISSUE THREAD

**Issue by richo67** [wereturtle/ghostwriter#491]
**Platform (please complete the following information):**
 - Manjaro 19.0
 - GNOME 3.34.2

**ghostwriter installation (please complete the following information):**
 - ghostwriter version 1.8.1
 - build from AUR http://aur.archlinux.org/packages/ghostwriter

**Describe the bug**
When Opening the file I can not see the folders which starts with dot in their name, like for example '.data'

**Comment by abenson** [comment]
What happens if you right click in the dialog and choose "Show hidden files"?

**Comment by richo67** [comment]
> What happens if you right click in the dialog and choose "Show hidden files"?

Then it shows ;-) Thank I was looking everywhere, but not there, is this QT way?

**Comment by abenson** [comment]
Yeah, it's just the standard Qt dialogs
