### ISSUE TITLE
What does "Style Sheets" do and how can I use them?

### ISSUE THREAD

**Issue by whit-colm** [wereturtle/ghostwriter#492]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

Hello,

I'm sorry to clog up your issues page but  I don't see any documentation regarding what I'm looking at. In the `settings` menu there is an option for custom style sheets, what does that do and is there a base template I can modify? Thanks!

I'm using EndevourOS Linux (5.5.8-arch1-1) running KDE 5.67.0 / Plasma 5.18.2 and have installed Ghostwriter 1.8.1 via the Arch AUR.

**Comment by wereturtle** [comment]
It's referring to cascading style sheets (CSS).  If you want to modify the default GitHub ones, they're available in this git repo under the `resources` folder.  The two files are `github.css` and `github-dark.css`.  You can also find more on the Internet, for example, from Wordpress, if you happen to like any Wordpress CSS themes.

**Comment by NoHara42** [comment]
I just recieved this error while trying to imprort my own stylesheet.
js: Not allowed to load local resource: file:///home/nohara/.config/ghostwriter/stylesheets/sepia.css

I used the github template and changed the background. I don't see anything wrong with my css.
Where should I be placing the style file? 
I'm using ubuntu 20.04

Thanks

**Comment by felipehw** [comment]
@NoHara42 

Did you resolve this problem?
I'm passing through the same problem in a Fedora 32 + Flatpak setup.

**Comment by NoHara42** [comment]
Unfortunately not no.

**Comment by abenson** [comment]
I think this might be an issue with flatpak permissions. You might need to
allow access to certain paths, but I'm not familiar with flatpak and how to
do it.

**Comment by felipehw** [comment]
@abenson 
The permissions, at least in my case, were correct. After a few minutes, it begin to work correctly. I don't know why.
