### ISSUE TITLE
Ghostwriter isn't detecting Multimarkdown installation

### ISSUE THREAD

**Issue by masterrite** [wereturtle/ghostwriter#499]
I installed Multimarkdown 6.5.1 and restarted my computer, but I can't find multimarkdown in the export option. There's only Pandoc multimarkdown. Can anyone help? Thanks

**Comment by masterrite** [comment]
Would it be possible to assign the location of a markdown exporter manually? I've tried everything I know of and I can't make Ghostwriter find my installation of Multimarkdown anywhere. I have another computer with the same setup and strangely I can get Multimarkdown at the bottom of the export list in addition to Pandoc MMD.
 
I'm on Windows 10, by the way.

![Snipaste_2020-03-31_15-30-56](https://user-images.githubusercontent.com/20837366/78076964-b3483880-7364-11ea-9738-a67dc5ce2f6e.png)

**Comment by masterrite** [comment]
I fixed the problem by moving multimarkdown.exe out of multimarkdown 6.5.1/bin folder to the multimarkdown folder. I don't know why Ghostwriter is unable to detect it earlier. It'd be great to be able to manually define the paths of different markdown converters, since I'm guessing scanning subfolders in Program Files would take too long.

**Comment by wereturtle** [comment]
You have to set the PATH environment variable to include the path to multimarkdown.  That's the secret.
