### ISSUE TITLE
Feature request: text padding configurable

### ISSUE THREAD

**Issue by gsbhasin123** [wereturtle/ghostwriter#504]
currently it looks like
![image](https://user-images.githubusercontent.com/48339289/79793973-55c15f00-8306-11ea-94c8-be07f1beb32c.png)

I'm saying that the padding on left and right should be configurable - in my case I want it to use more of my screen space :P

**Comment by wereturtle** [comment]
It already is configurable.  Go to Settings -> Preferences.  Select the Editor tab.  Then under the Styling Section you will see an Editor Width setting with a combo box.  Pick your favorite width, and there you go!  :)

**Comment by gsbhasin123** [comment]
Oh. :) thanks!
