### ISSUE TITLE
Focus mode doesn't vertical center align the focused text

### ISSUE THREAD

**Issue by felipehw** [wereturtle/ghostwriter#506]
Hi.
I don' t know if this is by design or a bug.
In the [Apostrophe editor](https://gitlab.gnome.org/somas/apostrophe), the Focus mode produces a centered vertical alignment of the text beside the highlight. This is a very comfortable and focused setup.
But in the Ghostwriter editor, at least in my machine (Linux + Flatpak), the Focus mode only gives me a highlight without the centered vertical alignment of the text.

**Platform:** Fedora 31 + Flatpak + Gnome.

![Screenshot from 2020-04-27 12-09-45](https://user-images.githubusercontent.com/4523897/80388676-8cf0bc80-8880-11ea-9814-c2ddc7cfaef2.png)

**Comment by wereturtle** [comment]
I'm afraid this is a Qt issue.  It just doesn't allow for that. Which is too bad, because I agree it's a really nice feature to have.  :(
