### ISSUE TITLE
Multi level lists not properly rendered in Ghostwriter 1.8.1

### ISSUE THREAD

**Issue by laggarcia** [wereturtle/ghostwriter#507]
I am using Ghostwriter 1.8.1 on Fedora 32 with GNOME3  on Wayland installed from the PRM package provided by the distro: ghostwriter-1.8.1-1.fc32.x86_64).

**Describe the bug:**

When I type a multi level list, only level 1 and level 2 are properly rendered in the preview pane.

A code like:

* level 1
  * level 2
    * level 3

is being rendered in the preview pane as:

* level 1
  * level 2
  * level 3

**Expected behavior**

The multilevel list should be rendered properly.

Notice: If I use tabs to ident the multiple leves instead of spaces, the editor works as expected.

**Comment by wereturtle** [comment]
How many spaces are you using to indent?  You need at least four for each level.  Also, which Markdown processor are you using?  Is it Sundown?  Pandoc?  Or...?
