### ISSUE TITLE
Possibility of commenting / review of write up 

### ISSUE THREAD

**Issue by himanshu0310** [wereturtle/ghostwriter#511]
The Ghostwriter is really all that I would need to write my draft for paper and other things. 
I am a user for the windows version. 
Since I can use ghostwriter for long text writeup with integration of images and links, I really try to use it as my first draft creating for all the papers and articles that I write. But at times the draft also need minor corrections, for that purpose, I was thinking if there could be a feature for commenting or accepting the changes. In line to the review setup. 
Of course one way is to use the strikeout and write the changes in italics, but I interested to know if there is a better approach.

**Comment by abenson** [comment]
I do this using git. Using something like a private GitHub or other management thing, pull requests can be commented on and edited before merged in. 

Ghostwriter should just focus on being a great editor.

**Comment by himanshu0310** [comment]
Well in principle I can agree to that. 
I would also like to see it as being a great editor.

**Comment by abenson** [comment]
One thing I'd like PandocMarkdown to add is Fountain's comments; Inline comments are surrounded like [[ this ]]  and won't be rendered. [Example](https://fountain.io/syntax#section-notes)

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
