### ISSUE TITLE
Ghostwriter does not follow the same theme as Gnome

### ISSUE THREAD

**Issue by renaldofreire** [wereturtle/ghostwriter#512]
**Platform:**
 - Gnome Fedora 32

**ghostwriter installation**
v1.8.1

**Describe the bug**
I'm using the Flat-Remix-GTK-Blue-Dark theme, only Ghostwriter doesn't follow the same pattern as the rest of the system. Is there a way to fix this?

**To Reproduce**
Open application.

**Expected behavior**
May the Ghostwriter have the same theme as Gnome.

**Screenshots**
[![error-qt-gkt.png](https://i.postimg.cc/GhPDSysn/error-qt-gkt.png)](https://postimg.cc/F7R1Y1ZT)

**Comment by wereturtle** [comment]
I'm going to guess that all your Qt apps behave this way?  If so, you'll have to configure your desktop environment to theme Qt apps with the GTK theme.  The Arch Linux wiki page [here](https://wiki.archlinux.org/index.php/Uniform_Look_for_QT_and_GTK_Applications#Theme_engines) should have more information.
