### ISSUE TITLE
Why is my epub entitled UNTITLED?

### ISSUE THREAD

**Issue by JohnBlood** [wereturtle/ghostwriter#513]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Fedora 32
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: GNOME

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 1.8.1
 - If Windows, installation type [e.g., portable or full install]:
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: Fedora repo

**Describe the bug**

When I export my Markdown file to epub (using pandoc), it says UNTITLED above the table of contents.

**To Reproduce**
1. Go to Export
2. Select either epub version
3. Export
4. Open resulting file in ebook reader

**Expected behavior**
I thought that ghostwriter would use either the filename or the first occurance of Header 1 as the title of the ebook

**Screenshots**
![Screenshot from 2020-05-17 23-41-33](https://user-images.githubusercontent.com/5157847/82172418-19970500-9898-11ea-9a7a-8c318fa0fd68.png)

Screenshot is a test ebook opened in calibre.

**Additional context**

**Comment by abenson** [comment]
Things like title are set in the metadata block.

[See Pandoc](https://pandoc.org/MANUAL.html#creating-epubs-with-pandoc)

**Comment by JohnBlood** [comment]
It's been a while since I created an epub with ghostwriter, but I don't think I ever had this issue before.

**Comment by JohnBlood** [comment]
I just discovered a workaround. If you start the first line of your document with a `%`, pandoc will see that as the Title. In my example, I put `% My Man Jeeves" at the top of my document and it worked. :smiley:
