### ISSUE TITLE
Multiple SpellCheck dictionnaries

### ISSUE THREAD

**Issue by CyberFoxar** [wereturtle/ghostwriter#514]
Hello,
This is more of a feature request than an issue.

Would it be possible to have multiple spell check dictionnaries active at the same time ? 

My use case is that I write a lot of text with mixed french and english in them, I'd love to be able to spell check both at the same time.

I am aware of #72 , where it has been said that quick language dictinnary switch would be difficult. My request is slightly different and I'd love to know if the stance on this question has changed or not.

I am also aware of the rules on request features. I an merely enquering if such a feature has bveen considered.

Thanks !

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
