### ISSUE TITLE
How to add an HTML template

### ISSUE THREAD

**Issue by pcav** [wereturtle/ghostwriter#515]
Thanks for this tool. I could not find a way of using an HTML template to configure the output (only CSS). Is this a current limitation of `ghostwriter`, or am I missing something here?
Thanks, and sorry if inappropriate here.

**Comment by abenson** [comment]
What do you mean by template?

**Comment by pcav** [comment]
The idea is to make users able to compile as HTML using a template like jinja https://jinja.palletsprojects.com/en/2.11.x/templates/
The alternative approach of directly inserting HTML fragments into the md file also should work fine, it's just more cumbersome, so feel free to drop this suggestion and close this ticket.
Thanks.

**Comment by pcav** [comment]
See e.g. https://github.com/btbytes/mdninja

**Comment by wereturtle** [comment]
Sorry, ghostwriter doesn't do that.
