### ISSUE TITLE
breaking space are removed.

### ISSUE THREAD

**Issue by cClaude** [wereturtle/ghostwriter#516]
Based on [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS:
```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"
```

 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]:
```bash
$ cinnamon --version
Cinnamon 4.4.8
```

**ghostwriter installation (please complete the following information):**
 - ghostwriter version : `ghostwriter v1.8.1`
 - If Linux, installation type :
```bash
$ cat /etc/apt/sources.list.d/wereturtle-ppa-bionic.list 
deb http://ppa.launchpad.net/wereturtle/ppa/ubuntu bionic main
deb-src http://ppa.launchpad.net/wereturtle/ppa/ubuntu bionic main
```

**Describe the bug**

**To Reproduce**

Run this, and just use save in ghostwriter:

```bash
$ printf 'space non-breaking\u00a0space' >test.md ; hexdump test.md ; ghostwriter test.md ; hexdump test.md 
```

Initial dump
```
0000000 7073 6361 2065 6f6e 2d6e 7262 6165 696b
0000010 676e a0c2 7073 6361 0065               
0000019
```

Final dump
```
0000000 7073 6361 2065 6f6e 2d6e 7262 6165 696b
0000010 676e 7320 6170 6563                    
0000018
```

`a0c2` have disappear.

**Expected behavior**

`a0c2` should be still there..

**Screenshots**
not applicable

**Additional context**
I have the same issue if file is properly UTF-8 or UTF-16 encoded.

Typically using:

``bash
libreoffice --writer test.md
```

**Comment by wereturtle** [comment]
It looks like it's an issue with Qt, which I can't help.  If you're good at programming, you may wish to try reproducing the bug with any of the following Qt classes:

* QTextStream
* QPlainTextEdit
* QTextDocument

If you can reproduce it with one of these, then I'd suggest filing a bug with the Qt devs (www.qt.io).
