### ISSUE TITLE
Repository for themes

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#52]
I have created a small repository for themes. Three I created myself, the others I plagiarised from `focuswriter`.

Everyone is invited to help document the theme file and to add new themes here https://github.com/jggouvea/ghostwriter-themes

**Comment by wereturtle** [comment]
Thank you very much!  I'll be sure to reference your theme repository in the README file next time I update it, as well as in the wiki when I get around to documentinthatg the theme file format.

**Comment by wereturtle** [comment]
I've referenced your theme repository in both the README file and in a wiki page.  Thanks again!

**Comment by jggouvea** [comment]
Thank you very much. I will try to create more themes.
