### ISSUE TITLE
Feature: open linked .md files in Ghostwriter, not a preview program

### ISSUE THREAD

**Issue by internationils** [wereturtle/ghostwriter#523]
I have files that often link to other markdown files and contain something like the following:
```
* [Index](00_INDEX.md)
* [Blogpost Guidelines](10_blogpost_guidelines.md)
```
When clicking on the link in the HTML preview, it opens a previewer. I would like it to open the .md files in ghostwriter for editing instead. If you do not want to make this default, then at least an option would be great.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
