### ISSUE TITLE
[Bug] master won't compile anymore

### ISSUE THREAD

**Issue by fushinari** [wereturtle/ghostwriter#524]
**Platform (please complete the following information):**
 - OS and version: Arch Linux (latest)
 - Desktop Environment: Plasma 5.19

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: `master`
 - Installation type: `ghostwriter-git` from the AUR

**Describe the bug**
`master` does not compile with gcc anymore since 63f1f27. 
```
/usr/bin/ld: build/release/dictionary_provider_hunspell.o: in function `(anonymous namespace)::DictionaryHunspell::removeFromSession(QStringLt const&)':
dictionary_provider_hunspell.cpp:(.text+0xc37): undefined reference to `Hunspell::remove(char const*)'
/usr/bin/ld: build/release/dictionary_provider_hunspell.o: in function `(anonymous namespace)::DictionaryHunspell::addToSession(QStringList cst&)':
dictionary_provider_hunspell.cpp:(.text+0xd27): undefined reference to `Hunspell::add(char const*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:754: build/release/ghostwriter] Error 1
```

**To Reproduce**
1. Try to compile `master` with gcc.

**Expected behavior**
It compiles and works as expected.

**Comment by wereturtle** [comment]
It looks like it's trying to call the Hunspell library, but it isn't there.  Do you have hunspell-dev (or whatever it is on Arch) installed?

**Comment by abenson** [comment]
I'm having the same issue on Void. It happened either when hunspell updated to 1.7 or disabled gcc4 compat. I assume the earlier?

**Comment by fushinari** [comment]
> It looks like it's trying to call the Hunspell library, but it isn't there. Do you have hunspell-dev (or whatever it is on Arch) installed?

Arch does not split the package like other distros do, so it's already included in the `hunspell` package.

@abenson hunspell was updated to 1.7 in 2018, so that can't be it.

**Comment by abenson** [comment]
I figured it out. It's using the headers from the vendered hunspell (`src/spelling/hunspell/hunspell.cxx`) but the system libraries, which have different interfaces.

The vendered version:

```
int Hunspell::add(const char * word)
int Hunspell::remove(const char * word)
```

But the system version uses `std::string`:

```
  int add(const std::string& word);
  int remove(const std::string& word);
```

**Comment by fushinari** [comment]
That was fast! Thanks! @abenson @wereturtle
