### ISSUE TITLE
[Feature Request]: Activity time graph

### ISSUE THREAD

**Issue by iuvbio** [wereturtle/ghostwriter#525]
I really like the session statistics feature of ghostwriter and I would like to take them a step further. The idea is to plot activity against time, for example, words written per minute for the last hour or so. I'm not sure how feasible it would be to include that in the HUD itself, since I'm sure the application should stay as lightweight as possible, but it would be cool if there was the possibility to export that data in some way. Is this possible at all?

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
