### ISSUE TITLE
Feature request: Typewriter mode

### ISSUE THREAD

**Issue by karanprime** [wereturtle/ghostwriter#531]
I like the focus mode implementation. A typewriter mode would be even better for focusing on current sentence. 
How it works: The current sentence stays at the centre of the screen, and scrolling up and down moves the page up and down, with the current sentence always in the centre. 

I saw that you do not have the bandwidth to keep adding new features, and I would be happy to contribute but don't know where to start. Some guidance would be great.

References:
* [Ulysses Typewriter Mode](https://ulysses.app/tutorials/typewriter-mode)
* [Typora Typewriter Mode](https://support.typora.io/Focus-and-Typewriter-Mode/)
* iA writer also has a typewriter mode, couldn't find official documentation

**Comment by abenson** [comment]
Doesn't the current focus mode already do this? In Settings->Preferences, on the Editor tab, you can choose the style of of Focus mode you want. Three of them are various types of highlighting (word, paragraph, and line), and the fourth disables highlighting, but they all four (at least for me) keep the current focused line as the center.

**Comment by karanprime** [comment]
I apologize I didn't realize it then. Thank you for your prompt response!
