### ISSUE TITLE
no spell checking, no dictionaries, after installation on ubuntu

### ISSUE THREAD

**Issue by manuelcaeiro** [wereturtle/ghostwriter#535]
Installed ghostwriter on Lubuntu (server) following strictly your set of instructions.
Settings -> Preferences -> Spell Check -> Dictionary is empty.
Cannot find any information on how to add a dictionary to the program.

**Comment by abenson** [comment]
You need to make sure a hunspell dictionary is installed. If you're looking for US, on Ubuntu the package is `hunspell-en-us`

**Comment by manuelcaeiro** [comment]
Solved. Thanks.
