### ISSUE TITLE
Mardown File Extensions Not Visible in Open Dialog

### ISSUE THREAD

**Issue by nkosi23** [wereturtle/ghostwriter#536]
**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Ubuntu 19.10
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: XCFE

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 1.7.4
 - If Windows, installation type [e.g., portable or full install]:
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: default repository

**Describe the bug**
First of all, thanks for the great work! Not all markdown files are being detected in the open file dialog. [There is consensus](https://superuser.com/questions/249436/file-extension-for-markdown-files) on the fact that the official markdown file extensions are the following:
- .markdown
- .mdown
- .mkdn
- .md
- .mkd
- .mdwn
- .mdtxt
- .mdtext
- .text
- .Rmd

The .text extension is particularly important to support, [even the original creator of Markdown](https://daringfireball.net/projects/markdown/) has been using it, and we use it exclusively a lot in our organization. All files having a markdown extension should be able to be opened without having to go through hoops. Github supports only a subset, but a markdown editor should support all standard file extensions since people edit markdown files in various contexts far beyond Github usage.

The 'Save As' dialog is also affected.

**To Reproduce**
1. Go to the menu 'File' > Open and open a folder where a markdown file having the right extension is located.

**Expected behavior**
Files having the a markdown extension should visible.

**Screenshots**

**Additional context**

**Comment by abenson** [comment]
I've thought about PRing a fix to add these as well as .fountain (a Markdown subset for writing screenplays)
