### ISSUE TITLE
Accented unicode characters

### ISSUE THREAD

**Issue by TanyaMurphy** [wereturtle/ghostwriter#54]
Accented characters are not displaying properly after reopening a file. For example, Québec becomes QuÃ©bec.

I am working with Ghostwriter v.1.2.2 (Qt v. 5.5.0) on Windows 10

**Comment by wereturtle** [comment]
Hi Tanya,

This issue sounds familiar.  The problem you are experiencing may have been fixed on issue #29.  Would you mind trying out the latest version and seeing if that fixes your issue?

Thanks!

**Comment by wereturtle** [comment]
I have confirmed that this is a duplicate of issue #29, which was fixed on a newer version of ghostwriter.  Please download the latest version for this fix.  Thanks!
