### ISSUE TITLE
Search dialog doesn't work in the preview mode

### ISSUE THREAD

**Issue by felipehw** [wereturtle/ghostwriter#541]
If I'm using exclusively the "preview mode" ... I can't search through the text using the "search" dialog.
This is a problem because many times I want to find results for words like "killer" and I have occurrences like `kill**er**` that are impossible to locate.

    Ghostwriter 1.8.0 (Flatpak version).
    Fedora 32 + Wayland + Gnome 3.36.2

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
