### ISSUE TITLE
Key Bindings for Spell Check

### ISSUE THREAD

**Issue by nxl4** [wereturtle/ghostwriter#543]
Could key bindings be added to the Spell Check function? Currently, the function has to be invoked from the menu. Perhaps, altering the code to something like this could be acceptable?

```cpp
editMenu->addAction(tr("&Spell check"), editor, SLOT(runSpellChecker()), QKeySequence("SHIFT+CTRL+?"));
```

**Comment by faldor20** [comment]
I would be a huge fan of this.
Though i would prefer ctrl+space. That is the shortcut used to bring up auto-completeions in many popular code editors.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
