### ISSUE TITLE
Kindly provide Fountain scriptwriting/screenplay writing options in this

### ISSUE THREAD

**Issue by rokfrog** [wereturtle/ghostwriter#544]
Hi
I'm using old legacy machine and can't install many software and needed something like Ghostwriter which includes fountain script writing feature or something which supports it. Kindly include the feature to support fountain. I'm using Peppermint 10 OS

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
