### ISSUE TITLE
[Enhancement] Start typewriter centered

### ISSUE THREAD

**Issue by dagdrommer** [wereturtle/ghostwriter#545]
Hey,
first and formest: i appreciate this great tool that I use daily and I would like to contribute an idea for enhancement:

When opening a new Document and starting the distraction free mode, with activated Typewriter-mode, the cursor starts on top of the empty document. While writing the cursor continuously moves down until it reached the center of the document where it stays in the actual typewriter position. I would suggest that the cursor right away starts in that centered position, when creating a new document, just as it is with a actual typewriter.

Btw, I use ghostwriter on Arch Linux with KDE Plasma 5 Desktop :see_no_evil:

**Comment by wereturtle** [comment]
I'm afraid with Qt it can't be done.  At least, I haven't found a way to do it.  I agree it would be nice to have!  If you ever figure out how, please do let me know the secret.
