### ISSUE TITLE
Local images not showing in Linux

### ISSUE THREAD

**Issue by pintert3** [wereturtle/ghostwriter#546]
- Platform : ArchLinux, i3wm
- ghostwriter Installation: v1.8.1, pacman

Local links to images do not show in the html preview, but external urls do.:
![](https://i.ibb.co/FgqWXR3/2020-10-10-00-57.png)
I've tried using `file:///...` and simply using it plain like: `/home/...` , but both don't seem to work.

**Comment by abenson** [comment]
What about using bare relative local paths, i.e `~/Pictures/football/960.jpg` (without `file://`)

**Comment by pintert3** [comment]
It still doesn't show

**Comment by wereturtle** [comment]
I can't replicate this issue.  I'm guessing it's something to do with Arch.

**Comment by Purgeme** [comment]
The issue I believe is not that the images don't load at all but that it requires the markdown file to be saved for the local images to be loaded. After saving the markdown file, the local images load up just fine.
