### ISSUE TITLE
CMake conversion

### ISSUE THREAD

**Issue by ferdnyc** [wereturtle/ghostwriter#547]
@wereturtle 

Just saw the major update, looking forward to testing it out!

Regarding the roadmap, and specifically the CMake-porting item: I took a look at the current qmake `.pro` file, I don't expect it'll be too much trouble to rewrite as a `CMakeLists.txt`. I've amassed a good deal of experience with Qt5 CMake over the past few years, and would be happy to help out with that if you'd like.

Let me know if you're interested, and I'll start working on a PR to replace the qmake build with an equivalent CMake setup.

**Comment by wereturtle** [comment]
Sorry for the late reply.  Yes, I would very much be interested!  But just a heads up, Qt 6 will be coming out Soon (TM), and I'm sure instructions for supporting cmake for both Qt 5 and Qt 6 will be forthcoming, which is why I have been holding off until they do.  Even if you can give me a head start, though, that would be much appreciated.  :)

**Comment by ferdnyc** [comment]
Be happy to! The situation with CMake and Qt 6 is mostly resolved; Kai Köhne from Kitware (the CMake developers) posted [this guidance](https://www.qt.io/blog/versionless-cmake-targets-qt-5.15) via the Qt blog way back in April, believe it or not. 

(Primarily, if you only have to care about supporting Qt 5.15 and Qt 6, and you can require building with CMake 3.17 or later, there are versionless targets available that allow `CMakeFiles.txt` configurations to support both Qt 5[.15+] and Qt 6 with only one line of difference between the two.

Assuming those bleeding-edge restrictions are unrealistic (I know they are for our projects), supporting Qt 6 along with Qt 5 will mostly just involve changing the names of dependency targets, so e.g `Qt5::Gui` becomes `Qt6::Gui`. (It could be just `Qt::Gui`, iff all the restrictions above could be applied.)

Even the major-versioned targets aren't a big deal as long as the targets are managed all in one place (I don't see why they wouldn't be), we can just wrap an `if()` around that bit and write Qt5 and Qt6 versions.

Target names are also composable from variables in CMake, so it's feasible to code it like:
```cmake
find_package(Qt5 5.15 COMPONENTS Gui Widgets ...)
find_package(Qt6 whatever...)
if(${Qt5_FOUND} OR ${Qt6_FOUND})
  set(QT_PFX Qt)
else()
   find_package(Qt5 COMPONENTS Gui Widgets ...)
   set(QT_PFX Qt5)
endif()
foreach(_comp IN Gui Widgets ...)
  list(QT_TARGETS APPEND ${QT_PFX}::${_comp})
endforeach()
```
And at the end, `${QT_TARGETS}` will contain, as appropriate, either:
* `Qt::Gui`, `Qt::Widgets`, ...
* `Qt5::Gui`, `Qt5::Widgets`, ...

There'd need to be a bit more error checking in there, but that's the gist of it. I'll work on getting a PR together so you can take a look.

**Comment by ferdnyc** [comment]
The bigger concern, from a Qt6 perspective, is that none of the Qt6 preview builds so far have included QtWebEngine.

QtWebEngine has always been separate from the Qt distribution itself, but in Qt5 it's listed as an optional component you can install right from the Qt installer. With Qt6 it's not there:

![image](https://user-images.githubusercontent.com/538020/100693939-f0cded00-335b-11eb-9e6c-aaa2175b89dc.png)


I don't know if that means it's "coming soon", or if they're splitting it out from the main Qt distribution and deprecating it, just as they did with QtWebKit before it. That's not necessarily the end of the world — QtWebKit is _still_ maintained by third-party volunteers, in fact — it  would just complicate the Qt 6 situation by introducing a new external dependency.

**Comment by ferdnyc** [comment]
A KDAB rep also revealed in a Qt Desktop Days presentation back in September that, while Qt is switching over to CMake _internally_ for Qt 6, ["qmake still supported for end user applications"](https://www.qtdesktopdays.com/wp-content/uploads/2020/09/keynote.pdf#page=8) (slide deck PDF link).

So in theory this conversion isn't a requirement. Personally I still feel it's a good idea, but it is technically optional.

That same slide also acknowledges the missing modules in Qt 6, and says that most of them should be coming in Qt 6.1 or 6.2. So, the WebEngine dependency might simply mean that ghostwriter isn't compatible with Qt 6.0, but requires either Qt 5.8+ or Qt 6.1+/6.2+.
