### ISSUE TITLE
 Minor bug: "Export failed: --smart/-S has been removed."

### ISSUE THREAD

**Issue by PrSunflower** [wereturtle/ghostwriter#550]
**Platform:**
 - Debian 10 Buster (64-bit) with GNOME

**ghostwriter installation:**
 - ghostwriter version: v1.8.1, private build from source code

**System:**
- Toshiba Satellite S50-B
- Intel Core i5 5200U
- Intel HD Graphics 5500 (Broadwell GT2)
- RAM: 8GB

### Description

I opened ghostwriter and while the app was usable there was no preview. Error message `Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.`

![wereturtle1](https://user-images.githubusercontent.com/59576952/98238950-7b8f1800-1f67-11eb-8242-adbf2158ae25.png)

<br>

### Solution

Closing and reopening ghostwriter solves the problem, the preview works correctly:

![wereturtle2](https://user-images.githubusercontent.com/59576952/98239079-b4c78800-1f67-11eb-8c93-efde3a6e6e15.png)

<br>

### More info: issue happened any times on Windows

While this is the first time I encouter this bug on GNU/Linux, I already encoutered it many many times on my Windows machine. I had created an issue on [ghostwriter's Windows repository](https://github.com/michelolvera/vs-ghostwriter/issues/16) as I thought it was a Windows-only bug.

### More info: other issues describing the same problem

#260 and #488 seem to describe the same problem.

**Comment by PrSunflower** [comment]
### Additional info

20 Nov 2020: The issue happened again. `Reload from disk` does not solve the problem, closing and reopening Ghostwriter fixes the problem.

**Comment by wereturtle** [comment]
Since I cannot replicate the issue, I'm going to close this report.  If you ever figure out more information that would help me to replicate the issue, please feel free to update this issue or open a new one.  Thanks!

**Comment by PrSunflower** [comment]
Understood! Thank YOU for having developed this wonderful software.

**Comment by Tau5** [comment]
I had the same issue now and restarting ghostwrite does in fact fix the issue

**Comment by PrSunflower** [comment]
@Tau5 What are your system specs?

[I was using the Windows version of Ghostwriter on a DELL Latitude laptop](https://github.com/michelolvera/vs-ghostwriter/issues/16) and I got the same error.

**Comment by Tau5** [comment]
I was using Arch Linux (EndeavourOS), I installed it trough the AUR package ghostwriter-git

**Comment by PrSunflower** [comment]
Hi @wereturtle . I have encountered the error again and tried to export to HTML to see if it gives more details. But no, it gives approximately the same message:

![image](https://user-images.githubusercontent.com/59576952/103170962-d1928480-4861-11eb-912b-5add3ea2b595.png)

I don't think I'll ever have more details on the issue. Does Ghostwriter have a log that I can post here?
