### ISSUE TITLE
Auto-matching character pairs: Possible to add/edit?

### ISSUE THREAD

**Issue by Moonbase59** [wereturtle/ghostwriter#553]
Is it possible to add/edit the auto-matching characters?

Reason: I’m writing German texts and need to use guillemets instead of the simple apostrophes, like in direct speech:

»These are what we call ›guillemets‹,« she said.

It might also be nice to add the ›normal‹ German apostrophes, like in:

„These are what we call ‚quote marks‘,“ she said.

So it would be great if I could add these pairs:
```
» «
› ‹
„ “
‚ ‘
```

Same thoughts apply to texts in other languages, for instance the French use the guillemets the other way round:
«This is direct speech.»

Or the English use:
“These are English ‘quotes’.”

It would be a great addition to Ghostwriter if the pairs could be specified somehwere, like in `ghostwriter.conf`, and the dialog to switch them on/off be created automatically, from the defined pairs.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
