### ISSUE TITLE
Tildes and other special characters render incorrectly on the sidebar outline

### ISSUE THREAD

**Issue by Tau5** [wereturtle/ghostwriter#554]
**Platform**
 - OS and version: Arch Linux (EndevaourOS) 5.9.8-arch1-1
 - If Linux, Desktop Environment: KDE Plasma 5.20.3

**ghostwriter installation**
 - ghostwriter version [Help->About in menu bar]: v2.0.0-rc
 - If Linux, installation type: AUR [ghostwriter-git](https://aur.archlinux.org/packages/ghostwriter-git/)

**Describe the bug**
Outilne elements with special characters like tildes (áè) and other characters (ñ¡ºª) are replaced with �

**To Reproduce**
1. Create a new file
2. Create a header which contains a special character described
3. Open or see the outline on the sidebar

**Expected behavior**
Special characters on the outline should be rendered properly

**Screenshots**
![Screenshot_20201127_115537](https://user-images.githubusercontent.com/28908976/100441945-8c830300-30a7-11eb-9d33-c392836c9f46.png)

**Additional context**
Some icons on the sidebar also don't render properly so it's possible it's due to a problem with the fonts

**Comment by dagdrommer** [comment]
Hello everyone. Unfortunately it happens to me to have the same problem.

I've tried it on the following Linux distributions:

- Arch Linux (official repositories)
- OpenSuse Tumbleweed  (official repositories)

Both run KDE Plasma 5.21.5 and QT 5.15.2

I also guess it might be a font problem, as both Linux distribution render different symbols. (My Arch looks exactly the same as in the picture of @Tau5 .) Further I also have the missing symbols for Toggle HTML, Hemingway-Mode and distraction free.

Thank you for your work.

**Comment by wereturtle** [comment]
@dagdrommer Please see if 2.0.2 is working for you. That's where the fix has been incorporated.  Let me know if you are still having any issues.
