### ISSUE TITLE
macOS Build

### ISSUE THREAD

**Issue by BNolet** [wereturtle/ghostwriter#555]
I've packaged the master branch at time of writing using big sur. It runs from the terminal but not from the GUI. 

See here for the app: https://github.com/BNolet/ghostwriter/releases/tag/v2.0-alpha1

Would be willing to help troubleshoot. Here's the crash report:

https://gist.githubusercontent.com/BNolet/a43d6cd2adfc456779e467bcb4ff5ef8/raw/f95ed7d67b28acc7a2945a7528ff3a9a61b263aa/crashreport.txt

**Comment by BNolet** [comment]
To add onto this, I get the error `Could not find QtWebEngineProcess` when doubleclicking the executable file that we symlink to be able to run the binary from the command line.

**Comment by BNolet** [comment]
And here's one which came from building 1.8.1: 
![image](https://user-images.githubusercontent.com/10198484/100666693-6370a580-3327-11eb-8a71-ab0535b82093.png)

Seem to be the same error, but with a little bit of elaboration?

**Comment by BNolet** [comment]
So I've narrowed building 1.8.1 down: 

switch the `QtWebEngine::initialize()` and `QApplication app(argc, argv)` lines around. Then we get to the same place as the error of launching ghostwriter 2.0.0-rc

To fix this error, I had to copy into `ghostwriter.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/` the QtWebEngineProcess executable from the brew install of qt5. 

Don't know how to make this a little less clunky of a build process. Any ideas?

**Comment by BNolet** [comment]
Alright, after some digging, it looks like `macdeployqt` is the culprit here. 

https://bugreports.qt.io/browse/QTBUG-86759

Will only be fixed with version 5.15.2 which is not available with brew yet

**Comment by BNolet** [comment]
Was able to install 5.15.2 via the Qt website open source license and compiled the build here: https://github.com/BNolet/ghostwriter/releases/tag/v2.0-alpha2

Only tested to run in Big Sur. I'll see about testing in Catalina tomorrow

**Comment by BNolet** [comment]
A little late, but yes this runs on Catalina. Only issue is with the themes chooser. It has a minimum height and width that just does not make any sense

**Comment by wereturtle** [comment]
If anyone wants to take a shot at making a Travis-CI yaml build instructions, I'd be very grateful.  :)
