### ISSUE TITLE
Scrolling line by line breaks smooth scrolling experience

### ISSUE THREAD

**Issue by BNolet** [wereturtle/ghostwriter#558]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: macOS Big Sur
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]:

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.0.0-rc
 - If Windows, installation type [e.g., portable or full install]:
 - If Linux, installation type [e.g., Flatpak, PPA, private build]:

**Describe the bug**
While scrolling in macOS the smooth scrolling  experience is broken. Instead, ghostwriter scrolls line by line.

**To Reproduce**
1. scroll any document  in ghostwriter

**Expected behavior**
Supposed to scroll like every other macOS app, rubber banding at the ends of documents and all.

**Comment by wereturtle** [comment]
Closing this issue as there was no reply from the author after two weeks.
