### ISSUE TITLE
Help..Linux user cannot make fullscreen

### ISSUE THREAD

**Issue by benji88i** [wereturtle/ghostwriter#561]
Hi there,

I love ghost writer but I recently upgraded to Fedora 33 and when i make it full screen the app vanishes. It still runs in the background however but I cannot interact with my other open applications.

I installed the app from Flathub and Ghost writer version I have is:

Version : 1.8.0

See screenshot below which kind of shows whats going on...The visible window (LHS) is adjusted to be smaller and the fullscreen document (RHS) is invisible..

![Screenshot from 2020-12-26 22-02-12](https://user-images.githubusercontent.com/68906758/103150266-8bd4ae00-47c6-11eb-8bc5-628edce2fad2.png)

Just hoping someone could assist

**Comment by wereturtle** [comment]
Are you using Wayland per chance?  It could be that Qt isn't fully supporting that functionality under Wayland.  Try switching to X and see if it works.

FYI, I too am on Fedora 33, but with KDE Plasma and X.  No problems there.  Worth a try to switch to X.

**Comment by benji88i** [comment]
Hi There,

I am using wayland with budgie on Solus OS and on fedora Gnome. Not sure precisely the difference. 

The issue only happens with Fedora though.

**Comment by benji88i** [comment]
> Are you using Wayland per chance? It could be that Qt isn't fully supporting that functionality under Wayland. Try switching to X and see if it works.
> 
> FYI, I too am on Fedora 33, but with KDE Plasma and X. No problems there. Worth a try to switch to X.

Is X another desktop environment? I love gnome for laptops but for desktop I like budgie.

**Comment by wereturtle** [comment]
X and Wayland are display server communication protocols.  In other words, they're the thing that says how the windows will be displayed based on your keyboard/mouse inputs.  Wayland is the successor to X, but isn't 100% ready for prime time with every desktop environment.  Fedora turns on Wayland by default.  Qt apps, like ghostwriter, might not do as well under Wayland.  As such, you can try switching back to X by logging out and selecting an X session of Gnome instead of Wayland from the menu.  Hopefully ghostwriter will be happy with that.

**Comment by metmarkosaric** [comment]
Had the same issue on latest Gnome/Wayland/Xwayland on Debian. Try to run ghostwriter like this. It fixes the full screen issue and other issues for me:

``` QT_QPA_PLATFORM=xcb ghostwriter ```

If that works, you can make this change permanent by changing the Exec line in your ghostwriter.desktop file to be like this:

``` Exec=env QT_QPA_PLATFORM=xcb ghostwriter %f ```

Great app by the way @wereturtle, thank you!

**Comment by santiagocezar** [comment]
Well that's just a work around that forces the app to run on XWayland. Do we know if this is an app or Qt problem?

**Comment by wereturtle** [comment]
> Well that's just a work around that forces the app to run on XWayland. Do we know if this is an app or Qt problem?

@santiagocezar  Try installing another Qt app that can run in full screen, and see if it has the same problem in Wayland.  That's the only way to know.
