### ISSUE TITLE
Ghostwriter pandoc preview shows error

### ISSUE THREAD

**Issue by Spounka** [wereturtle/ghostwriter#563]
**Platform:**
 - Arch Linux: 
 - KDE 5.20:

**ghostwriter installation:**
 - ghostwriter version 1.8.1:
 - If Linux, installation type: Arch package / Repository

**Describe the bug**
Whenever I try to change the preview engine to pandoc ( any variant of pandoc ) the preview throws an error as in the screenshot
![GHOSTWRITER ERROR](https://user-images.githubusercontent.com/30209821/105488950-c12fc700-5cb2-11eb-9ed4-3993501a5ea8.png)

**Comment by berrfred** [comment]
Same issue on Windows Server 2019 with ghostwriter 1.8.0 / 1.8.1 and pandoc 2.11.4.

`pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.5, ipynb 0.1.0.1
User data directory: C:\Users\Administrator\AppData\Roaming\pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.`

**Comment by netskink** [comment]
I was going to file an issue but I saw this one.  My error is possibly related so perhaps its best to include here.

I am running Debian linux stable.  I have tried the apt-get install ghostwriter using the default stable repository and the repo specified in the install guide here.  In both cases the rendered preview screen is blank with a single message:

```
Export failed: Cannot find file --smart at /usr/bin/multimarkdown line 127.
```

The other user mentioned pandoc.  Originally I did not have pandoc installed.  If I install pandoc, the error persists.

```
$ pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
Default user data directory: /home/davis/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by fushinari** [comment]
See #488 and #550 . For Arch users, install `pandoc-bin` rather than `pandoc` for a better experience.
