### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cedardocster** [wereturtle/ghostwriter#564]
Will there ever be an option to use wiki links for following local links?  

Something like [[some link]] to open the file "some link.md" in the current folder.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
