### ISSUE TITLE
Feature request - snippets

### ISSUE THREAD

**Issue by cdbdev** [wereturtle/ghostwriter#567]
Hi,

First of all thanks a lot for your great work!!

I just have 1 request, is it possible to provide functionality to create snippets?

Thanks

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
