### ISSUE TITLE
More options in Format menu

### ISSUE THREAD

**Issue by cdbdev** [wereturtle/ghostwriter#568]
Hi,

Is it possible to add some more options to the FORMAT menu please?

- code block / inline code
- table
- insert url

Thank you

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
