### ISSUE TITLE
feature request: support github flavor tables in preview html

### ISSUE THREAD

**Issue by oising** [wereturtle/ghostwriter#569]
As the title says -- it seems github tables don't render. 

e.g.

```md
|x|y|z|
|-|-|-|
|1|2|3|
```

|x|y|z|
|-|-|-|
|1|2|3|

**Comment by cdbdev** [comment]
It works, you just have to install a convertor that supports GFM like pandoc. You're probably using 'Sundown' which is default I think.

Greetings

**Comment by oising** [comment]
@cdbdev I'm using the windows build -- I couldn't see any way to add extensions like that. The dropdown for the renderer only shows sundown, as you say.

**Comment by cdbdev** [comment]
I'm using windows too. You just have to download and install pandoc. It will be added to your dropdown afterwards

**Comment by oising** [comment]
Thanks @cdbdev  -- I'll close this issue now.
