### ISSUE TITLE
Have Ctrl+H open find-and-replace window.

### ISSUE THREAD

**Issue by tsoj** [wereturtle/ghostwriter#570]
This is a very small (I guess?) feature request, many editors have a Ctrl+H shortcut to open the find-and-replace window, so it might be not only useful for me but for a few other people, too.

**Comment by wereturtle** [comment]
This is a configuration issue with your distro.  (I'm assuming you are on Linux).  For example, if you are using KDE Plasma as your desktop environment, the default shortcut for find and replace is `Ctrl+R`.  This is not the first time I've heard of unusual or missing keyboard shortcuts.  It seems something is configured wrong for Qt at the distro level, which sadly would require a much more expert troubleshooter to resolve than myself.

I'll leave this issue open for a while in case someone else has an idea.
