### ISSUE TITLE
Rendering of checkboxes

### ISSUE THREAD

**Issue by ygaeon** [wereturtle/ghostwriter#572]
I've quite recently discovered Ghostwriter and opted to migrate to it quite quickly, after using Typora, Marktext and Joplin. Ghostwriter is very fast in comparison. 
As an avid user of todo-lists along my note taking I was surprised that checkboxes wasn't rendered in the preview. I'm not sure if that is something that you have already in your projected implementation. However, I'll create this issue here for you in case it's something you'll implement down the line :-)

```
- [ ] An item to be done
- [x] An item that is done
```
Should be rendered something as:
- [ ] An item to be done
- [x] An item that is done

Thanks guys... :+1:

**Comment by abenson** [comment]
You'll need to pick a renderer that supports it, this isn't something that
gets implemented in ghostwriter itself.

**Comment by ygaeon** [comment]
OK, thanks.
In the settings I can find "Settings -> Preview Options -> Markdown Flavor = Sundown" ..
Would this be the "renderer" you're mentioning?
If so, I'm unable to select anything else than "Sundown".
Where may I find other renderers? (that will be available in the preview mode)

**Comment by abenson** [comment]
You may need to install `cmark-gfm`.  What operating system are you on?

The next version looks like it'll have `cmark-gfm` built-in, so this is
likely temporary.

**Comment by ygaeon** [comment]
Oh, I'm sorry. :-)
```
OS: Arch Linux x86_64
Kernel: 5.11.2-arch1-1
WM: i3
```

```shell
$ sudo pacman -S cmark-gfm
```
Selected it in "Settings -> Preview Options". Unfortunately the preview still doesn't render check-boxes :)

**Comment by Hermann12** [comment]
> OK, thanks.
> 
> In the settings I can find "Settings -> Preview Options -> Markdown Flavor = Sundown" ..
> 
> Would this be the "renderer" you're mentioning?
> 
> If so, I'm unable to select anything else than "Sundown".
> 
> Where may I find other renderers? (that will be available in the preview mode)

I see pandoc, too.

**Comment by ygaeon** [comment]
Ah, I don't have `pandoc` installed (trying to avoid Haskell packages on my system).

Unfortunately I don't think css would be able to search for `- [ ]` and replace with `<input type="checkbox">` 

:-)

**Comment by Hermann12** [comment]
> 
> 
> Ah, I don't have `pandoc` installed (trying to avoid Haskell packages on my system).
> 
> Unfortunately I don't think css would be able to search for `- [ ]` and replace with `<input type="checkbox">`
> 
> :-)

I tried this one and it works fine in the preview mode. Source: https://jblevins.org/log/custom-css
