### ISSUE TITLE
Feature Request: Add support for Gemini markdown format

### ISSUE THREAD

**Issue by dvn0** [wereturtle/ghostwriter#573]
Gemtext is a very simple markdown format, primarily used for the Gemini internet protocol.

The markdown syntax is very simple, and has very few rules, and the main thing which is different than commonmark is the link syntax: `=> url:.// Optional Link Title`

You can read the specification here: https://gemini.circumlunar.space/docs/specification.gmi (Section 5 "The text/gemini media type")

Another reference:
https://gemini.circumlunar.space/docs/gemtext.gmi

Would be nice to have this in Ghostwriter.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
