### ISSUE TITLE
Theme Folder Not Found - Can't Save or Load Themes

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#575]
OS: Linux 5.11.7-arch1-1 #1 SMP PREEMPT
QT: Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0)
DE: KDE Plasma,

**ghostwriter installation (please complete the following information):**
AUR Build from git.

**Describe the bug**
User theme folder not read. Can't load themes. Can't create themes.

**To Reproduce**
1. Try to apply a theme that is already or
2. Try to create a new theme by editing the current
3. See error

**Expected behavior**
Themes in ~/.config/ghostwriter/themes should be honored.
New themes should be created in ~/.config/ghostwriter/themes if the folder exists.

**Screenshots**

![image](https://user-images.githubusercontent.com/10410111/111846571-e1ac8400-88e5-11eb-9f71-f1370441ae1e.png)

**Comment by wereturtle** [comment]
First, I have no idea why the AUR maintainer is including a release candidate (or even alpha!) of the upcoming version 2.0.0.  You may wish to contact the maintainer to use the latest tag in git instead, which is the last stable release.

Second, theming in version 2 has changed drastically.  But I haven't seen this error.  Version 2 will not load old themes from version 1, but it should be able to create them.  Try verifying your permissions in ~/.config/ghostwriter and make sure it's still writeable.  You can also try compiling from the source and seeing if the latest and greatest works for you.  Let me know how it goes.

**Comment by jggouvea** [comment]
Thank you. For some odd reason the theme folder had become read-only. As for the theme format change, now let's just wait for the new releases. 

Should I delete the old theme rpo?
