### ISSUE TITLE
always SEGV during editing inline euqation

### ISSUE THREAD

**Issue by braindevices** [wereturtle/ghostwriter#577]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Ubuntu 20.04
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Gnome

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.0.0-rc5
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: ppa:wereturtle/staging

**Describe the bug**
try to edit the text as normal. The sidebar keeps appear and disappear during typing. When try to insert/modify text in inline equation. the program just crash with SEGV.

**To Reproduce**
0. make sure the `hide sidebar while typing` is on.
1. select light mode
2. type `$$` then use arrow to go back and insert between `$ $`
3. crash

**Expected behavior**
show not crash

**Comment by wereturtle** [comment]
I can't replicate the SEGV behavior with my Pandoc installation under Fedora.  What version of Pandoc are you using?  You can type the command below in a terminal window to find out:

```
$ pandoc -v
```

As for your equation rendering issue, I believe the `\,` part is some sort of escape thing?  If I use three backslashes instead, it renders correctly in Pandoc (`\\\,`).  If I use two backslashes in cmark-gfm ('\\,') it will also render correctly.  The issue might be a conflict with Mathjax Javascript rendering the HTML equations after Pandoc partially preprocessed the math equations.  Mathjax definitely wants backslashes to be escaped if they aren't before a keyword.  Pandoc...I'm not sure what it's doing.  I'll investigate and find out.  I may have to turn off Pandoc's Mathjax option for the preview to get things consistent.  I'll let you know how it goes.

**Comment by braindevices** [comment]
```
$ pandoc -v
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/dracula/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ qmake -query QT_VERSION
5.12.8
```

**Comment by braindevices** [comment]
I don't think it is pandoc problem though. panwriter works fine to some point. Is there anyway to turn on verbose mode of ghostwriter?

**Comment by braindevices** [comment]
> As for your equation rendering issue, I believe the `\,` part is some sort of escape thing? If I use three backslashes instead, it renders correctly in Pandoc (`\\\,`). If I use two backslashes in cmark-gfm ('\,') it will also render correctly. The issue might be a conflict with Mathjax Javascript rendering the HTML equations after Pandoc partially preprocessed the math equations. Mathjax definitely wants backslashes to be escaped if they aren't before a keyword. Pandoc...I'm not sure what it's doing. I'll investigate and find out. I may have to turn off Pandoc's Mathjax option for the preview to get things consistent. I'll let you know how it goes.

no idea the cmark-gfm result is still wrong. `\,` show `,` still, which is wrong.

**Comment by wereturtle** [comment]
The equation will be rendered in cmark-gfm if you type `\\,` (sorry I messed up my backticks in my prior post).  Were you able to get Pandoc to render with `\\\,`?

**Comment by braindevices** [comment]
> Were you able to get Pandoc to render with `\\\,`?
with `\\\G` in the very front or `\\\,` at the end make pandoc preview work. But the export result is wrong, so basically the preview and export does not match. And the preview of inline equation also does not render correctly.

![Screenshot from 2021-03-24 21-13-35](https://user-images.githubusercontent.com/7507440/112377573-37b66880-8ce6-11eb-8eed-b5dad9c66c90.png)
![Screenshot from 2021-03-24 21-16-59](https://user-images.githubusercontent.com/7507440/112377659-53217380-8ce6-11eb-816e-0befea0a1f7d.png)

**Comment by braindevices** [comment]
BTW: the pandoc strict preview is fine. I wonder maybe the preview option is actually not what we selected in the preview setting.

**Comment by braindevices** [comment]
the problem is not fully solved yet. Now the presentation (font size, alignment is wrong):
![Screenshot from 2021-03-29 09-12-39](https://user-images.githubusercontent.com/7507440/112799784-1f8c7380-906f-11eb-9da8-7b99fca94cdb.png)

For inline equation we have to add space after and before `$`, which is ok. The format of the equation looks ok if add `\` in front of `\,`.

![Screenshot from 2021-03-29 09-13-32](https://user-images.githubusercontent.com/7507440/112799797-22876400-906f-11eb-8ce4-91e5fe58d7ea.png)
