### ISSUE TITLE
sidebar is out of control

### ISSUE THREAD

**Issue by braindevices** [wereturtle/ghostwriter#578]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Ubuntu 20.04
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Gnome

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.0.0-rc5
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: ppa:wereturtle/staging

**Describe the bug**
1. when sidebar is turn on, type in editbox. The sidebar will disappear during typing then re-appear when typing stop. This is very disturbing.
2. when sidebar is turn off, type in editbox. The sidebar will automatically appear. And then it has same behaviour as 1.

**To Reproduce**
1. type in text editbox
2. go to view->show sidebar to tick it off
3. type in text editbox again

**Expected behavior**
1. the sidebar should not disappear when show sidebar is on.
2. the sidebar should not appear when show sidebar is off.

**Comment by wereturtle** [comment]
Hi, go to Settings -> Preferences from the menu bar, and then to the General tab.  There you will find a new option to hide the sidebar while typing.  Uncheck it.  I'm still tweaking the functionality for this feature.  Thank you for reminding me to make sure the sidebar doesn't reappear if it was turned off.  😄

**Comment by braindevices** [comment]
thanks for the tip, at least it does not disappear now.

**Comment by Moonbase59** [comment]
Same here, Linux Mint 20.1/Cinnamon and 2.0.0-rc5. Thanks for the workaround!
