### ISSUE TITLE
cannot remember the dark/light mode choice

### ISSUE THREAD

**Issue by braindevices** [wereturtle/ghostwriter#579]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Ubuntu 20.04
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Gnome

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.0.0-rc5
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: ppa:wereturtle/staging

**Describe the bug**
start ghostwriter turn off dark mode. Restart the ghostwriter will be in dark mode again.

**To Reproduce**
1. tick off the dark mode at the right side of the status bar.
2. close ghostwriter
3. run ghostwriter again

**Comment by wereturtle** [comment]
It's working fine for me under Fedora.  Please check your ~/.config/ghostwriter/ghostwriter.ini file to ensure that it is writeable.

**Comment by braindevices** [comment]
```
$ ls ~/.config/ghostwriter
dictionaries  ghostwriter.conf  themes
```
there is no ini file

**Comment by wereturtle** [comment]
Oh sorry, the .conf file then!

**Comment by braindevices** [comment]
it is 664 no problem. Seems no problem. I think due to the SEGV the program never get chance to write the config.
