### ISSUE TITLE
can we allow user go back to classic HUD mode?

### ISSUE THREAD

**Issue by braindevices** [wereturtle/ghostwriter#580]
In v2.0.0 the HUD is convert to sidebar. But I do not like the side bar. If I want the sidebar to be readable, it need to expand 1/5 of my window, which is too much and wasting my screen area, since normal sidebar info only few lines and mostly below 20 lines. If I make it narrow, I barely read the outline and other content.

The HUD is very useful because it can be transparent and multiple HUDs can be shown simultaneously. The HUD window can be addjust to perffect size and overlay on the preview panel since it is transparent. I always turn on the statistic HUD and outline. The newbies want the cheat sheet to be always active too. The sidebar approach disabled all of this convenience and waste more screen area. This is very important for people work on laptops.

**Comment by wereturtle** [comment]
Believe me, I had wanted to keep the HUDs for the same reasons.  However, the HUDs aren't working correctly of late under Wayland.  I was forced to abandon them.  😢
