### ISSUE TITLE
Feature request: Ctrl+D for deleting the current line

### ISSUE THREAD

**Issue by grisu48** [wereturtle/ghostwriter#581]
Hi,

To increase the awesomeness of `ghostwriter` I'd like to ask to implement `Ctrl+D` as shortcut for deleting the current line.

Thanks!

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
