### ISSUE TITLE
BOTTOM OF EDITOR CONTENT TRUNCATED IN HTML PREVIEW

### ISSUE THREAD

**Issue by UfiAuttorri** [wereturtle/ghostwriter#582]
**ISSUE**
When cutting & pasting "plain text" (no hidden control chars, etc.) into the editor, everything looks fine.  Toggling the live HTML preview shows that the bottom of the text will be truncated, usually in the middle of a sentence in a paragraph.  Nothing displays after that point in preview, although it is showing in the editor.

Additionally, the last paragraph, no markup/down, in the editor appears with shading - from where or how or why is unknown.  That shaded block is after the truncation point in the preview.

**ENVIRONMENT**
ghostwriter 2.0.0-rc5
Qt version 5.9.5
Linux Mint 19.3 Cinnamon, v4.4.8
Kernel 4.15.0-140-generic

**ADDENDUM**
Sorry if this is a known issue. I could not find anything similar.  Also, this should be easy to reproduce without any special editor content.

This issue only started with the current RC.  The previous did not have this problem.

[RC5_text-issue-example-20210329i0917.txt](https://github.com/wereturtle/ghostwriter/files/6222369/RC5_text-issue-example-20210329i0917.txt)
![RC5_text-issue-example-20210329i0917](https://user-images.githubusercontent.com/30702894/112850869-0932e780-9070-11eb-8d48-b935107dcb32.png)

**HINT**
Aha!  It seems if you add enough blank lines (CR/LF?) to the end of the editor, the other stuff will appear (be revealed) in the HTML preview window!  Perhaps this is a clue?  ... like a buffer pointer issue? O_o

**Comment by UfiAuttorri** [comment]
OK, so, out of curiosity we cloned the source local and installed the requisite tools/libs per the instructions here.  The make/build ran without any complaints.  We did not do the make install in order to have the original executable for comparison.  We launched the local build executable and ... NO PROBLEM!  The issue noted in #582 did NOT occur.  We then launched the "installed" version that had only moments earlier still exhibited the problem and it no longer exhibited the problem.

We can only surmise that we were "missing" something or else had a version of _something_ that was causing this issue.

**Comment by wereturtle** [comment]
This appears to happen only in cmark-gfm, not in Pandoc.  I narrowed the issue down to cmark-gfm not liking the special quotation characters.  I suspect it throws off the smart quotes option somehow, but that's just a hunch.  I recommend filing a bug report against cmark-gfm [here](https://github.com/github/cmark-gfm).

As a workaround in the meantime, you can switch Markdown processors (i.e., use Pandoc or MultiMarkdown), or else avoid using fancy quotation marks.

**Comment by Leopardus4** [comment]
Hi!

It looks weird. I created a simple document with only few characters:
[a.md](https://github.com/wereturtle/ghostwriter/files/6588087/a.md)

Result in Ghostwriter 2.0.1 - `aaa b` is truncated:
![obraz](https://user-images.githubusercontent.com/48633054/120568187-b0871e80-c413-11eb-92cd-4b455329b399.png)

But compiled `cmark-gfm` from [this repository](https://github.com/github/cmark-gfm) parses it correctly:
![obraz](https://user-images.githubusercontent.com/48633054/120568302-e5937100-c413-11eb-868c-26a7be4d42fa.png)

Could you explain @wereturtle where did you narrow this issue?

Anyway, thank you for a good editor!

**Comment by wereturtle** [comment]
I'm thinking the fix to #619 may have fixed this issue.  Would you please see if version 2.0.2, which incorporates this fix, works for you?

**Comment by Leopardus4** [comment]
Yes, in 2.0.2 preview is not truncated. Thanks!
