### ISSUE TITLE
Preview display inconsistant

### ISSUE THREAD

**Issue by Willtech** [wereturtle/ghostwriter#583]
Good Afternoon,

Let me appreciate you on a great project. I really enjoy writing markdown and this helps.

I am reporting that there is an issue of consistency in the preview display where text does not always display the same as it does on GitHub. Of course, it is possible that it is GitHub that is wrong, there is one other known issue with the consistency of display compared to the format.

![comparison of GhostWriter and GitHub](https://user-images.githubusercontent.com/1173622/113394899-c319b300-93e4-11eb-9a70-aec8e2d87252.png)
You may find a copy of the original document here;  
https://github.com/Willtech/passupd/blob/master/README.md

Keep up the good work you have our appreciation.

KING JAMES HRMH
Great British Empire

**Comment by wereturtle** [comment]
Is GitHub using cmark-gfm officially yet as their backend processor?  I'm not sure if they actually switched over yet.  It technically hasn't reached version 1.0, so I'm guessing not.  Either way, I recommend filing a bug report with cmark-gfm [here](https://github.com/github/cmark-gfm).
