### ISSUE TITLE
Print and Print Preview do not actually print the rendered version

### ISSUE THREAD

**Issue by TheBlackBeans** [wereturtle/ghostwriter#584]
**Platform (please complete the following information):**
Linux 64 bits Debian 10 Gnome 3.30.2

**ghostwriter installation (please complete the following information):**
Ghostwriter v1.7.4 via Debian repository.

**Describe the bug**
`Print` and `Print Preview` show the Markdown code, not the rendered version.

**To Reproduce**
Write `# Title`. Go to `File -> Print` or `File -> Print Preview`. You'll see `# Title` instead of `Title`, as shown `Live HTML Preview`.

**Expected behavior**
I expect to get the same result from printing and the HTML preview.

**Screenshots**
![code](https://user-images.githubusercontent.com/23179762/114297369-8028a100-9ab0-11eb-92df-bfdaf2480b7b.png) ![preview](https://user-images.githubusercontent.com/23179762/114297372-83239180-9ab0-11eb-9c40-81a82329389f.png)

**Comment by abenson** [comment]
As I recall this was intentional.  Use "Export" to generate a rendered version.  Also, printing was removed in 1.8.0 entirely.

**Comment by TheBlackBeans** [comment]
The joy of stable repositories I guess :) However, "Export" generates an HTML version, I want a PDF version. Currently, I use an external tool to convert Markdown to PDF, but it would be better to be able to directly generate the pdf from within the application, especially because the external tool (pandoc) actually doesn't render at all the same way (I mean stylization is preserved but applied in a different fashion).

**Comment by abenson** [comment]
Export should offer a dropdown allowing you to pick the filetype.

![Export Dialog](https://user-images.githubusercontent.com/227317/114564386-e1c64800-9c35-11eb-93dd-4cf8c07675fb.png)

**Comment by TheBlackBeans** [comment]
I saw that, but it only offered HTML until I realized you have to choose a Markdown converter that allows for pdf conversion. The one I had by default (Sundown) only did HTML. Thanks
