### ISSUE TITLE
FreeBSD port about to be deleted because of dependency on Python 2.7

### ISSUE THREAD

**Issue by nkosi23** [wereturtle/ghostwriter#585]
Hello,

The port of ghostwriter for FreeBSD [will be deleted in June](https://www.freshports.org/editors/ghostwriter/) because apparently ghostwriter depends on qt5-webengine which itself depends on python 2.7 which is EOLed. After a couple of years of deprecation warnings, FreeBSD has now started to actively remove packages depending on python 2.7. 

Is there a way to build ghostwriter without needing python2.7?

**Comment by wereturtle** [comment]
Wow, why would qt5-webengine need python at all?  On Fedora, for example, the equivalent `qt5-qtwebengine` package has no dependency on python whatsoever.  There is, however, a separate package for Python **3** bindings to qtwebengine.  I wonder of the FreeBSD maintainer who packaged the `qt5-webengine` package included Python 2 bindings within, or else added a dependency to the bindings package for Python 2?  It sounds like something that the `qt5-webengine` package maintainer needs to fix.

Unless...There's a new qt5-webengine package that supports Python 3 and is just named differently?  In which case, whoever is maintaining the *ghostwriter* package for FreeBSD needs to switch dependencies.
