### ISSUE TITLE
Toggle menu bar when not full screen mode

### ISSUE THREAD

**Issue by cedricfung** [wereturtle/ghostwriter#587]
Most Linux apps allow disable the menu bar even when not full screen mode, that makes the interface clean.

**Comment by wereturtle** [comment]
You mean...most *GNOME* apps?  :laughing:  This is a Qt app, a la what KDE apps are built on, so...it works as intended.  :)

**Comment by RiedleroD** [comment]
I mean, firefox and chrome both disable it, and those don't necessarily follow GNOME-standards. pcmanfm has it enabled in both their qt and gtk frontends, teams and discord hide it. deadbeef and corrscope don't. Kate has hundreds of settings, but hiding the menu bar isn't one of them, and it's really annoying.

So please, if anything, add at least an option to hide it. Or show it by default and toggle it when Alt is pressed. Just dismissing it is kinda unfair.

**Comment by cedricfung** [comment]
@RiedleroD You may try my fork. https://github.com/cedricfung/ghostwriter
