### ISSUE TITLE
Ordered list in style 1) doesn't work

### ISSUE THREAD

**Issue by PSLLSP** [wereturtle/ghostwriter#589]
ghostwriter v1.8.1, installed from PPA
Ubuntu Linux 18.04.5

I am not sure but I think that ordered list in style 1) 2) is not part of standard `Markdown`. `ghostscript` editor supports it, so I tried it and I see in preview window (CTRL+M) that it doesn't work as expected. When I define ordered list in standard way, like 1. 2., it works good...

Example, WISH list is not rendered as list in the preview window, it is one long paragraph:

```
# DEMO

## TODO list, this works:

1. learn **MARKDOWN**
1. learn **Linux**
3. buy new computer

## WISH list, this is broken:

1) learn **MARKDOWN**
1) buy new house
3) buy new car
```

**Comment by wereturtle** [comment]
The default processor, cmark-gfm, does not support that ordered list style.  However, you can install a different processor, such as Pandoc, that DOES support it.  *ghostwriter* will automatically detect it's installation on startup, and you can switch to using it in your preview settings.
