### ISSUE TITLE
Where is the macOS application bundle?

### ISSUE THREAD

**Issue by NightMachinery** [wereturtle/ghostwriter#592]
```
MacOS
You can download an application bundle for MacOS and copy it under /Applications (for all the users) or $HOME/Applications (for the current user). That application should work on osx 10.10+, but was tested only on macOS 10.13. Please remember that this build is experimental and you'll find some bugs. Please report those on the issue tracker.
```

Where are the links for these bundles?

PS: Trying to build from source fails:
```
❯ git clone https://github.com/wereturtle/ghostwriter
cd ghostwriter
qmake
make

Cloning into 'ghostwriter'...
remote: Enumerating objects: 5270, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 5270 (delta 56), reused 66 (delta 30), pack-reused 5149
Receiving objects: 100% (5270/5270), 20.64 MiB | 840.00 KiB/s, done.
Resolving deltas: 100% (3104/3104), done.
Updating files: 100% (1043/1043), done.
Info: creating stash file /Users/evar/Base/_Code/misc/ghostwriter/.qmake.stash
Project MESSAGE: using font awesome free
Project WARNING: Qt has only been tested with version 10.15 of the platform SDK, you're using .
Project WARNING: This is an unsupported configuration. You may experience build issues, and by using
Project WARNING: the 11.1 SDK you are opting in to new features that Qt has not been prepared for.
Project WARNING: Please downgrade the SDK you use to build your app to version 10.15, or configure
Project WARNING: with CONFIG+=sdk_no_version_check when running qmake to silence this warning.
Project ERROR: Unknown module(s) in QT: webenginewidgets webengine webchannel
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by wereturtle** [comment]
Unfortunately, I don't officially support MacOS, largely because I don't own the necessary Mac hardware.  The build notes are maintained by volunteers.  I am likewise reliant on volunteers to bundle the MacOS application.  None have volunteered so far.  But if you figure out how to build it and bundle it, please do volunteer!  :smile:

**Comment by KingBBQ** [comment]
The error above suggests you are trying to build on Apple ARM (aka M1) system. AFAIK the QT5 doesnt support webengine yet:

https://bugreports.qt.io/browse/QTBUG-85537

**Comment by KingBBQ** [comment]
> @NightMachinary before calling qmake add `CONFIG+=sdk_no_version_check`in `ghostwriter.pro`file, in the `macx`block starting at line 201, for example in line [213](https://github.com/wereturtle/ghostwriter/blob/master/ghostwriter.pro#L213).
> 
> On macOS 10.15 with newest XCode (12.4) ghostwriter then compiles and resulting app can be started.

Can you supply the build package? I cant compile on ARM; but should be able to run the build through Rosetta

**Comment by NightMachinary** [comment]
@KingBBQ I am not on ARM, actually. It still doesn't compile:
```
❯ qmake
Project MESSAGE: using font awesome free
Project ERROR: Unknown module(s) in QT: webenginewidgets webengine webchannel
```

**Comment by alanfranz** [comment]
I have been able to build the bundle with Mojave. Here's a link to the my release:

https://github.com/alanfranz/ghostwriter/releases/tag/2.0.1-macos

I haven't tested anywhere else. Of course I know it's not exactly a "trusted and reproducible process". If I like and use ghostwriter I may think about creating a build script for AWS MacOS instances.

**Comment by picajoso** [comment]
Thank you @alanfranz :) Works on my Mac mini M1 (8/256GB) with macOS 12.3.1
