### ISSUE TITLE
Menubar gone after fullscreen

### ISSUE THREAD

**Issue by matthiasbeyer** [wereturtle/ghostwriter#593]
**Platform (please complete the following information):**
 - OS and version: NixOS 20.09 (stable)
 - Desktop Environment: KDE Plasma

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 1.8.0
 - If Linux, installation type: distro package

**Describe the bug**

If I enter fullscreen mode via KDE and then exit it again, the menu bar is gone. It is still accessible via the `ALT-<key>` bindings, but not visible.

**To Reproduce**

1. Open Ghostwriter
2. Fullscreen it (via keybinding, for me Meta+f)
3. Exit Fullscreen (via keybinding, for me Meta+f)

**Expected behavior**
Menubar visible after exiting fullscreen.

---

Thanks for making this nice piece of software, I like it a lot (although I'm usually a vim poweruser)! :tada:

**Comment by wereturtle** [comment]
Is this error still occurring for you with the new 2.0.1 version?  I cannot replicate it on this version.

**Comment by matthiasbeyer** [comment]
My distro (nixos) ships 2.0.0 in the `nixos-unstable` channel and I cannot reproduce this error with this version (2.0.0) either.

I consider this fixed!

**Comment by wereturtle** [comment]
Great, thanks!
