### ISSUE TITLE
Sidebar text is squashed

### ISSUE THREAD

**Issue by j-james** [wereturtle/ghostwriter#596]
**Platform (please complete the following information):**
 - OS and version: Arch Linux 5.12.1
 - Desktop Environment: GNOME

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 2.0.0-rc5
 - If Linux, installation type: Compiled from cedricfung's fork, but this bug should be applicable to this repo

**Describe the bug**
The sidebar is too squished to fit its default text. This also applies on the Markdown cheat sheet pane.

**Screenshots**
![2021-05-07-180202](https://user-images.githubusercontent.com/35242550/117520771-c9103000-af5e-11eb-9d26-1bd1fbf6da45.png)

**Comment by wereturtle** [comment]
You can drag that thin light to the right of the sidebar with your mouse to make the sidebar wider as a workaround.  What's your screen resolution like?  The app makes the default size based on a screen percentage.

**Comment by j-james** [comment]
I'm on a 1920x1080 screen. I'll check to make sure it happens with the default font, too.
