### ISSUE TITLE
Use system-wide installation of cmark-gfm

### ISSUE THREAD

**Issue by dotlambda** [wereturtle/ghostwriter#597]
Ghostwriter should try to find cmark-gfm using pkg-config and only use its vendored version if unseccessful.

**Comment by wereturtle** [comment]
cmark-gfm is built-in to help with syntax highlighting.  Having it as part of the executable improves speed.

**Comment by dotlambda** [comment]
> Having it as part of the executable improves speed.

That's only part of the truth: If other programs load the same library, speed is higher if it's a shared one.

**Comment by wereturtle** [comment]
> That's only part of the truth: If other programs load the same library, speed is higher if it's a shared one.

I believe [this article from IBM](https://www.ibm.com/docs/en/aix/7.2?topic=techniques-when-use-dynamic-linking-static-linking) explains my rationale and would be educational for you to read.
