### ISSUE TITLE
Flatpak is not up to date

### ISSUE THREAD

**Issue by danburd** [wereturtle/ghostwriter#600]
**Platform (please complete the following information):**
 - OS and version: Fedora 34
 - If Linux, Desktop Environment: GNOME 40

**ghostwriter installation (please complete the following information):**
 - If Linux, installation type: Flatpak

**Describe the bug**
The [flatpak on Flathub](https://www.flathub.org/apps/details/io.github.wereturtle.ghostwriter) has not received the 1.8.1 update nor the 2.0.0 update. It is currently on 1.8.0 and has not apparently been updated since May 2019. It also uses outdated runtimes (freedesktop 18.08 and and kde 5.12).

**To Reproduce**
1. Go to https://www.flathub.org/apps/details/io.github.wereturtle.ghostwriter and see that the version number is 1.8.0 and that it was last updated on May 11, 2019.
2. Run `flatpak install flathub io.github.wereturtle.ghostwriter` in the terminal and see that the installer tries to pull many outdated runtimes

**Expected behavior**
Ghostwriter's flatpak would be on the 2.0.0 release and would use up-to-date runtimes.

**Comment by wereturtle** [comment]
Yes I'm still debating whether I want to maintain the Flatpak app.  It seems every time I submit a new build for Flathub, their build machine has some new validation error that they added that isn't reflected in a local Flatpak build.  It gets frustrating after a while.

**Comment by linuxkettle** [comment]
FreeBSD package is on 1.8.1 as well.

**Comment by eternaltyro** [comment]
If not flatpak, is there a chance you could release an AppImage?
