### ISSUE TITLE
Support for FTP/FTPS/SFTP

### ISSUE THREAD

**Issue by Zagur** [wereturtle/ghostwriter#605]
It could be a nice feature to be able to connect via FTP/FTPS/SFTP to edit markdown files and when you save the file it is uploaded via FTP/FTPS/SFTP to the server.

Similar to this plugin for Atom: https://atom.io/packages/remote-ftp In the end it is just a remote navigation.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
