### ISSUE TITLE
File corrupted after power outage.

### ISSUE THREAD

**Issue by winarama** [wereturtle/ghostwriter#606]
**Platform (please complete the following information):**
 - Linux Mint 18.04
 -  Cinnamon Desktop Environment

**Ghostwriter installation (please complete the following information):**
 - Ghostwriter v1.8.0
 - Installation type PPA

**Describe the bug**
While editing a file in ghostwriter my laptop lost power. When I rebooted, the file I was editing was corrupted (replaced with some weird binary file) and the .backup file was empty. Is there a way to retrieve the contents of the original file?

**To Reproduce**
N/A

**Screenshots**
Screenshot shows contents of corrupted file, I don't recognize the encoding.
![Screenshot from 2021-05-13 10-30-12](https://user-images.githubusercontent.com/48623322/118060862-1f55f680-b3d7-11eb-9d94-1a562338109a.png)

**Comment by wereturtle** [comment]
Sorry to hear that!  I'm afraid you can't recover from this.  It looks like the OS was still writing to the file when it happened.  Things tend to get all buffered on the way to the hard drive/SSD drive, and thus you may experience file corruption on power loss.  :cry: 

I'm truly sorry for your loss.

**Comment by winarama** [comment]
No worries man, luckily my brain still works so I just need to write it again.

So was it like a buffer race condition when writing to the file system?

**Comment by wereturtle** [comment]
Probably more like the data was still in the process of being written, or queued up to be written.  Losing power in the middle of that can cause all sorts of fun stuff.
