### ISSUE TITLE
Preview tables and images

### ISSUE THREAD

**Issue by innovation-plantation** [wereturtle/ghostwriter#613]
Provide a way to see tables and images as they are entered.
For images it would be fine to show the image when hovering over the link, or show it below the link.
For tables, it would be fine to show a table to the side of the text, or to move the text to line up with as columns with lines between cells.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
