### ISSUE TITLE
When typing Korean, the cursor blinks in front of the letter.

### ISSUE THREAD

**Issue by hfdkj** [wereturtle/ghostwriter#614]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
Windows 10

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 1.8.1
 - If Windows, installation type [e.g., portable or full install]: portable

**Describe the bug**
If you type any letter in Korean, the cursor blinks at the left side of the letter.
The cursor is supposed to be at the right (you can experiment in Notepad or any other browser)
I could still type properly with the bug, but it's a minor inconvenience

**To Reproduce**
Type any Korean letter, and you can see the cursor blinking at the left side of the letter.
But when you type any non-Korean letter (comma, latin alphabet...) the cursor is at its proper place again.
Copy pasting Korean letters from the internet won't reproduce this issue. You need to type from a Korean keyboard.

**Expected behavior**
Cursor is supposed to look something like "abcde|"
Instead "ㄱㄴㄷㄹ|ㅁ"

**Screenshots**
https://user-images.githubusercontent.com/84863035/119696115-d21f5d80-be89-11eb-9511-b515fa436a5e.mp4

**Comment by wereturtle** [comment]
I'm thinking this is an upstream QT issue.  If you are interested in reporting the bug with Qt, please visit their bugtracker [here](https://bugreports.qt.io/secure/Dashboard.jspa).
