### ISSUE TITLE
Triple-click selects empty line

### ISSUE THREAD

**Issue by mjkorman** [wereturtle/ghostwriter#616]
I love ghostwriter, but there's something that annoys me everyday. When I triple-click on a line of text that's followed by an empty line, it selects both the text and the empty line. This makes it difficult to apply formatting to the line or to copy and paste into another application, because then I have to delete the empty line.

Most other applications do not have this behavior, but some do. I would appreciate a way to turn it off.

**Comment by wereturtle** [comment]
I'm afraid that's a Qt app thing that is out of my control.  The Kate editor (also made with Qt) will for example behave the same way.
