### ISSUE TITLE
Chinese preview in HTML is incomplete.

### ISSUE THREAD

**Issue by lioneie** [wereturtle/ghostwriter#619]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
Fedora33

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [newest code of master branch]:
 - Fedora33 private build

**Describe the bug**
Chinese preview in HTML is incomplete.

**To Reproduce**
Open "Preview in HTML" window, past long Chinese word(e.g., [Linux kernel coding style - Chinese translated](https://github.com/lioneie/blog/blob/master/coding-style-%E7%BF%BB%E8%AF%91-Linux%E5%86%85%E6%A0%B8CodingStyle/coding-style-%E7%BF%BB%E8%AF%91-Linux%E5%86%85%E6%A0%B8CodingStyle.md)), then the preview is incomplete.

**Expected behavior**
Show the Chinese preview complete.

**Comment by martin-ueding** [comment]
This also happens for German in Version 2.0.1. I have noticed that the “lag” is the number of UTF-8 characters that are prior to that position. It seems that it somehow counts the _characters_ on the Markdown side, but only emits the same number of _bytes_ on the HTML side. If I replace an “ä” (two bytes in UTF-8) with an “a” (one byte) prior to that position, the HTML preview shows one more character.

![Bildschirmfoto_20210626-10:12:47-8a9](https://user-images.githubusercontent.com/976924/123506966-460a7c80-d667-11eb-8f23-816d288f07e3.png)
