### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by digital-idiot** [wereturtle/ghostwriter#620]
**Platform**
 - Linux 5.12.9-1 MANJARO
 - KDE Plasma 5.21.5

**Ghostwriter**
 - 2.0.1
 - Native Repository (*Community*)

**Issue**
 1. Some icons / text on the buttons not being displayed
 2. Themes customization window on full-screen stretching beyond screen

**Reproduce**
- Launch Ghostwriter
- Launch theme customization window on full-screen

**Expected behavior**
- Text / icons on button should be displayed correctly
- All menus windows must not stretch beyond screen

**Screenshots**

![image](https://user-images.githubusercontent.com/10576475/121311817-0fadcd00-c905-11eb-8df1-e91a81963b73.png)

![image](https://user-images.githubusercontent.com/10576475/121312590-d0cc4700-c905-11eb-8fa4-83c6a18a4957.png)

**Additional Info**
- Using a HiDPI screen with 3840×2160 resolution.

**Comment by wereturtle** [comment]
While I don't have a HiDPI display, I cannot replicate this issue with the `QT_SCALE_FACTOR` environment variable set to 2 or above with Qt 5.21 / Fedora 34.  I even tried a fractional value of 1.5. What happens on another Linux distro for you with VirtualBox?  I'm just trying to see if a real HiDPI monitor causes the difference vs. the simulated HiDPI I get with the environment variable.  Or if it's just Manjaro being...Manjaro.

Thanks!

**Comment by rolodoom** [comment]
## Icons Missing

I have the same problem with the icons. I follow installation instructions from github:

	$ sudo add-apt-repository ppa:wereturtle/ppa
	$ sudo apt update
	$ sudo apt install ghostwriter

![Screenshot_20210628_162017](https://user-images.githubusercontent.com/61945227/123705959-3e94d000-d82d-11eb-914a-7ffd27c86286.png)

## My Linux Box Info:

**Platform**

	Linux 5.4.0-77-lowlatency Ubuntu
	KDE Plasma 5.18.15

**Ghostwriter**

    2.0.2
    Github Official Repository

**Issue**

    Some icons / text on the buttons not being displayed

**Reproduce**

    Launch Ghostwriter

**Comment by wereturtle** [comment]
For giggles, I installed the latest Kubuntu and the latest Ubuntu MATE in VirtualBox.  I could replicate the issue in Kubuntu with a fresh build, but not in Ubuntu MATE.  Fedora 34 (where my app instance looks OK), shares the same version as on Kubuntu, so it isn't the Qt version causing this.  It seems like there might be some sort of packaging issue that is OK in Fedora but not in Kubuntu/Manjaro?  But I don't know what that might be.

**Comment by dagdrommer** [comment]
The exact same issue is also currently present using the flatpak https://github.com/flathub/io.github.wereturtle.ghostwriter (under openSuse Leap 15.3)
