### ISSUE TITLE
Equations in a new file do not render

### ISSUE THREAD

**Issue by digital-idiot** [wereturtle/ghostwriter#621]
**Platform**
 - Linux 5.12.9-1 MANJARO
 - KDE Plasma 5.21.5

**Ghostwriter**
 - 2.0.1
 - Native Repository (*Community*)

**Issue**
 - Equations a new file do not render.
 - Equation rendering engine ignores newline (`\\` or `\\\\`) 

**Reproduce**
1. Launch Ghostwriter
2. Open a new file (Do not save)
3. Write some LaTeX equation
- Include newline inside an equation

**Expected behavior**
- Equations should be rendered without the need of being saved
- Equations should render newlines

**Screenshots**

![image](https://user-images.githubusercontent.com/10576475/121319176-3e7b7180-c90c-11eb-9018-db599f163437.png)

**Additional Info**
- Using a HiDPI screen with 3840×2160 resolution.

**Comment by wereturtle** [comment]
The equation you provided isn't rendering because it is missing a `}`.  Try this instead:

   $x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$

**Comment by digital-idiot** [comment]
> The equation you provided isn't rendering because it is missing a `}`. Try this instead:
> 
> $x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$

Despite that issue is still there even with the correct equation. See below:

![image](https://user-images.githubusercontent.com/10576475/125343819-d084f880-e356-11eb-9545-4fcbde7b2be5.png)

**Comment by wereturtle** [comment]
I can't replicate this issue.  Sorry.

![image](https://user-images.githubusercontent.com/10375170/126080122-827ff897-5299-4a61-b031-7af10c3c03ab.png)
