### ISSUE TITLE
Weird highlighting issue

### ISSUE THREAD

**Issue by andersmmg** [wereturtle/ghostwriter#624]
**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Manjaro Linux
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: KDE

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]:
 - If Windows, installation type [e.g., portable or full install]:
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: Manjaro Official Reposiroties (community)

**Describe the bug**
The `i` and the `l` in this text are darkened, and I don't know why. It doesn't seem to affect any of the functionality, but it's an odd possible bug that might be related to something bigger. I could just be misunderstanding someting though.

**To Reproduce**
1. Paste the text into the editor:

This is a test.
Also, this is too,
so is this,
and this.

**Expected behavior**
This text should all be the same color. (as far as I know)

**Screenshots**
![Screenshot_20210619_195242](https://user-images.githubusercontent.com/16022203/122660110-bed77900-d13b-11eb-98a6-bb7349f3cd32.png)

**Additional context**
Just typing the text word for word leaves it the right color until something is changed on that line, then this comes back.

**Comment by joshuakerr** [comment]
I just want to contribute another screenshot. Here I've changed the "markup" color in the theme to green in order to highlight the issue.

![image](https://user-images.githubusercontent.com/26580195/124316283-39d06480-db2a-11eb-92c6-4d2972a215bc.png)

I'm also using the Manjaro build from the repos (KDE). Ghostwriter 2.0.1.

**Comment by janTaja** [comment]
Windows 10, ghostwriter 2.0.2, same issue. I’ve also noticed the highlighting is weird if the line starts with non-English letters and isn’t the first line in the paragraph, I think it might be related.
![image](https://user-images.githubusercontent.com/53832230/124915081-c9c65080-dff9-11eb-99e1-1225708d590e.png)
The text in the image:
```
текст *text*
текст *text*

текст *text*
текст *text*
текст _text_
текст **text**
текст __text__
текст `text`
текст [Link](http://url.com "Title")
текст [Reference Link][ID]
текст ![Image](./image.jpg "Title")
текст [ID]: http://url.com "Reference Definition"
text *text*
text _text_
text **text**
text __text__
text `text`
text [Link](http://url.com "Title")
text [Reference Link][ID]
text ![Image](./image.jpg "Title")
text [ID]: http://url.com "Reference Definition"
```

**Comment by tildagail** [comment]
There's a discussion item  with more information that might help - #688
