### ISSUE TITLE
Cannot find the option to add a custom stylesheet

### ISSUE THREAD

**Issue by dhsathiya** [wereturtle/ghostwriter#625]
**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Description:	Ubuntu 20.04.1 LTS
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: **Gnome**

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: **2.0.1**
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: **PPA**

**Describe the bug**
Cannot find the option to add a custom stylesheet as described in https://github.com/wereturtle/ghostwriter/issues/530#issuecomment-655696029.

**To Reproduce**
Install ghostwriter with PPA on Ubuntu 20.04 with following commands:
```bash
sudo add-apt-repository ppa:wereturtle/ppa
sudo apt update
sudo apt install ghostwriter
```
**Expected behavior**
I should be able to see the custom stylesheet option under `settings > preview options` 

**Screenshots**
![image](https://user-images.githubusercontent.com/26240780/122993819-62878a00-d3c5-11eb-9491-59277c346184.png)

**Additional context**
Please let me know if more screenshots are required or any other information for debugging.

**Comment by dhsathiya** [comment]
I also found that syntax highlighting isn't working either for me.
Let me know if I have to install/configure anything for that.

**Comment by wereturtle** [comment]
That option has been removed with version 2.0.  Instead, the style sheet is adaptive to the current theme colors.  Syntax highlighting for source code within the preview requires Pandoc along with some Javascript being included (I don't remember off the top of my head which script Pandoc is using.)  You can include it manually within your document if you like.  However, ghostwriter does not support this feature directly.
