### ISSUE TITLE
how to make preview and sidebar not show automatically

### ISSUE THREAD

**Issue by cedardocster** [wereturtle/ghostwriter#627]
On wereturtle when I open a file the preview and side bar are always there.  I'd like to have just the editing window alone automatically open at first until I manually go to turn them on.

How do I do that - can't find that in settings.

**Comment by wereturtle** [comment]
If you don't have the preview and sidebar opened when you exit the app, the app should remember that when it next launches.  It does for me.  The last state of the app's UI configuration is stored under ghostwriter.conf.  You did not specify your OS, but you should be able to find the location for your OS in the README file.  Make sure the directory and .conf file itself are writeable.
