### ISSUE TITLE
[Packaging] Interested in helping for the Windows build

### ISSUE THREAD

**Issue by Meta-Don** [wereturtle/ghostwriter#629]
Hi, 

I read the contributing note and created an "issue" as requested.

I use ghostwriter a lot on Windows machines. Seeing that the "official fork" wasn't up to date, I decided to do it myself and spent some time setting up the VS+Qt environment. It worked and now I'm looking up to create msi installers (either the VS standard package or Inno Setup, not sure yet) so I could help out compiling newest builds for Windows.

I didn't use michelolvera's .sln project. I compiled from this source with MSCV in command line. 

Also, I'm new to contributing so I don't know if I should fork the repo or not to share these builds.

Thank you for making this great software,
Meta-Don

**Comment by YashWalke** [comment]
@Meta-Don I do **not** think you need to fork this repo to share your builds. Just create a new repo with a single README file and upload your builds in the 'Releases' section.

**Comment by Meta-Don** [comment]
@YashWalke thank you for suggesting this! 

Here is the [repo](https://github.com/Meta-Don/ghostwriter-windows-builds) containing portable versions for 2.01 and 2.0.2.

**Comment by michelolvera** [comment]
Hi, I have compiled the latest version, sorry for the delay.
