### ISSUE TITLE
Ghostwriter doesn't recognize Pandoc

### ISSUE THREAD

**Issue by Meta-Don** [wereturtle/ghostwriter#630]
**Platform (please complete the following information):**
 - OS and version: Windows 10 (10.0.19042)

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 2.0.2
 - If Windows, installation type: portable ("private build", I guess)

**Describe the bug**
As the title says, Ghostwriter doesn't see Pandoc. Pandoc is installed, I can use if from the command line and the PATH is set.

**To Reproduce**

1. Install ghostwriter 2.0.2 on a Windows machine + Pandoc (includes restart)
2. Start ghostwriter.exe
2. Check "Settings">"preview option"
3. "Markdown Flavor" click the list

**Expected behavior**
Pandoc should show up on the Markdown flavor list, it doesn't. Pandoc doesn't show up either on File>Export.

**Screenshots**
![Preview option menu only showing cmark](https://user-images.githubusercontent.com/44459141/123947704-f5fe2380-d9a0-11eb-8753-18200c7896bb.png)
![Path screenshot proving the path is set for Pandoc](https://user-images.githubusercontent.com/44459141/123947707-f696ba00-d9a0-11eb-8169-32d8aad18d66.png)

**Additional context**
Tried restarting the machine, tried it on another Windows machine (10.0.19042) and still got the same bug. 

Version 2.0.1 has the same bug. But Pandoc is recognized on version 1.8.1.

Thank you in advance,

**Comment by wuchtw** [comment]
I fixed it for ghostwriter 2.0.2 and 1.8.1 on Windows 10 (with default Microsoft Defender Antivirus)  by adding 'C:\Program Files\Pandoc\pandoc.exe' exclusion to Microsoft Windows Security. I didn't have the problem on another Windows 10 machine with Avast Antivirus. You may try excluding pandoc to your antivirus. For Microsoft Defender Antivirus, refer to [Microsoft Support](https://support.microsoft.com/en-us/topic/how-to-add-a-file-type-or-process-exclusion-to-windows-security-e524cbc2-3975-63c2-f9d1-7c2eb5331e53) .
![pandoc](https://user-images.githubusercontent.com/11154060/125017754-5e868800-e0a6-11eb-8208-565b549c9ca6.png)
