### ISSUE TITLE
Missing MSVCP140_1.dll (probably) and VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by janTaja** [wereturtle/ghostwriter#633]
**Platform:**
 - OS and version: Windows 10 Pro

**ghostwriter installation:**
 - ghostwriter version: 2.0.2
 - If Windows, installation type: portable

**Describe the bug**
The app fails to launch with two error messages “The program can’t start because VCRUNTIME140_1.dll is missing from your computer. Try reinstalling the program to fix this problem.”
It used to show a bigger number of such errors and one for MSVCP140_1.dll, but now it doesn’t.

**To Reproduce**
1. Download portable installation from here https://github.com/michelolvera/vs-ghostwriter/releases/tag/win-2.0.2
2. Unzip it
3. Launch ghostwriter.exe
4. See the errors

**Expected behavior**
The app launching without errors

**Additional context**
I’m a new user, so I don’t know if this problem was present in previous versions.
I tried to download the files manually, but the app fails to launch with the 0xc000007b error this way.
The thing with MSVCP140_1.dll: I remember putting it in System32, but I don’t see it there, and I don’t remember deleting it. I don’t know what happened.

**Comment by michelolvera** [comment]
You need to download visual c++ [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

Please close this issue if it works for you.
