### ISSUE TITLE
shortcut to move line up and down?

### ISSUE THREAD

**Issue by cedardocster** [wereturtle/ghostwriter#634]
in some text editors and some md editors you can move a line up and down with keyboard shortcuts (handy when organizing a todo checklist), e.g. in abricotine its ctrl-shift + up or down arrows.

Is there a way to do this in ghostwriter?

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
