### ISSUE TITLE
HTML formatted text copy is in plain text format style under Windows

### ISSUE THREAD

**Issue by clach04** [wereturtle/ghostwriter#635]
**Platform (please complete the following information):**
 - OS and version: Windows 10
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: NA

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.0.2
 - If Windows, installation type [e.g., portable or full install]: portable 
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: NA

**Describe the bug**

Edit menu, "Copy HTML" results in text style, i.e. not CF_HTML (`RegisterClipboardFormat("HTML Format")`). Pasting clipboard into a GUI tool that handles formatted text ends with plain text (with the HTML escaped).

I'm not 100% clear if this is a bug or an intended feature.

**To Reproduce**
1. Enter n Markdown/open MD file
2. Click on 'Edit' menu
3. Click on 'Copy HTML'
4. No Error,but pasting into an application (E.g. Microsoft Word, Outlook, MS Teams) results in plain text with html tags.

**Expected behavior**

I was expecting to see the pretty formatted output.

**Screenshots**

Happy to attach if text description is not clear.

**Additional context**

I'm no able to check this on another platform :(

I have a workaround. I wrote a Python script to pull from the clipboard and then dump back into the clipboard HTML style - see Microsoft docs https://docs.microsoft.com/en-us/windows/win32/dataxchg/html-clipboard-format

    import xerox  # note needs xerox (fork) https://github.com/clach04/xerox/ for clipboard access

    x = xerox.paste()
    xerox.copy(x, html=True)

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
