### ISSUE TITLE
it is feasible to use ghostwriter +markdown for large documentation files?

### ISSUE THREAD

**Issue by Osolemio44** [wereturtle/ghostwriter#636]
I have programming notes made in Microsoft Word that weigh 60 megabytes.
I want to pass that documentation to something opensource and that GIT can version. I have been researching 3 possible technologies.
 - MarkDown
 -  reStructuredText
 - DocBook. 

I have completely ruled out DocBook for its complexity. Personally, I am in love with MarkDown, but I am concerned about rendering when opening large files. 
I have read that there are people who have had problems loading files greater than 5 megabytes, but I have also read people who have written entire books in markdown. So the question is, could I work with ghostwriter and markdown for technical documentation with large files without having rendering problems?

#### P.D:
* One of the very important things for me is not having to fragment the markdown file into several small ones.
* I know that for long documentations, it is recommended to use rst. But I am much more attracted to the simplicity and syntax of markdown. I am also aware that MarkDown was designed for HTML, but anyway, javascript was also designed for the web and now we see it in the backend and desktop applications.

**Comment by wereturtle** [comment]
Yes!  I specifically engineered *ghostwriter* to handle large documents without freezing while typing or worse (crashing).  I regularly test it with *War and Peace*-sized files.  Take it for a spin and see for yourself!
