### ISSUE TITLE
hide word counter from the bottom

### ISSUE THREAD

**Issue by igroglaz** [wereturtle/ghostwriter#638]
![image](https://user-images.githubusercontent.com/39904162/125769916-afb5527c-2e9c-47d1-951e-fced1c275297.png)

"19 words".. it will be awesome to have an option to hide it.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.

**Comment by igroglaz** [comment]
I see thank you. It's sad cause I really hoped to use gw for my work.. but this counter distracts me a lot.
