### ISSUE TITLE
Allow using command for rendering

### ISSUE THREAD

**Issue by Arsen6331** [wereturtle/ghostwriter#639]
I made a custom markdown renderer. It accepts input on Stdin and outputs on Stdout. I would like to be able to use this in ghostwriter. Previously, I just symlinked to `cmark-gfm`, but that no longer seems to be working. Can this be added? If not, where would I add such functionality for myself?

**Comment by JoelMon** [comment]
I'm also interested in this feature. I'm writing a parser for my markdown that extends the syntax. It would be awesome if we could run commands like @Arsen6331 mentions.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
