### ISSUE TITLE
Asciidoc

### ISSUE THREAD

**Issue by jggouvea** [wereturtle/ghostwriter#64]
I know very well that "Ghostwriter" is supposed to be a Markdown Editor. However I am opening this issue for a simple reason: there's so little competition towards a good Asciidoc with syntax highlighting and the markup seems so straightforward that, perhaps, you will consider the possibility.

Little competition means that a web search for Asciidoc editors mostly return pages that claim that asciidoc can be edited by any text editor. But no specific editors.

Asciidoc solves a problem for people who want both an online and a printed version: it can be used to generate docbook, which can be translated to anything.

And it is used by many people who author free software manuals, including the Gnome project. This is a large userbase, and literate one that may get interested in lending you some help.

You will probably close this with a wontfix tag, I know. But I just wanted you to consider the possibility.

**Comment by wereturtle** [comment]
Well, it probably won't be me who does the implementation.  I decided long ago to keep the application focused toward Markdown.  But I am also not against the feature, either.  I can leave this issue open with a "Help Wanted" tag, if you like.  Someone with Qt experience is bound to show up eventually and chip in, right?  We can hope!  It's why I open-sourced the project, after all.

**Comment by wereturtle** [comment]
Closing due to lack of volunteers.  Will reopen if someone does volunteer.
