### ISSUE TITLE
Serious Conflict With NumPad and Lists

### ISSUE THREAD

**Issue by tajmone** [wereturtle/ghostwriter#65]
I think this issue report need a foreword: Many of the exalted standards in computing are built around the old days of ASCII, and in their tradition they carry on with a strong US-Centric attitude. MarkDown is no exception...

Non-USA keyboards (Italian is my case, but also French, German, and many others) don't have a key for characters like tilde `~`, or backtick `` ` `` — just to mention a few of the many missing ones! —, so you can imagine what a nightmare it becomes to mark a block code: we have to go through the `Alt + Numeric Pad 126` for tilde (or `96` for backtick) THREE TIMES in a row.

So much for talks on accessibility and open standards — and bare in mind: I'm sparing you the rants on working with Arabic and Hebrew keyboards, which would make anyone laugh at the mentioning of RTL implementation in 99% of existing software (as if introducing RTL was all there is to allow decent working with semitic languages, which have separation between vowels and consonants, and special glyphs for letters according to in-word context).

Going back to ghostwriter, the problem is that the Alt + NumPad numbers sequence trigger list styles whenever numbers 0, 1 or 8 are involved—which end up inserting all sort of list item syntax in the paragraph. Since there is no menu or hotkey to invoke inline or block code syntaxing, the Alt sequences are the only way to achieve them.

Personally, since I work a lot in text editing, I use frequently the NumPad shortcuts to quickly obtain Unicode special characters (from em-dashes to curly quotes, special letters, and so on). In some cross language works, special key sequences are required to switch between language modes, and for many special characters not represented on keyboard). So the potentials for problems at stake with the Alt + numbers sequences are rather high — unless the program can differentiate between numbers being struck on the main keyboard and thos on the numeric pad.

Therefore, any Alt hotkey involving numbers will inevitably conflict with non-USA keyboard users.

I would have thought that keyboard input would distinguish between numbers being typed in the main keyboard and those typed on the numeric pad, but maybe this is a shortcoming of Qt.

**Comment by wereturtle** [comment]
Doh!  Having a Homer Simpson moment.  The good news is it was on my to-do list already, because I was noticing conflicts between these shortcuts and the KDE Plasma 5 desktop shortcuts.  I'll prioritize this fix.

**Comment by tajmone** [comment]
Great! Sorry for the ranting ... but I get really frusted whenever I stumble on the good standars (*nix like) where such difficoult character are envolved.

I mean ... just look at Vim (or SublimeText), all the config hacks people with non-USA keyboards have to go through in order to acess all the tilde or backtick hotkeys (these are the 2 most troublesome characters for non-USA keyboards).

Unofrtunately, keyboard producers just behaved as if ASCII was dead. Except it's not.

But usally most API distinguish between numbers from keyboard and those from NumPad.

Thanks a lot! I'm really enjoying using GhostWriter! And I'm going to include it in a project here in GitHub (hopefully soon).

**Comment by wereturtle** [comment]
OK, I switched all the shortcuts using Alt to use Ctrl instead.

And you are most welcome.  I look forward to seeing your project.  I'm sure it will be interesting.

**Comment by tajmone** [comment]
Thanks a lot! Looking forward for next binary release (don't have required compiler on this PC).
