### ISSUE TITLE
Preview only, by command line or right-click?

### ISSUE THREAD

**Issue by darenw** [wereturtle/ghostwriter#690]
I'll be using Ghostview a lot on my Arch Linux machine. 99.8% of the time, only to look at .md files.  Once in a while, to create and edit them, but that's rare.  The normal view in Ghostview is 1/2 editor and 1/2 preview. I can slide the divider between to the left and have 100% view. 

But wouldn't it be slick to just right click on a file in Thunar (or any file manager) and just have the 100% preview view come up?  Is this possible?  

Often I am in a bash command line, and same thing... I see an .md view, and want to pop up a view-only markdown viewer. Could a command line option be provided to do that?

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
