### ISSUE TITLE
ghostwriter: No HTML preview when offline

### ISSUE THREAD

**Issue by Passionlinux** [wereturtle/ghostwriter#691]
Hello,

I am the maintainer of Debian and therefore of the distributions derived from it (ubuntu, Mint, MXLinux ...) for your program (as well as I frequently take care of the packaging of this one for openSUSE).
I received a bug report from a user of your Debian program, I am writing it here for you: 

> Package: ghostwriter
> Version: 1.8.1-2
> Severity: normal
> 
> Dear Maintainer,
> 
> ghostwriter doesn't show or update the HTML preview when the
computer is disconnected from the Internet. Looking at the
network traffic when starting ghostwriter reveals connection
attempts to "cdn.jsdelivr.net". This domain is referenced in
the MathJax code in the "3rdparty" directory of the ghostwriter
sources.
> 
> AFAIK there is no hint on the ghostwriter site nor in the
documents from Debian that an Internet connection is needed
for this editor to properly work.
> 
> Apart from the external JS sources obviously needed for the
HTML preview there is no other traffic to the net, and the
preview also works when disconnecting the computer after
ghostwriter was started.
> 
> HTH,
> Flössie
> 
> -- System Information:
> Debian Release: 11.1

You can find the request [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999658)

Is there something I missed when packing? What do you recommend? 

Best regards.

Sebastien.

**Comment by Passionlinux** [comment]
I just tested on my side, with version 2.0.2 available in Sid and 
testing, it works.

I'll wait and see if the person can confirm that their problem is no longer one on a more up-to-date version of Ghostwriter.

Cordially.

**Comment by Floessie** [comment]
@wereturtle Glad to see the issue tracker back. :+1: I would have reported directly upstream, if it had been there at the time.

@Passionlinux I'll reply here, as it's less tedious than on the BTS.

> I just tested on my side, with version 2.0.2 available in Sid and testing, it works.

I can confirm that for an unconnected Debian Testing laptop: it works with 2.0.2.

> Can you say more about your concern? Are there any pictures in the file? 

On Debian Stable with 1.8.1 there's no HTML preview update as described.

No pictures, just plain text.

> Is it just a file with text?

Yes.

> Is it possible to ask yourself if you have a file available 
> (non-personal) that does not work and that I could test on my side?

Open ghostwriter 1.8.1 on an offline machine. Enable HTML preview (<kbd>Ctrl</kbd>+<kbd>M</kbd>) and type some text. Nothing is shown in the HTML preview. Save the file. Close ghostwriter.

Open ghostwriter again. It will now show the text in the preview, but whatever you type isn't updated.

As for testing: maybe it's beneficial to test this under **Stable**. :wink: I for one wouldn't mind if ghostwriter is updated to 2.0.2 or latest in Stable to fix the bug, but I don't know if this is viable for you.

HTH,
Flössie

**Comment by Passionlinux** [comment]
Hello Flössie :-)

> @Passionlinux I'll reply here, as it's less tedious than on the BTS.

No worries, I still think for everyone's understanding, postpone the message in BTS.

I can confirm that it works with 2.0.2. With 1.8.1 there is no HTML preview update as described.

> As for testing: maybe it's beneficial to test this under Stable. wink I for one wouldn't mind if ghostwriter is updated to 2.0.2 or latest in Stable to fix the bug, but I don't know if this is viable for you.

I tested 1.8.2 and 2.0.2 on a stable as well as 2.1.0 :-); this is why I can confirm without worries that the 1.8.1 does not have a preview if not connected to the network, unlike the versions that follow.

I don't mind pushing a 2.0.2 version into stable, plus the bug fix might help. There is 2.1.0 but I still have a few odds and ends that I need to take care of before it is validated.

Regards

**Comment by Floessie** [comment]
@Passionlinux Fantastic! :+1: Looking forward to a newer version in stable!

**Comment by Passionlinux** [comment]
Hello;

I'll drop by to give some news. So as said, the package for version 2.0.2 is in backport, at least she waits. 
<https://ftp-master.debian.org/backports-new.html>
<https://ftp-master.debian.org/new/ghostwriter_2.0.2-2~bpo11+1.html>

Version 2.1.0 is in the Sid and testing repositories.

For the moment I always leave the bug on Debian open as long as the version which fixes it is still not in the backport ...

Regards.
