### ISSUE TITLE
Typewriter sound, and line spacing

### ISSUE THREAD

**Issue by mzsoli** [wereturtle/ghostwriter#692]
I know it's a bit old-fashioned, and maybe a useless idea, but I'd like to have a typewriter voice and line spacing in Ghostwriter.
If possible.
I love Ghostwriter and Markdown, by the way. Thanks a lot for that. Simple, small, minimalist, and I can separate the actual writing from the editing.
:100: :+1:

**Comment by mruiz42** [comment]
Read CONTRIBUTION.md, feature requests are not being looked at unless it's a translation. Even if you implement it yourself and make a pull request, it won't be added most likely. My interpretation. I thought of adding a feature in the past but I don't think my PR would be accepted. Kind of disappointing but nonetheless I like this software project a lot.

Alternatively, I'm sure you could find something that imitates typewriter noise as a 3rd party on each key press that maybe even will activate on a per-application basis. Also, how about using a mechanical keyboard?

**Comment by Floessie** [comment]
[This one](https://github.com/dsebastien/typewriter-sounds) looks fun... (X11 only)

**Comment by abenson** [comment]
Similar to another I've used, [bucklespring](https://github.com/zevv/bucklespring).

**Comment by mzsoli** [comment]
> Similar to another I've used, [bucklespring](https://github.com/zevv/bucklespring).

Thank you very much! :-)
Very good app. I was looking for something like this .
