### ISSUE TITLE
Don't see the highlighted words found in dark mode

### ISSUE THREAD

**Issue by Uhter** [wereturtle/ghostwriter#695]
Hi everybody.

[sorry for my english]
In dark mode, I don't see well highlighted words found with the find feature. The highlight color is not clear enough.

**Setup:**
 - ghostwriter 2.0.2-1
 - Manjaro Xfce (GNU/Linux)

**To Reproduce:**
1. toggle dark mode (in bottom right corner)
2. find <kbd>Ctrl</kbd>+<kbd>F</kbd>
3. type any word from the file
4. press <kbd>F3</kbd> or click "Highlight matches" on the left of find bar.

Here's what I get by searching "status" word:

[![tmpGH1.png](https://i.postimg.cc/rpqdFcbk/tmpGH1.png)](https://postimg.cc/K1sc0Xxq)

If I toggle to light mode, I see very well highlightings:

[![tmpghlight.png](https://i.postimg.cc/qRkZLt55/tmpghlight.png)](https://postimg.cc/bGBTYv8x)

And if come back to dark mode, highlightings are OK expect one:

[![tmpgh2.png](https://i.postimg.cc/YCRXS29N/tmpgh2.png)](https://postimg.cc/4YKvLgpn)

Ghostwriter issue or maybe Qt issue on Xfce? I don't know.
Am I the only one?

**Comment by wereturtle** [comment]
Well I see them OK, so this is more of a personal preference thing.  You can duplicate the theme from the theme editor and tweak it if you want.  :)

**Comment by Uhter** [comment]
I did it. It's perfect now ;)
Thank you @wereturtle.
