### ISSUE TITLE
rtl in preview

### ISSUE THREAD

**Issue by ekm507** [wereturtle/ghostwriter#698]
**Platform:**
 - KDE neon User 5.23 (Plasma Desktop)

**ghostwriter installation:**
 - ghostwriter version [see Help->About in menu bar]:
 - ghostwriter 2.1.0  (installed with apt from official PPA)

**Describe the bug**

markdown preview does not show RTL or BiDi text properly. however, adding a `<div dir="rtl">` tag fixes the issue. but since it is not standard markdown tag, it should not be used.

**To Reproduce**
1. write any RTL or BiDi text. for instance:  
یک two سه چهار پنج
2. see the preview window.

**Expected behavior**
text should be shown in RTL.

**Seen behavior**
text is shown in LTR

**Screenshots**

![image](https://user-images.githubusercontent.com/13185969/145214941-7e67b6d0-2b85-41db-a794-9182396cd2c0.png)

**Additional context**
the program is surely able to render bidi text correctly. adding the `div` tag proves it.  
the problem is that it does not do it automatically.  
also the edit section shows everything correctly.

**Comment by wereturtle** [comment]
Well, if I export to HTML and open with Chrome or Chromium, it has the same issue.  Apparently the browser just needs that tag.  Now it would be nice if the Markdown processor itself would autodetect RTL and put the div tag in automatically.  However, I have no control over that.  Not even Pandoc does that.  What you can do for now is request that feature from the maintainer(s) for your favorite Markdown processor.  Pandoc's issue tracker is located [here](http://https://github.com/jgm/pandoc/issues).  I agree it would be a nice feature to have!
