### ISSUE TITLE
Some translation issues

### ISSUE THREAD

**Issue by NightSharp** [wereturtle/ghostwriter#701]
**Platform :**
 - Windows 10

**ghostwriter installation :**
 - 2.1.0
 - portable

**Describe the bug**
Several Similar cases. I will decribe them based on [ghostwriter_zh.zip](https://github.com/wereturtle/ghostwriter/files/7700494/ghostwriter_zh.zip) (Of course I speak Chinese)

1. Almost every items in Preferrence Dialog are not displayed as their translation ones, still the original ones.
2. text "Preview in dark mode" in themeselectiondialog.cpp don't have the corresponding translation items. Maybe it need to be wrapped with `tr()` .
3. Several Buttons' name can't be translated, such as "Yes", "No", "Save", "Disgard", "Cancel", "Close". It seems that they depend on another localization file instead of `ghostwriter_xx.qm` , because I can't find out these texts in the src file of ghostwriter.

**To Reproduce**

1. Just open the Preferrence Dialog and it's obvious.
2. Open "Settings" > "Theme...", It's on the left bottom corner.
3. Many places, such as **Export** dialog, **Theme** diaglog, and **Close and Save** dialog, etc.

**Expected behavior**
They should all displayed as what they are translated.

**Screenshots**
1. according to case 1
![2021-12-13 (3)](https://user-images.githubusercontent.com/9748063/145742053-65f972d4-a08d-4008-ac1f-bf6ef034ee96.png)

2. according to case 2
![2021-12-13 (1)](https://user-images.githubusercontent.com/9748063/145742036-14c3f4d8-a7ae-4161-9737-d8c0f20064d4.png)

3. according to case 3
![2021-12-13](https://user-images.githubusercontent.com/9748063/145742028-bfdba2b0-f1cd-49a9-8075-b0cb96c97daa.png)
![2021-12-13 (2)](https://user-images.githubusercontent.com/9748063/145742043-7a422e05-49e7-4c51-8a6a-b8aec803983b.png)

**Additional context**
Nothing

**Comment by wereturtle** [comment]
Qt provides its own translation files for common UI text such as "OK" and "Cancel".  See if you can locate a Chinese translation file from the Qt installation itself.  Unfortunately, I am not the person who does the Windows platform bundling, so this is probably an issue where it was simply not included in the zip.
