### ISSUE TITLE
Autosave folder customisation

### ISSUE THREAD

**Issue by benji88i** [wereturtle/ghostwriter#706]
Hi there,

Sorry this is not an issue but I didnt know how to reach out for help

I am trying to customise where the backup (or autosave) filed are sent to.

We are getting a lot of random files in our documents directory (the default folder) and we would like to change if possible the location where they are stored

![image](https://user-images.githubusercontent.com/68906758/146423018-7c1b59dc-f9fc-4dc4-814b-a4f6b402a2d3.png)

**Comment by mruiz42** [comment]
This is directly related to issue #696 and a fix has already been suggested. I agree, being able to set the location where documents are stored and named would be a nice feature.
