### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by fultonm** [wereturtle/ghostwriter#707]
**Platform (please complete the following information):**
Fedora 35 on Gnome on Wayland (default)

**ghostwriter installation (please complete the following information):**
2.1.0, installed from copr.fedorainfracloud.org/wereturtle/stable using ‘dnf ’
**Describe the bug**
When entering fullscreen mode using the full screen button on the bottom right, the window disappears. In the video recording provided, a black screen is shown but on my screen I see my desktop and background applications but I can't click on them. Pressing ESC returns Ghostwriter to a regular window and then it continues to work.

**To Reproduce**
1. Enter full screen

**Expected behavior**
The application goes full screen

**Screenshots**
Video: https://web.tresorit.com/l/pAdRk#LuGAoxpOoeK9IdBWwHm6NA

**Additional context**

**Comment by fultonm** [comment]
I just discovered if I go to Fullscreen, although the app disappears, if I close the window using the hotkey Super + Q, then reopen it, it will launch in full screen. I can use Esc to return to a regular window, but I cannot return to fullscreen without quitting in fullscreen and relaunching.

**Comment by wereturtle** [comment]
Qt does is not 100% working with Wayland.  As such, you may wish to report this issue to the Qt devs [here](https://bugreports.qt.io/secure/Dashboard.jspa).
