### ISSUE TITLE
MacOS 12 (Monterey) with Qt 6.2.2

### ISSUE THREAD

**Issue by houserockr** [wereturtle/ghostwriter#709]
I was able to compile gw with qt 6.2.2 (installed via homebrew) under MacOS 12.0.1.
I had to make minor changes to the `*.pro` file (e.g. `QMAKE_MACOSX_DEPLOYMENT_TARGET = 12.0`) and several obvious changes due to the changes Qt API.
Especially things like `setMargin()` -> `setContentMargins()` and `setCodec()` -> `setEncoding()`.
Stuff like that.

It compiles and links well.

However, the call to `macdeployqt` in the `QMAKE_POST_LINK` fails as follows:
```
macdeployqt /Users/mef/Downloads/ghostwriter/build/release/ghostwriter.app 
ERROR: Cannot resolve rpath "@rpath/QtGui.framework/Versions/A/QtGui"
ERROR:  using QSet("/Users/mef/Downloads/ghostwriter/build/release/lib")
```
Which repeats itself for each of the qt modules.
I get that `macdeployqt` is probably responsible for copying all the necessary qt libs into the application's lib directory. But what's its problem?

Compiler:
```
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
macdeployqt is linked as follows:
```
/opt/homebrew/bin/macdeployqt -> ../Cellar/qt/6.2.2/bin/macdeployqt
```
Also, the signature of the app seems to be wrong:
```
pkgutil --check-signature build/release/ghostwriter.app/
Package "ghostwriter.app":
   Status: package is invalid (checksum did not verify)
```
But I managed to sign it with my dev-id
```
$ codesign --force --verify --verbose --sign "Apple Development: anon@foo.com (ABCDEFG)" build/debug/ghostwriter.app/
build/debug/ghostwriter.app/: replacing existing signature
build/debug/ghostwriter.app/: signed app bundle with Mach-O thin (arm64) [io.github.wereturtle.ghostwriter]
```
Which doesn't help. The app still gets an immediate SIGKILL.
However, it seems to deploy the application just fine.
`ls -1 build/debug/ghostwriter.app/Contents/Frameworks/` yields:
```
QtConcurrent.framework
QtCore.framework
QtGui.framework
QtNetwork.framework
QtOpenGL.framework
QtPositioning.framework
QtPrintSupport.framework
QtQml.framework
QtQmlModels.framework
QtQuick.framework
QtSvg.framework
QtWebChannel.framework
QtWebEngineCore.framework
QtWebEngineWidgets.framework
QtWidgets.framework
libb2.1.dylib
libbrotlidec.1.dylib
libdouble-conversion.3.dylib
libfreetype.6.dylib
libglib-2.0.0.dylib
libgthread-2.0.0.dylib
libhunspell-1.7.0.dylib
libicudata.69.dylib
libicui18n.69.dylib
libicuuc.69.dylib
libintl.8.dylib
libjasper.4.dylib
libjpeg.9.dylib
libmd4c.0.dylib
libpcre.1.dylib
libpcre2-16.0.dylib
libpng16.16.dylib
libtiff.5.dylib
libwebp.7.dylib
libwebpdemux.2.dylib
libwebpmux.3.dylib
```
The bundle is about 260mb (release) and 413mb (debug)

When I try to start the application from the command line, it immediately receives SIGKILL.
```
$ ./build/debug/ghostwriter.app/Contents/MacOS/ghostwriter 
Killed: 9
$
```
`otool` yields
```
$ otool -L ./build/debug/ghostwriter.app/Contents/MacOS/ghostwriter
./build/debug/ghostwriter.app/Contents/MacOS/ghostwriter:
	@executable_path/../Frameworks/QtSvg.framework/Versions/A/QtSvg (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtWebEngineWidgets.framework/Versions/A/QtWebEngineWidgets (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtPrintSupport.framework/Versions/A/QtPrintSupport (compatibility version 6.0.0, current version 6.2.2)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 54.0.0)
	@executable_path/../Frameworks/QtWidgets.framework/Versions/A/QtWidgets (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtWebEngineCore.framework/Versions/A/QtWebEngineCore (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtQuick.framework/Versions/A/QtQuick (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtOpenGL.framework/Versions/A/QtOpenGL (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtGui.framework/Versions/A/QtGui (compatibility version 6.0.0, current version 6.2.2)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 244.119.0)
	@executable_path/../Frameworks/QtConcurrent.framework/Versions/A/QtConcurrent (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtQmlModels.framework/Versions/A/QtQmlModels (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtWebChannel.framework/Versions/A/QtWebChannel (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtQml.framework/Versions/A/QtQml (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtNetwork.framework/Versions/A/QtNetwork (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtPositioning.framework/Versions/A/QtPositioning (compatibility version 6.0.0, current version 6.2.2)
	@executable_path/../Frameworks/QtCore.framework/Versions/A/QtCore (compatibility version 6.0.0, current version 6.2.2)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.14.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by houserockr** [comment]
I had some minutes to spare so I tried again and it finally works.
First I found that code signing should be done as follows:
`codesign --deep -f -s "Developer ID Application: <company name> (<team id>)" --options "runtime" "<appName>.app/"`
However, when starting the app, it failed as soon as external shared libraries needed to be loaded. I didn't want to go as far as to sign all the qt libs from homebrew.

But then I thought, maybe the official binaries from qt.io will be signed "correctly" such that mac os can verify them.
And yes, that works!
With Qt 6.2.3.

Now I've got 22 modified files in my git stash.
The ones that I "ported" so that they work with Qt6.
Here's the list:

	modified:   3rdparty/QtAwesome/QtAwesome.cpp
	modified:   ghostwriter.pro
	modified:   resources/mac/macdeploy_helper.sh
	modified:   src/abstractstatisticswidget.cpp
	modified:   src/appmain.cpp
	modified:   src/colorschemepreviewer.cpp
	modified:   src/documenthistory.cpp
	modified:   src/documentmanager.cpp
	modified:   src/exportdialog.cpp
	modified:   src/htmlpreview.cpp
	modified:   src/mainwindow.cpp
	modified:   src/markdowneditor.cpp
	modified:   src/markdownhighlighter.cpp
	modified:   src/sidebar.cpp
	modified:   src/spelling/abstract_dictionary.h
	modified:   src/spelling/abstract_dictionary_provider.h
	modified:   src/spelling/dictionary_manager.cpp
	modified:   src/spelling/dictionary_provider_nsspellchecker.h
	modified:   src/spelling/spell_checker.cpp
	modified:   src/statisticsindicator.cpp
	modified:   src/stylesheetbuilder.cpp
	modified:   src/timelabel.cpp

Are you guys interested?

**Comment by wereturtle** [comment]
Yes, I am.  Please put in a pull request.  However, please be aware that I will have to do a slow code review and make sure that changes to make it work on Qt 6 are still backwards compatible with Qt 5.  So it might be a while before you see it merged.

**Comment by houserockr** [comment]
pull request #747

**Comment by synkathairo** [comment]
@houserockr interestingly I was able to get your fork to build on an M1 mac using the homebrew qt however it crashes with a runtime error

**Comment by houserockr** [comment]
> @houserockr interestingly I was able to get your fork to build on an M1 mac using the homebrew qt6 however it crashes with a runtime error

Yeah I know, I had the same problem and I described it in my last comment alongside with one possible solution. Problem is code signing.
