### ISSUE TITLE
Feature Request: Paste images from clipboard....

### ISSUE THREAD

**Issue by frohro** [wereturtle/ghostwriter#712]
I'm looking for a good markdown editor for my daughter to use taking notes, and like a lot of the features of ghostwriter, but she really needs to paste images from here clipboard into a document, and the only way to do that now is to save them to disk and then drag and drop them into her document or use the menu option.  It would be a lot faster to just paste.

Thanks for all your good work!

Rob

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
