### ISSUE TITLE
"British English (United Kingdom)" shows up twice in the list of dictionaries

### ISSUE THREAD

**Issue by Cxarli** [wereturtle/ghostwriter#719]
Version 2.0.1-1 from Arch repos, with hunspell-en_gb

**Describe the bug**
In the Dictionary dropdown, it shows British English twice with no visible distinction. 

**To Reproduce**
1. Go to Settings > Preferences > Spell Check
2. Open the dropdown

**Expected behavior**
Add a visual reason why there are two, so the user can pick the right one.

**Screenshots**
![image](https://user-images.githubusercontent.com/10348289/147865173-c70139ab-1df3-4aba-90de-c917cdb9dc50.png)

**Additional context**
`hunspell-en_GB` adds several dictionaries, two of which are `en_GB` and  `en_GB-large` which contains more words.

**Comment by wereturtle** [comment]
I find the proposed solution rather hacky (counting characters for the word "large") for a distro that should really just have one dictionary for the same language.  If there is a more standard way of sorting this out, I'd be willing to accept pull request for that instead.  Out of curiosity, does FocusWriter have the same issue?  The code in *ghostwriter* for dictionaries is lifted from FocusWriter.
