### ISSUE TITLE
Quick switch for language dictionary?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#72]
Dear @wereturtle,

Would it be possible to add a switch to quickly switch the active dictionary used for the spell check?

Thankfully,

~Robert

**Comment by wereturtle** [comment]
Look under Settings->Dictionaries... in the menu bar.  If the dictionary you want is missing in the list of available dictionaries, you will have to install the hunspell package for the desired language.  Just open the Software Center and search for "hunspell".  It will list a ton of dictionary packages for various languages.

**Comment by orschiro** [comment]
Dear @wereturtle,

  

I appreciate your response.

  

I am aware of the option to change the dictionary from the menu. However, I
would like to suggest a quicker option by placing a switch of language next to
the `Focus` button, for instance.

  

My rationale is that changing language is something very common and needed
frequently.

  

What do you think?

  

Thankfully,

  

~Robert

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 3 2016, at 6:28 pm, wereturtle &lt;notifications@github.com&gt; wrote:  

> Closed [#72](https://github.com/wereturtle/ghostwriter/issues/72).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/weretur
tle/ghostwriter/issues/72#event-612764904)![](https://github.com/notifications
/beacon/AAKbw2lyo5GtxNQ7IemPA8rXzYzRNF5Cks5pz-qzgaJpZM4H-h_M.gif)

**Comment by wereturtle** [comment]
I like the interface the way it is, because it's clean and simple.  Other competing editors likewise do not clutter the interface with such an option.  Sorry.

**Comment by orschiro** [comment]
Dear wereturtle,

  

I respect your design decision!

  

Of course the best would be if Ghostwriter could automatically support
multiple languages and thus would make it obsolete having to switch
dictionaries if one works in multiple languages.

  

However, I assume this is technically impossible, correct?  
  

Warmly,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 4 2016, at 9:05 pm, wereturtle &lt;notifications@github.com&gt; wrote:  

> I like the interface the way it is, because it's clean and simple. Other
competing editors likewise do not clutter the interface with such an option.
Sorry.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/weretur
tle/ghostwriter/issues/72#issuecomment-205450365)![](https://github.com/notifi
cations/beacon/AAKbwwqAyYuy9eSZeoyXkTRyu7jX5sV9ks5p0WD2gaJpZM4H-h_M.gif)

**Comment by wereturtle** [comment]
It would be a very difficult feature to implement, yes.

**Comment by orschiro** [comment]
Alright, let's close this one for now.

Thank you!

~Robert

**Comment by bipox** [comment]
My vote for something similar. 
It's 6 clicks to switch language. It doesn't seem much but it gets old fast. 
Maybe just an entry in the menu easier to access? Or in the little cog menu under the themes?

Anyway, thanks for your work, Ghostwriter is great!
