### ISSUE TITLE
MathJax Error

### ISSUE THREAD

**Issue by mmjvox** [wereturtle/ghostwriter#721]
**Platform:**
 - OS and version [opensuse 15.3]: 
 - Linux, Desktop Environment [kde plasma 5.18.6]:

**ghostwriter installation:**
 - ghostwriter version [2.1.1]:
 - Linux, installation type [build from source]:
 - I didn't installed yet, I'm in build state.
 - Qt 5.15.2
 - GCC 7.5

**Describe the bug:**
```
Error compiling js file: /.../ghostwriter-2.1.1/3rdparty/MathJax/bin/sre/mathmaps/es.js:2:26: error: Expected token `,'
build error 3rdparty_MathJax_bin_sre_mathmaps_es_js.cpp
```

**Comment by wereturtle** [comment]
I do not get this error on Fedora or Ubuntu.  It shouldn't even be compiling anything for MathJax, as these are just resource files to include in the executable.

What commands are you using to build?

**Comment by mmjvox** [comment]
I don't remember about that error and used commands.
About two week later i tried to build and built successfully. I don't remember if i pulled again or not.
