### ISSUE TITLE
2.1.1 Upgrade window flashes blank on mouse movements

### ISSUE THREAD

**Issue by devkingdom** [wereturtle/ghostwriter#723]
Today I ran a DNF upgrade on my system.  Lots of recent updates got applied including a step up to Ghostwriter 2.1.1.   Think my previous was a 2.0 so not that big of an update but since doing the upgrade the Ghostwriter window flashes constantly and its making it difficult to use.  I haven't figure out the root cause but here is what I have so far.

- Launch Ghostwriter 2.1.1 with md file.
- In dark mode
- Move mouse over text editor
- Blanks black then comes back showing previous words
- Seems to almost never happen when mouse not used
- Over time seems to become less frequent
- Tried downgrading to 2.0.2 and same issue on quick test
- Didn't flicker once while I was typing in web browser for this report and no focus on Ghostwriter.
- Doesn't seem tied to which MD file I open.  Was starting with a new one when first happened.

Fedora 35 Workstation
Up to date as of 6.45 January 9th
GNome 41.2 (Wayland)
i7 2.6Ghz CPU
64bit system
16G mem
1TB drive

**Comment by devkingdom** [comment]
Some more details after further use.  Turned off auto-save didn't change anything.  When it goes blank the menu bar vanishes to.  So it is everything inside the window shell.  Screenshot when it happens attached.

![Screenshot from 2022-01-12 16-40-39](https://user-images.githubusercontent.com/7296179/149225845-4d63228c-b483-4af2-9783-73abae5998f2.png)
.

**Comment by devkingdom** [comment]
Here is what the above looks like when not flashed out.
![Screenshot from 2022-01-12 16-44-06](https://user-images.githubusercontent.com/7296179/149226056-9d9faf5e-5e7e-4433-a8d4-390067e82061.png)

**Comment by devkingdom** [comment]
Some more observations
- Putting in full screen mode The entire thing vanishes and I see just my desktop.
- Switching to show the html render, when the screen blanks. the html pane stays and everything else vanishes.

Really stuck at this point and not sure where to go or what to try.

![Screenshot from 2022-01-12 16-58-57](https://user-images.githubusercontent.com/7296179/149229794-bb758d64-12de-426f-a4bf-0bed05e86874.png)

**Comment by wereturtle** [comment]
Does the issue occur if you switch from Wayland to X?

**Comment by devkingdom** [comment]
I tried but can't even get the system to load gnome when trying to switch to X.  just keeps crashing and going back to the log in screen.

**Comment by wereturtle** [comment]
Since this is like an X vs Wayland issue, there's not much I can do about it.  It sounds like you may need to do something to fix your system just to use X at all.  Bummer!
