### ISSUE TITLE
Wrong Font being resolved in Windows 10

### ISSUE THREAD

**Issue by barry-vt** [wereturtle/ghostwriter#725]
working on a document with indents and the indenting of text on the Windows 10 program sometimes changes the font similar to level2, where I want standard-sized body text.  Renders properly on my Ubuntu 20.04 LTS.  Dark theme is the windows, lighter theme is Linux.  the larger font is also carried over to the export to HTML. the third image is from Window 10 notepad+++ as i wanted to see if any other characters are embedded.

![image](https://user-images.githubusercontent.com/47467634/150854489-4aaf16f9-366e-442d-844a-2aaab52b472b.png)
![ghost mage001](https://user-images.githubusercontent.com/47467634/150854678-5bb82b7b-2181-4cd4-837b-a34872f85655.png)
![ghost mage002](https://user-images.githubusercontent.com/47467634/150858291-26e4f54b-bd05-4964-b6f6-fe54e506cab7.png)

**Comment by wereturtle** [comment]
There is an option in the settings to use large headings (or not).  Uncheck it:

![image](https://user-images.githubusercontent.com/10375170/154817069-6ca590a1-b92a-4f8f-9742-73a8227fc2ba.png)
