### ISSUE TITLE
ghostwriter does not render everything at once when an ascii art text box is used.

### ISSUE THREAD

**Issue by cdwijs** [wereturtle/ghostwriter#727]
**Platform (please complete the following information):**
Microsoft Windows [Version 10.0.18363.2037]

**ghostwriter installation (please complete the following information):**
 ghostwriter version: 2.10
 installation type full install

**Describe the bug**
When an ascii art block is used, not everything is rendered, it looks like about 260 chars are in a buffer somewhere, and need to be "pushed out" into the renderer by typing (or pasting) new characters.

**To Reproduce**
1. Start ghostwriter from the start menu
2. Click on "Bestand-nieuw" (File-new)
3. Paste this text at the left plane
`
```ditaa
 ┌──────────────┐          ┌──────────────┐          ┌─────────────┐ 
 │    Router    │   Wifi   │              │  Ethernet│   Laptop    │ 
 │     With     ◄──────────┤ Raspberry Pi ◄──────────┤   Without   │ 
 │   Internet   │          │              │    SSH   │  Internet   │ 
 └──────────────┘          └──────────────┘          └─────────────┘ 
```
`
4. Now only the top half of the ascii art is rendered in the right plane.
5. Type extra text in the left plane. With each typed character, one extra char of the ascii art is rendered. After the complete ascii art is rendered, at each keystroke one letter is displayed, but there's a lag of 264 characters.

**Expected behavior**
Everything is rendered at once, and everything is rendered, there are no characters missing.

**Screenshots**
Here a lot of extra characters are entered,  264 characters are missing in the right plane.
![image](https://user-images.githubusercontent.com/8469638/151828388-c199a5fd-89c0-4081-990c-bc7f67cde41d.png)

**Additional context**
The problem also occurs when "ditaa" is omitted.

**Comment by cdwijs** [comment]
This seems to be related to https://github.com/wereturtle/ghostwriter/issues/699 

In notepad++ I see ? chars at the arrowheads when I choose Encoding "ANSI"
![image](https://user-images.githubusercontent.com/8469638/151831596-c70fadcc-cce6-410c-8227-e69ed8c26d45.png)

When I replace the arrowheads with "<" ghostview renders the text correctly:
![image](https://user-images.githubusercontent.com/8469638/151831892-cf929791-fbe9-48af-9a69-d39f4b042130.png)

This is the UTF-8 encoded text file (I don't have a hex editor right now to figure out what UTF-8 code is the problem.)
[ascii-art.txt](https://github.com/wereturtle/ghostwriter/files/7972386/ascii-art.txt)

What extra info can I provide?

**Comment by cdwijs** [comment]
It turns out Ghostwriter can't deal with this character in ANSI encoding "|" (a6 in hex), it gets rendered as a question mark:
[only-ansi-chars-16-char-lag-ansi.md](https://github.com/wereturtle/ghostwriter/files/7977559/only-ansi-chars-16-char-lag-ansi.md)
![image](https://user-images.githubusercontent.com/8469638/151949809-2e649274-6ac6-4bab-9885-295253a73ea1.png)

Ghostwriter also rendered this file incorrectly, it has a lag of 16 chars:
[only-ansi-chars-16-char-lag.md](https://github.com/wereturtle/ghostwriter/files/7977577/only-ansi-chars-16-char-lag.md)
![image](https://user-images.githubusercontent.com/8469638/151950239-f3acc3b2-6954-425a-8568-bf41b84ae6f6.png)

**Comment by cdwijs** [comment]
I now realize I am running the portable version, not the full install. Sorry about intercommunicating that.

**Comment by wereturtle** [comment]
*ghostwriter* only works with UTF-8.  If you can convert the file you are pasting from into that format, that would probably solve your issue?
