### ISSUE TITLE
Will be the flathub version updated?

### ISSUE THREAD

**Issue by raffaem** [wereturtle/ghostwriter#728]
Will the [flathub version](https://flathub.org/apps/details/io.github.wereturtle.ghostwriter) be updated?

The version on flathub is 1.8.0 while the version here is 2.1.1

**Comment by wereturtle** [comment]
I'll consider updating it when the FlatHub devs stabilize what they consider to be acceptable appdata.xml formatting for their build validation.

**Comment by raffaem** [comment]
At this point I think you'll be better of by pulling it out from flathub altogether
