### ISSUE TITLE
Option to hide the menu bar permanently when NOT in full screen mode

### ISSUE THREAD

**Issue by shockproof22** [wereturtle/ghostwriter#729]
such a simple thing shouldn't take much time to implement and for a "distraction-free writer" menu bar is quite distracting in dark mode with it's white color
or at least give an option to change it's color 
a simple keyboard shortcut or menu toggle to hide it would be useful

**Comment by shockproof22** [comment]
i don't like going in full screen mode cause on switching back to ghostwriter it weirdly blinks and stutters most of the time.
Windows 11- version 2182 (OS build 22000.434)
ghostwriter version 2.1.1

**Comment by shockproof22** [comment]
also I like seeing my taskbar all the time so full-screen mode is not the solution here

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
