### ISSUE TITLE
Hemingway mode?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#73]
Dear @wereturtle, 

And another suggestion:

Aside the focus mode - which I like a lot - what do you think of adding a Hemingway mode that prevents the user to use the backspace key to erase content while composing?

Thankfully, 

~Robert :-)

**Comment by wereturtle** [comment]
Sure, that doesn't sound too hard to add.

**Comment by orschiro** [comment]
Great!

  

Looking forward to testing it. :-)

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 3 2016, at 6:49 pm, wereturtle &lt;notifications@github.com&gt; wrote:  

> Sure, that doesn't sound too hard to add.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/weretur
tle/ghostwriter/issues/73#issuecomment-205008872)![](https://github.com/notifi
cations/beacon/AAKbw8_A9XmZgAC7de1pl4DQ_ZFlc9kyks5pz--EgaJpZM4H-iLD.gif)
