### ISSUE TITLE
Does ghostwriter support shortcut for code block ?

### ISSUE THREAD

**Issue by L1so** [wereturtle/ghostwriter#730]
I like stackexchange markdown style, it has a specific shortcut for enabling code block.

![Peek 2022-02-04 12-11](https://user-images.githubusercontent.com/44594524/152475692-beaae9bb-c582-4106-bb5f-ca69d0e617ea.gif)

I try look anywhere on https://wereturtle.github.io/ghostwriter/quickrefguide.html, nothing on the text say a shortcut to invoke code block. Is there any hidden settings I need to enable, or is it not supported (yet) ?

Thank you!

**Comment by wereturtle** [comment]
Yes, select the lines of text you want to turn into a code block, and press the `TAB` key.  :)
