### ISSUE TITLE
Synchronize markdown editor and HTML preview automatically

### ISSUE THREAD

**Issue by JoseOlin** [wereturtle/ghostwriter#731]
First of all, **thanks for this amazing editor**. It's currently my preferred option for writing posts.

There are just a couple of details that I think would substantially improve the usability of ghostwriter.

Currently the viewer is only updated when something is written in the markdown section, however, especially when reviewing/editing, **it would be convenient if the update was done when scrolling, or at least when clicking on a paragraph**. 

It would also be great if **clicking on a paragraph in the previewer would take you to the same paragraph in the editor**. 

Thanks in advance!

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
