### ISSUE TITLE
Store the size of the sidebar, the editing section and the preview section.

### ISSUE THREAD

**Issue by JoseOlin** [wereturtle/ghostwriter#732]
For most work, the sidebar can be very small, dividing the rest of the screen evenly between the edit section and the preview section; however these **dimensions are not saved when the program is closed**. Even hiding and showing the sidebar or HTML preview makes all sections revert to their default size.

Is it possible to activate an **option that stores the sizes for each section defined by the user**?

Thanks in advance.

**Comment by JoseOlin** [comment]
I just noticed that even minimizing and maximizing the app causes the custom dimensions to be lost

**Comment by JoseOlin** [comment]
Hi!

Was this solved or just dismissed?

**Comment by wereturtle** [comment]
Partially solved.  I don't agree with saving the widths of the editor and preview.  I prefer those to autosize to 50-50 for maximum convenience.  This is just for the sidebar.  Note  however that widgets do tend to expand to fill out relative sizes when the window is resized.  This is normal and OK.  But other than that, it should save and reload the last sidebar width upon exit/start.

**Comment by JoseOlin** [comment]
Okay.
Let's try it!

In my case it would be more useful to store the size of the 3 sections, since there are sessions that I use it mostly to write (15%, 70%, 15%) and others that I use it to edit visualize (15%, 35%, 50%).
 
I will try to make the modification. Knowing that it is done in Qt and since Qt Creator is my favorite IDE has encouraged me to give it a try.

Thanks again for your answer and for releasing this wonderful editor
