### ISSUE TITLE
Feature: Open Folder

### ISSUE THREAD

**Issue by erickod** [wereturtle/ghostwriter#733]
It would be nice if the GhostWriter could open a directory with markdown and show the markdown files of that directory and it's subdirectories in the sidebar.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
