### ISSUE TITLE
.cfg themes do not appear in chooser

### ISSUE THREAD

**Issue by CouldBeThis** [wereturtle/ghostwriter#734]
**Platform:**
 - Ubuntu 18.04
 - If Linux, Desktop Environment: XFCE4

**ghostwriter installation:**
 - ghostwriter version: 2.1.1
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: Installed via `synaptic`

**Describe the bug**

Themes from theme repo do not show up. 

**To Reproduce**

1. Close `ghostwriter`
2. Download `ghostwriter` theme repo, for example by `git clone git@github.com:jggouvea/ghostwriter-themes.git`

3. move all directories into `~/.config/ghostwriter/themes` 

4. Open `ghostwriter`

5. Go to `Settings` > `Themes`

6. No new themes available.

**Expected behavior**

Themes should be available once installed per instructions.

**Additional context**

* The ghostwriter wiki [directs](https://github.com/wereturtle/ghostwriter/wiki/Where-to-Get-More-Themes) to [`jggouvea/ghostwriter-themes`](https://github.com/jggouvea/ghostwriter-themes) for themes. 

* Wiki [instructs](https://github.com/wereturtle/ghostwriter/wiki/Theme-File-Format#file-location) 

> Theme files must be kept in a folder of their own inside the themes folder. The themes folder is located in one of the following locations, based on your OS:
> 
> ... 
> * Linux: /home/<your_user_name>/.config/ghostwriter/themes 
> 
> ... A theme is named by ghostwriter as the directory its configuration is in. So, if your create a directory called "Foo" and put a valid `theme.cfg` file inside it, ghostwriter will add a "Foo" theme to its theme menu. Any associated background image is also included in this folder.

* I verify that the directory structure is correct, for example, [`ghostwriter-themes/Gruvbox-Dark`](https://github.com/jggouvea/ghostwriter-themes/tree/master/Gruvbox-Dark) is located at `/home/username/.config/ghostwriter/themes/Gruvbox-Dark` and its contents is `theme.cfg`.

* In `ghostwriter` I created a new theme via the interface. This generated a file `/home/username/.config/ghostwriter/themes/text.json`

Has the theme format changed to `json`? If so is it not backward compatible? Can the old themes be straightforwardly converted?

thanks for the application!

**Comment by wereturtle** [comment]
I'm afraid the new theme format is in `json` and is not backwards compatible.  Sorry!

**Comment by dgl-dev** [comment]
So, to be clear, none of the themes in [jggouvea](https://github.com/jggouvea)
/
[ghostwriter-themes](https://github.com/jggouvea/ghostwriter-themes)

are usable? Correct?
