### ISSUE TITLE
ghostwriter does not render everything at once when an ascii art text box is used. 

### ISSUE THREAD

**Issue by cdwijs** [wereturtle/ghostwriter#736]
New issue, as i can't reopen https://github.com/wereturtle/ghostwriter/issues/727

Platform (please complete the following information):
Microsoft Windows [Version 10.0.18363.2037]

ghostwriter installation (please complete the following information):
ghostwriter version: 2.10
installation type portable

Describe the bug
When an ascii art block is used, not everything is rendered, it looks like about 260 chars are in a buffer somewhere, and need to be "pushed out" into the renderer by typing (or pasting) new characters.

To Reproduce

1) Start ghostwriter from the start menu
2) Click on "Bestand-nieuw" (File-new)
3) create a drawing in https://asciiflow.com/#/
4) past the ascii into notepad++ and confirm the encoding is UTF-8
![image](https://user-images.githubusercontent.com/8469638/154926773-6fe0a362-21c9-45ab-89d0-b38a497904f8.png)
5) copy from notepad++ and paste this text at the left plane
6) add the 3 backticks before and after the text
7) Observe only half of the image is rendered.
![image](https://user-images.githubusercontent.com/8469638/154927219-769ab8b5-f279-4536-b208-8a8745079562.png)

I can't see how this is working as intended.

**Comment by wereturtle** [comment]
Upon further investigation, this appears related to issue #699 .  It only happens in Windows, so it makes it difficult for me to debug.  However I suspect cmark-gfm is most likely the culprit.  If you can manage to build and install cmark-gfm on Windows and see if it gives the same output, that would be very helpful.

In the meantime, I will close this issue as a duplicate and you can continue to contribute to #699.
