### ISSUE TITLE
Pandoc not found - portable Windows version

### ISSUE THREAD

**Issue by DustyPane** [wereturtle/ghostwriter#738]
**Platform (please complete the following information):**
Windows 10 21H2

**ghostwriter installation (please complete the following information):**
 ghostwriter 2.1.1 portable

**Describe the bug**
Pandoc is installed into its default folder C:\Users\username\AppData\LocalPandoc
That path is added to both the user and system PATH variable.  Existence of pandoc.exe at that path has also been confirmed.
ghostwriter does not offer the option to switch the preview window from cmark-gfm to pandoc

**To Reproduce**
1. open Settings > Preview Options
2. click the markdown flavor dropdown
3. the list of markdown flavors only shows cmark-gfm
Alternatively:
1. open Settings > Export
2. click the markdown converter dropdown
3. the list of markdown flavors only shows cmark-gfm

**Expected behavior**
since Pandoc is installed and its installation path has been added to the PATH variable, ghostwriter should allow me to switch the markdown flavor / markdown converter from cmark-gfm to pandoc.

**Comment by wereturtle** [comment]
In the new 2.1.2 version, I have increased the wait time for checking if Pandoc can run. Please let me know if it is working now or if more tweaking is required.

Thanks!

**Comment by wereturtle** [comment]
Duplicate if #724
