### ISSUE TITLE
Impish Indri Release

### ISSUE THREAD

**Issue by friciwolf** [wereturtle/ghostwriter#745]
I was wondering the other day why my favourite markdown editor has not received any updates lately, even going as far as almost thinking the project was dead.

To my surprise it was only the newest build not being released through the PPA -- so could you provide us, non-LTS Ubuntu users with up-to-date impish builds?

**Comment by wereturtle** [comment]
The reason you are not seeing any further Impish builds is that Launchpad (and Canonical) stopped supporting that version.  To get newer builds, you will have to upgrade your Ubuntu version.  That, or follow the build instructions in the README file.  :)

**Comment by friciwolf** [comment]
Thanks for the prompt reply!
[Impish Indri](https://wiki.ubuntu.com/Releases) is the latest non-LTS Ubuntu release (version 21.10), which will be soon surpassed in a month by the new LTS release, Jammy Jellyfish (version 22.04), so there is no newer version.
Also, other devs (such as [TexStudio](https://launchpad.net/~sunderme/+archive/ubuntu/texstudio) support Impish too, which is why I was originally surprised ghostscript does not.
I could go ahead and compile the source code myself, however, other users might also want to get the newest and best version, hence this issue.
