### ISSUE TITLE
Ghostwriter is in Arch Linux official repositories

### ISSUE THREAD

**Issue by chromer030** [wereturtle/ghostwriter#746]
**Platform :**
 - Arch Linux KDE

**ghostwriter installation :**
From repository : https://archlinux.org/packages/community/x86_64/ghostwriter/

**Describe the bug**
It's not bug , some kind of requesting to edit README in order to add Arch Linux to supported Linux distroes.

**Additional context**
Ghostwriter is in Arch linux repo, please add it to supported list of Linux distros.
thanks for all your efforts.

**Comment by hugopl** [comment]
And I'm using it :smiley: 

I think this patch "fixes" this "issue" https://github.com/wereturtle/ghostwriter/pull/753

**Comment by wereturtle** [comment]
The README is directing users on where to get the latest release that I personally packaged before it even hits other distributions' repos. I should hope it goes without saying that users can install the app from their distro's package manager. Unfortunately, I am not the maintainer of the ArchLinux package, hence why I have no instructions in the README. I hope that clears things up. :)
