### ISSUE TITLE
Support for unsaved files? (Hot Exit feature)

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#75]
Dear @wereturtle,

Do you think it is useful to add support for "saving" unsaved files?

By this I mean preserving the content of a file that has not been saved locally yet and which content would be shown again on re-opening of the editor. 

This might be quite useful in situations in which one quickly wants to draft something, close the editor and continue at a later stage to work on it.

Thankfully,

~Robert

**Comment by wereturtle** [comment]
Postponing this feature for now, but I've backed up the progress I've made so far on the "hotexit" branch.  I'll get back to it when I have more time.  I just don't want to delay the launch of 1.4.0 any further.
