### ISSUE TITLE
Sidebar takes up half the screen and selection to hide sidebar isn't saved

### ISSUE THREAD

**Issue by ReaderGuy42** [wereturtle/ghostwriter#751]
When you open up the program the sidebar showing the outline of a .md file takes up more than half the screen.

**Platform (please complete the following information):**
 - OS and version [e.g. Ubuntu 18.04, Windows 10, MacOS Sierra]: Linux Mint 20.2
 - If Linux, Desktop Environment [e.g., Gnome, Plasma, Cinnamon, etc.]: Cinnamon

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 2.1.2
 - If Windows, installation type [e.g., portable or full install]: /
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: via the Mint repo

**Describe the bug**
Sidebar takes up more than half the screen.

**To Reproduce**
1. Open .md file
2. see huge sidebar
3. close sidebar
4. close editor
5. reopen file
6. sidebar is there again and still huge

**Expected behavior**
Editor should save sidebar size/if it's been turned off.

Thanks :)

**Comment by RobViren** [comment]
I have been noticing the preference for hiding the sidebar is not persisting either. Though in my case I can notice that a window snap to the side is causing the setting to change. I feel like it has been losing it at other times, but I do a lot of window snapping and assume the issue could be related to window size changes in general. 

System settings: https://termbin.com/h2j0
Version: 2.1.2

To Reproduce:
1. Open editor
2. Change preference to hide sidebar
3. Snap window to the side using either shortcut or mouse
4. Observe the return of the sidebar and a change to the setting toggle

**Comment by josephpconley** [comment]
Is there a config file or some other way to set these preferences on startup?

**Comment by OrdinaryMagician** [comment]
Confirming the bug here on Arch Linux as well. Started happening exactly as of 2.1.2.

**Comment by fn-ix** [comment]
Confirmed on 2.1.2 on Arch as well. I should add that the editor width isn't saved either: when the sidebar is closed, the editor automatically spans the window width.
