### ISSUE TITLE
Ghostwriter is available on the standard Fedora's dnf repositories

### ISSUE THREAD

**Issue by tleb** [wereturtle/ghostwriter#752]
**Platform (please complete the following information):**
 - OS and version: Fedora Linux 35 (Workstation Edition), `Linux fedora 5.16.14-200.fc35.x86_64 #1 SMP PREEMPT Fri Mar 11 20:31:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - If Linux, Desktop Environment: Fedora's default Gnome 3

**Describe the bug**

It seems that ghostwriter has been added to the default `updates` repo, at least on Fedora 35, but the README still recommends a Copr.

**To Reproduce**

```plain
$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"

$ dnf info ghostwriter
Available Packages
Name         : ghostwriter
Version      : 2.1.2
Release      : 1.fc35
Architecture : x86_64
Size         : 2.3 M
Source       : ghostwriter-2.1.2-1.fc35.src.rpm
Repository   : updates
Summary      : Cross-platform, aesthetic, distraction-free Markdown editor
URL          : https://github.com/wereturtle/ghostwriter
License      : GPLv3+ and CC-BY and CC-BY-SA and MPLv1.1 and BSD and LGPLv3 and MIT and ISC
Description  : Ghostwriter is a text editor for Markdown, which is a plain text markup
             : format created by John Gruber. For more information about Markdown, please
             : visit John Gruber’s website at http://www.daringfireball.net.
             :
             : Ghostwriter provides a relaxing, distraction-free writing environment,
             : whether your masterpiece be that next blog post, your school paper,
             : or your novel.
```

**Expected behavior**

Update the README to mention this. I did not send a PR because I was not sure if this was reserved to Fedora 35. [It seems](https://packages.fedoraproject.org/pkgs/ghostwriter/ghostwriter/) that the package is also available for Fedora 34. Should the README still mention the Copr repo? The staging Copr should probably stay ([the builds are failing](https://copr.fedorainfracloud.org/coprs/wereturtle/stable/builds/) though).

**Comment by wereturtle** [comment]
The README is directing users on where to get the latest release that *I* personally packaged before it even hits other distributions' repos.  I should hope it goes without saying that users can install the app from their distro's package manager.  I hope that clears things up.  :)
