### ISSUE TITLE
Feature Request: Single tap new paragraph

### ISSUE THREAD

**Issue by TheAkashicTraveller** [wereturtle/ghostwriter#754]
It would be nice have a setting that makes pressing enter start a new paragraph, or just make two new lines as a shortcut, instead of having to press it twice every time.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
