### ISSUE TITLE
Settings -> Stylesheets 

### ISSUE THREAD

**Issue by tridral** [wereturtle/ghostwriter#755]
I am using Ghostwriter v1.8.0 to edit markdown for Pandoc and it has the option of referencing a stylesheet to help with its rendering
The option is found under

Settings -> Stylesheets

My wife is using Ghostwriter v2.0.0-rc and there is no option 'Settings -> Stylesheets'.  (all the other Settings menus are available)

I would like to be able to reference a Stylesheet from v2 of ghostwriter.  How do i do this?

Thank you!

**Comment by wereturtle** [comment]
This feature was removed to instead dynamically theme the HTML preview to match the editor's chosen theme.  What I had in mind was that the live preview is really there to verify that the Markdown syntax is correct, not to preview an entire website.

**Comment by tridral** [comment]
Thank you very much for your reply.

We have found ghostwriter to be a very good markdown editor. The preview
feature - using the stylesheet - was most useful. If it could  ever be
re-enabled as an option we would greatly appreciate it.

'ö-Dzin




འོད་འཛིན་དྲི་བྲལ
'ö-Dzin Tridral
[image: https://]about.me/tridral
<https://about.me/tridral?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
☸
*Drala Jong Appeal - creating a Buddhist retreat centre in Wales:
https://www.drala-jong.org/ <https://www.drala-jong.org/> *☸

☸ Achos pan ddaw y Pedwar Marchog i ofyn a roist ti o dy gyfan - fydd gen
ti ddim esgus - Meinir Gwilym ☸
