### ISSUE TITLE
Unexpected behaviour of "\" character in LaTeX code.

### ISSUE THREAD

**Issue by scavi-github** [wereturtle/ghostwriter#756]
**Platform (please complete the following information):**
 - OS: Windows 10

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 2.1.1 (portable)

**Describe the bug**
Within LaTeX blocks, in some cases, the `\` character currenlty only works if it is escaped (i.e. `\\`), which breaks standard LaTeX syntax.
- In most LaTeX commands, `\` works correctly, e.g.: `\alpha`, `int`, ...
- Some examples of commands that do _not_ work correctly: `\\`, `\,`, `\;`, `\!`.

**To Reproduce**
```
$$
a
\\
b
$$
```
does not render a new line in-between a and b.

**Expected behavior**
The `\` should not be required to be escaped within LaTeX code.

**Comment by wereturtle** [comment]
This is probably a MathJax thing, which is really the only LaTeX supported in ghostwriter.  You can see for yourself in the MathJax live demo [here](https://www.mathjax.org/#demo).  The demo does not render the newline either.

I would suggest submitting an issue report to the MathJax devs.
