### ISSUE TITLE
Compose key don't work

### ISSUE THREAD

**Issue by jjsarton** [wereturtle/ghostwriter#757]
ghostwriter 2.1.2 on fedora 35 XFCE

Entering characters with the compose key (Multi_key) don't work.

For example typing [compose-key] [s] [s] should be recognized as 'ß'. Within ghostwriter I get 'ss'.

**Comment by wereturtle** [comment]
I am on Fedora 35 KDE but cannot replicate this issue.  My compose key is able to produce the correct characters in ghostwriter.  It could be some sort of Qt configuration thing.  To check, you could try installing and opening another Qt application such as Kate and seeing if the compose key is working there.  If not, I'd suggest submitting a bug report to the [Qt devs](https://bugreports.qt.io).  If other Qt apps work well under XFCE, then I'm stumped and would like to know if others can reproduce this issue.  I will leave this issue open until we know more.

**Comment by jjsarton** [comment]
Thank for your answer, while installing and trying Kate, the same problem occurred. 
The reason what that I had an own ~/.XCompose file. I had to insert a further line on the top of this file.
``
include "%L"
``
With this line QT allow entering from composed  characters.
