### ISSUE TITLE
Feedback Request: Insert Headings Shortcuts

### ISSUE THREAD

**Issue by magrubertone** [wereturtle/ghostwriter#758]
Hi! Have just started using ghostwriter and am really liking it so far. But one thing that I'm instantly missing is having shortcuts to insert different levels of headings. In the other two markdown writers I've used, Macdown and Typora, the shortcuts were something like: (ctrl/cmd)+1, 2....6 = #, ##.....######. It was just really quick and handy. This could possibly exist already so apologies if that's the case, couldn't find it in the program or docs though!

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
