### ISSUE TITLE
Is it possible to Disable Meta for UTF-8? Is this a bug?

### ISSUE THREAD

**Issue by planetahuevo** [wereturtle/ghostwriter#760]
**IMPORTANT NOTICE**:  Please do NOT use the issue tracker for new feature requests.  Only bug reports or troubleshooting requests are being accepted at this time.  For details, please see the [contributing guidelines](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md).

**Platform (please complete the following information):**
Windows 10.

**ghostwriter installation (please complete the following information):**
 - ghostwriter version 2.1.2 just donwloaded
 - If Windows, installation portable

**Describe the bug**
I am having this problem##286 https://github.com/wereturtle/ghostwriter/issues/286  when exporting the HTML, but my problem is the meta header.
If I remove the meta header, everything looks fine, both in chrome and firefox. 
With the meta header,  they are displayed as  «?». 
If I take the file, with the meta header (or without) and edit it with Sublime text editor and then change the encoding to UTF-8, everything works as expected on any browser with any meta. 
So I am not sure where the problem is but the export html by default does not provide a clean html that can be used without any modification. 

**To Reproduce**
1. Create a text with Spanish characters like á or ñ or é íóú
2. Go to  export
3. Export to html. 
4. open in chrome or firefox

**Expected behavior**
To be able to use HTML on other browsers without any interaction with the file.

** Additional Note**
The file is encoded as utf-8 or at least that is what the text editor say, but those characters are not, so reencoding fix the issue.

Thanks!

**Comment by wereturtle** [comment]
I presume you are using the built-in Markdown processor, cmark-gfm?  This processor isn't the best for producing standalone documents.  I recommend you install Pandoc.  I believe it should solve your unicode issue by putting in the meta header for you.  (Recall that most Markdown processors assume you'll be copying/pasting snippets of HTML for your blog or whatever rather than producing a standalone HTML page.)

**Comment by planetahuevo** [comment]
The meta code is there and that is the problem. 
If I remove the meta code, it works.
If I do not remove the meta code but do the proper encoding of the texts on utf8, it works. 
I am using the windows installation, so no idea how to install pandoc, and it should not be necessary, as the easy solution is not to add any meta into the html. 
Can we disable that "meta" somehow? 
Thanks

**Comment by wereturtle** [comment]
This is cmark-gfm that creates the meta tag for use with standalone HTML documents.  I cannot reproduce your issue, however.  The characters you provided show up fine for me in Chrome with the meta tag in the HTML file.

A workaround you can try is going to the menu bar -> Edit -> Copy as HTML.  Then paste into an empty HTML file.  There will be no header/body tags, however.  It will just be an HTML snippet.  But it sounds like that's your use case anyway.

**Comment by 0x263b** [comment]
The issue is on Windows when exporting using the default settings (`cmark-gfm`) it adds the below meta tag which says the charset is `utf-8` when it needs to be `windows-1252`

```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```
