### ISSUE TITLE
No contact info available

### ISSUE THREAD

**Issue by somas95** [wereturtle/ghostwriter#761]
There is no contact info available, which would be nice to have in case anyone wants to get in contact with the maintainers. In my case I would want to discuss several things as the maintainer of another markdown editor app (which btw is credited in here as uberwriter, but it changed name! I'll open another issue regarding that), and a bugtracker may not be the best place to have such discussions

**Comment by wereturtle** [comment]
I prefer my privacy.  I hope you understand.  There's the new GitHub discussions tab if you want to start a discussion there.
