### ISSUE TITLE
[Suggestion] Enable Printing directly from GhostWriter

### ISSUE THREAD

**Issue by Mossy93** [wereturtle/ghostwriter#763]
I would love to be able to print directly from GhostWriter. Aside from that I love this program.

**Comment by wereturtle** [comment]
Thank you for your interest!  Unfortunately, I am not accepting new feature requests at this time. 
 Please read the [Contributing guide](https://github.com/wereturtle/ghostwriter/blob/master/CONTRIBUTING.md) for further details.
