### ISSUE TITLE
Question: Is there a way to add "config" / "profile" /... to customize exported HTML?

### ISSUE THREAD

**Issue by dgl-dev** [wereturtle/ghostwriter#768]
# Question
Is there a way to add "config" / "profile" /... to customize exported HTML?

I will be using ghostwriter to write KDP books

I need to "imbed" fonts, styles, ... in the generated HTML 

I really, really, ... don't want to edit the HTML before converting it to PDF

**Comment by wereturtle** [comment]
Have you tried embedding the appropriate HTML tags into your Markdown document?

**Comment by wereturtle** [comment]
Closing this issue as there was no reply from the author after two weeks.
