### ISSUE TITLE
Visually linkifying URLs on export to PDF?

### ISSUE THREAD

**Issue by orschiro** [wereturtle/ghostwriter#77]
Dear @wereturtle,

Do you have any advice how I can visually linkify URLs on export to PDF using any of the Pandoc converters?

As of now, links are not underlined, nor shown in a different colour which makes them difficult to be identified as links. 

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14540992/0493a9e2-0288-11e6-8018-cf43a3310bc2.png)

**Comment by wereturtle** [comment]
Hmm, it's working for me.  The link is showing in the PDF when I use just the plain Pandoc option to export.

I'm using Linux Mint 17.3 (equivalent of Ubuntu 14.04), Pandoc 1.12.2.1 (straight from the repo), and Document Viewer 3.10.3 for my PDF viewer.

While the link does show up in blue in the PDF viewer, and has the correct URL in the tooltip when I hover my mouse over it, clicking on it isn't opening the web browser, but that's an issue with the PDF viewer.

If you're running an older version of Pandoc, it might explain your issue.  I'm not sure, though.  You could try installing a newer version of Pandoc and see if that helps.

![screenshot from 2016-04-15 08 21 50](https://cloud.githubusercontent.com/assets/10375170/14566182/4cb32a6c-02e3-11e6-97a4-e11d8b6933b2.png)

**Comment by orschiro** [comment]
Thanks for investigating!

The only thing I can think of is the different Pandoc version. I am using `1.17.0.2-1` which I downloaded from the [releases page](https://github.com/jgm/pandoc/releases).

I tried the same export options as you:  
![image](https://cloud.githubusercontent.com/assets/170947/14568918/fa88fff6-033b-11e6-8a2f-b8e08a34433d.png)

But neither Evince nor Chromium's built-in PDF reader show the link visually. I guess I will try your version of Pandoc now. 
![image](https://cloud.githubusercontent.com/assets/170947/14568936/0f0708e2-033c-11e6-8f68-acf912443114.png)

**Comment by orschiro** [comment]
Alright, problem solved! :-) 

I downgraded to `pandoc_1.13.2.1-dfsg-1build6_amd64.deb` and this one shows the link:

![image](https://cloud.githubusercontent.com/assets/170947/14569110/cd65c904-033c-11e6-9316-9192ed33be57.png)

I will pass this one on to the Pandoc developers. 

Thankfully,

~Robert

**Comment by wereturtle** [comment]
Whew!  Glad you found the solution!

**Comment by orschiro** [comment]
Dear @wereturtle,

Have you seen John's reply in the referenced issue? He suggests to do the following:

> Sure. Set
> 
> linkcolor: blue
> citecolor: blue
> urlcolor: blue
> toccolor: blue
> 
> in your YAML metadata. (Or set these variables using -V on the
> comand line, e.g. `-Vlinkcolor=blue`)

Can we apply this to Ghostwriter somehow?

Warmly,

~Robert

**Comment by wereturtle** [comment]
I'll see what I can do, but I think it will be awkward and inconsistent with how all the other file format exports are handled.

**Comment by orschiro** [comment]
@wereturtle, 

very appreciated, thanks!

Maybe an optional text config file to set advanced options like these?

~Robert

**Comment by orschiro** [comment]
Wow, thanks for fixing this @wereturtle!

~Robert
