### ISSUE TITLE
How to include custom CSS in viewer for Pandoc extensions (fenced divs and bracketed spans)

### ISSUE THREAD

**Issue by robertpetry** [wereturtle/ghostwriter#770]
**Platform:** Debian Linux version 11 (bullseye), XFCE desktop

**ghostwriter installation:**
2.0.2-2, installed from Debian bullseye backports repository

**Describe the issue:**
In later versions of Ghostwriter (>2.0) support for custom css files seems to have been removed from the viewer.  This is problematic because my project uses Pandoc's "fenced divs" and "bracketed spans" to extend the markup language.  I want these features to be rendered within the Ghostwriter viewer because I want  users to use Ghostwriter as their authoring tool and they need to be able to see these features in the viewer.  Without these features supported in the css they just appear blank or are otherwise ignored.   (Ultimately a custom Pandoc LUA writer is used to convert an author's work to the format used by a secondary project which utilizes the additional markup information.)

**To Reproduce**
I tried pointing to additional css files in the "css" lines in the metadata of my document to customize things but they only seem to be affecting the exported output, not the viewer.  Is there any way, with a standard installation of Ghostwriter to include custom css to support these Pandoc extensions for my project (and others)? 

**Expected behavior**
css files in document meta data (or elsewhere) should be included/includable in Ghostwriter viewer rendering.

**Additional context**
Recompiling isn't really an option for the end users I am envisioning -- the point of the project is to make an already complicated  piece of software more accessible by using Ghostwriter and Pandoc Markdown's fenced divs and bracketed spans.  As Ghostwriter is Pandoc-based, having the ability to support fenced divs and brackets spans, which are part of Pandoc Markdown, within the viewer is desirable.

**Comment by wereturtle** [comment]
A few questions:

1. Who exactly are these users?  Do you represent a company or university?
2. If the answer to #1 is that yes, you do indeed represent a company or university, may we discuss payment for the reintroduction of this feature?
3. If your users are not employees or students, why is forking the project a roadblock for you?
4. Have you experimented with embedding your CSS into your markdown file with the style tag? Or perhaps with the link tag?  I'm not sure what you mean by "metadata".  Is this a Pandoc extension to which you are referring?

**Comment by wereturtle** [comment]
I don't necessarily agree with every extension to Markdown Pandoc supports.  The point of Markdown was to hide the geeky HTML/CSS stuff as much as possible.  Have you considered cutting out PreTeXt and just using Pandoc to export to EPUB/PDF/whatever?  In my experience, it does make nice EPUB books out of the box.

Beyond that, I'm afraid I don't have time for new feature requests.
