### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by genericusername3** [wereturtle/ghostwriter#773]
**Platform:**
 - OS and version: Manjaro 
 - If Linux, Desktop Environment: Gnome 42.1

**ghostwriter installation:**
 - ghostwriter version: tested 2.1.2-1 (repos) and 2.1.3 (from AUR, current git state), can't these are not the versions from within ghostwriter since it doesn't start
 - If Linux, installation type: Manjaro repos and AUR; flatpak (2.0.1) works fine

**Describe the bug**
Ghostwriter does not launch. When in a Terminal, the following output appears:

    Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
    Using pandoc version 2.17.1.1
    Command "multimarkdown" is not available.
    Using cmark version 0.30.2
    Segmentation fault (core dumped)

**To Reproduce**
1. `ghostwriter`

**Expected behavior**
No segfault

**Additional context**
What other diagnostics should I do? I'm not sure if other devices running Manjaro are affected, or if this is the same segfault as in #772, since I don't get the 

    Unsupported modifier, resource creation failed.
    XXX: resource creation failed

messages

**Comment by wereturtle** [comment]
Are you using Wayland?  If so, please try switching to X.

**Comment by wereturtle** [comment]
Also, did you try doing what the Warning in your terminal output suggested?  Try typing the following in your terminal window:

    $ QT_QPA_PLATFORM=wayland ghostwriter &

**Comment by RonaldAJ** [comment]
I have the same problem. 
Both when installing:
```
$ sudo add-apt-repository ppa:wereturtle/ppa
$ sudo apt update
$ sudo apt install ghostwriter
```

and when building from source:
```
$ qmake -qt5
$ make
$ sudo make install
```
Details:
OS Ubuntu: 20.04.4 LTS on virtualbox
Gnome Version: 3.36.8
Windowing system: X11

**Comment by RonaldAJ** [comment]
For me installing using the ppa and then starting with:
`QT_QPA_PLATFORM=xcb ghostwriter &`
solves the problem.
And the latex gets rendered which was the reason to look into this.
