### ISSUE TITLE
Download page links to the wrong repo

### ISSUE THREAD

**Issue by JC3** [wereturtle/ghostwriter#779]
The Windows "64-bit portable" download link on this page:

https://wereturtle.github.io/ghostwriter/download.html#windows

Still links to the michelolvera repo at https://github.com/michelolvera/vs-ghostwriter/releases/latest, but it should instead probably link to https://github.com/wereturtle/ghostwriter/releases, since the Windows builds are here now and the other repo even states that it's deprecated in its readme.

Currently, because the download link goes to the other repo (and https://wereturtle.github.io/ghostwriter is linked from all over place), it's probably a safe bet that the overwhelming majority of Windows users are a few versions behind.

(Fwiw, I wouldn't have found the official wereturtle release link at all except I wanted to make an FR, so I ended up at the main github page in the michelolvera repo, noticed it was a fork with the "Issues" tab disabled, raised an eyebrow then poked around a little, and ended up here.)

**Comment by wereturtle** [comment]
Fixed!  Thanks for pointing this out.
