### ISSUE TITLE
Migrate from QtWebKit to QtWebEngine for Qt 5.6

### ISSUE THREAD

**Issue by wereturtle** [wereturtle/ghostwriter#78]
Qt has deprecated QtWebKit in version 5.6.  Migrate code to use QtWebEngine instead if Qt 5.6 or greater is being used to compile.  Use this [guide](https://doc-snapshots.qt.io/qt5-5.6/qtwebenginewidgets-qtwebkitportingguide.html) as a reference for the migration.

**Comment by wereturtle** [comment]
Postponed due to QtWebEngine not being mature enough to ensure a seamless switch.  Will wait at the very least until DOM traversal via a C++ API is implemented as it was for QWebKit.

**Comment by wereturtle** [comment]
Postpone again.  There is no package for QtWebEngine in either the Debian Stable or Ubuntu repository.  The libqt5webengine5 package is presently in Debian Testing and is slated for mainstream release in Debian 9 / Ubuntu 17.04.

**Comment by katafrakt** [comment]
Just FYI @wereturtle it's not possible to run Ghostwriter on MacOS with default Qt5 from Homebrew, as QWebKit is removed from there. There is a formula to install with QWebKit support, but it takes a couple of hours to compile (at least on MacBook Pro), so probably no one is going to do that.

I know that MacOS is not a primary platform target, so that's just an information to consider. Also, I think Ubuntu 17.04 has already been released. Not sure about Debian, though.

**Comment by wereturtle** [comment]
Hi @katafrakt, I've been experimenting with the [annulen fork of QtWebKit](https://github.com/annulen/webkit/releases), since I am in the same boat with Windows, and have been stuck on an old Qt 5 build ever since the Qt devs stopped shipping it prebuilt.  With Qt 5.9, the annulen QtWebKit is working gloriously.  I only had to drop in the prebuilt libraries into the right places, and *ghostwriter* was up and running.  So give that link I posted a try with the MacOS version.  Hopefully the Qt devs will soon incorporate this version of QtWebKit by default, prebuilt, in future Qt releases.  (That is ultimately the goal of that project.)

**Comment by iamandrewluca** [comment]
If someone gets problems when installing `qt` with
```
brew install qt --with-qtwebkit
```

Try this instead. This is last `qt` formula with `--with-qtwebkit` option
```
brew install qt@5.7 --with-qtwebkit
```

**Comment by pazos** [comment]
@katafrakt @iamandrewluca @wereturtle: brew devs added long stable support for qt5.5.1. You only need the bottle, no compilation involved.

`brew install qt@5.5`

I've tested this and works like a charm. Submitted a [wip] PR to add official mac support on #353

**Comment by tommyboylab** [comment]
I'm currently having issues installing either  Qt 5.7 or 5.5 with the above methods, I believe they have been removed from Homebrew. Any way to compile using the latest Qt or does anyone have a build of the application they are willing to share?

**Comment by a17r** [comment]
> Hopefully the Qt devs will soon incorporate this version of QtWebKit by default, prebuilt, in future Qt releases. (That is ultimately the goal of that project.)

How realistic is it at this point? I don't see much movement, in Gentoo we ultimately had to package a Qt5WebKit snapshot (not happy) and we consider it deprecated, openSUSE is another distribution not installing Qt5WebKit anymore by default.

**Comment by wereturtle** [comment]
@a17r Yeah, I don't think it's realistic, especially as the project seems to have come to a halt.  I've been experimenting with the Chromium version.  It will drop Soon (TM).  However, since Chromium is such a resource hog, I am also considering having the option (as much as it pains me due to maintenance overhead) of also using the QTextBrowser instead, even though it is far more limited.  I'd hate for ghostwriter to become as resource-hungry as an Electron app with no option to make it lighter.
