### ISSUE TITLE
Support desktop color scheme

### ISSUE THREAD

**Issue by mokazemi** [wereturtle/ghostwriter#780]
**Platform (please complete the following information):**
 - OS and version: Arch Linux
 - Desktop Environment: KDE Plasma
 - Display server: X11

**ghostwriter installation:**
 - ghostwriter version: 2.1.4

**Describe the bug**
When I set a accent color other than Breeze (Blue), some parts of application changes the color, but not most parts.

**To Reproduce**
1. Change accent color
2. Open ghostwriter
3. Check the colors

**Expected behavior**
I expect all parts of the program change colors and inherit color scheme (Selection highlight, left panel, scrollbar, etc)

**Screenshots**
![Screenshot_20220701_201553](https://user-images.githubusercontent.com/18334056/176928519-46e37ad7-7e56-4cd6-9b0a-d0b2f3c12df4.png)

**Additional context**
There could exist a theme, named "System theme" which uses system color scheme.

**Comment by wereturtle** [comment]
You could always...create your own theme?  :)
