### ISSUE TITLE
Incomplete nested list is formatted as header

### ISSUE THREAD

**Issue by char101** [wereturtle/ghostwriter#781]
**Platform (please complete the following information):**
 - OS: Windows 10

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 2.1.4
 - If Windows, installation type: portable

**Describe the bug**
Incomplete list with nested item that is indented manually is formatted as a heading.

**To Reproduce**
1. Create a list item `- list item`
2. Press enter
3. Press backspace twice to remove the automatic bulet
4. Press space twice then write `-`

**Expected behavior**
List item not formatted as heading.

**Screenshots**
![2022-07-05 22_29_01-New Issue · wereturtle_ghostwriter — Mozilla Firefox](https://user-images.githubusercontent.com/71255/177363991-77b103d1-edb0-449b-97b8-5e15943e6f26.png)

**Additional context**

**Comment by wereturtle** [comment]
Hi @char101 

This is expected behavior for CommonMark.  You can enter the same text into the live CommonMark demo [here](https://spec.commonmark.org/dingus/) and get the same result.  The reason it is doing that is because you left a single dash on the line after the list item.  The CommonMark parser thinks you want the list item to be a setext header.  Remove the dash or else put more text after it to turn it into another list item.

**Comment by char101** [comment]
Thank you for the explanation.

The commonmark about the setext header says this

> A [setext heading](https://spec.commonmark.org/0.29/#setext-heading) consists of one or more lines of text, each containing at least one [non-whitespace character](https://spec.commonmark.org/0.29/#non-whitespace-character), with no more than 3 spaces indentation, followed by a [setext heading underline](https://spec.commonmark.org/0.29/#setext-heading-underline). **The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph**: they cannot be interpretable as a [code fence](https://spec.commonmark.org/0.29/#code-fence), [ATX heading](https://spec.commonmark.org/0.29/#atx-headings), [block quote](https://spec.commonmark.org/0.29/#block-quotes), [thematic break](https://spec.commonmark.org/0.29/#thematic-breaks), [list item](https://spec.commonmark.org/0.29/#list-items), or [HTML block](https://spec.commonmark.org/0.29/#html-blocks).

Since the previous line is a list item, isn't it not a valid setext header?
