### ISSUE TITLE
Preview apparently gets confused with nesting when _ and {} appear inside equations delimited by $$

### ISSUE THREAD

**Issue by qudent** [wereturtle/ghostwriter#789]
I use Windows 10, Ghostwriter 2.1.1.

```
${s}_s$ isa^b $s_{c}$

$(s)_$ isa^b $s_{c}$

$s_s$ isa^b $s_{c}$

${s}_s$ isa^b $s_c$

$s_x$ isa^b $s_y$

$_$ isa^b $_$
```
yields the following:

![image](https://user-images.githubusercontent.com/94126637/180646574-55c29ad3-5cd1-46a6-bf5d-4f3947d8ed78.png)

Apparently, if there is a paragraph with 2 MathJax equations AND each of them contains an underscore AND the expression before the underscore in the first eq is in brackets AND the expression after the underscore in the second eq is in brackets, the system produces weird outputs apparently related to the hierarchy of deliminiters (renders the text between the equations as MathJax, doesn't render the text within the equations as MathJax). Note that paragraphs 3-5 render correctly.

**Comment by wereturtle** [comment]
What you're seeing is a common conflict between MathJax and Markdown.  If you aren't already, please try using Pandoc instead of the default cmark-gfm processor, as it tries to solve such conflicts.

**Comment by qudent** [comment]
This works better for me, thanks!

(although there is still intermittent trouble with the cursive rendering on the editor page, but I can't reproduce it right now).
