### ISSUE TITLE
Preview doesn't delete old versions of rendering when typing in a line containing cursive and MathJax

### ISSUE THREAD

**Issue by qudent** [wereturtle/ghostwriter#790]
Using Ghostwriter 2.1.1 on Windows 10.

I start with a file containing `_d_ s $a$ q`, i.e. containing first cursive and then MathJax. Then I type "k" at the end 3 times, and press backspace 3 times after that.

The result looks like this:

![image](https://user-images.githubusercontent.com/94126637/180647875-0d70a854-b71f-4345-911a-23d22c7fe955.png)

Apparently, the preview system rerenders everything after the start of the equation `$a$ qk` after a keypress. But it doesn't delete the previous rendering `$a$ q`, inserting the new result afterwards. So the result now looks like the rendering of `$a$ qk$a$ q`, and so on. The same happens when deleting characters.

Typing before the equation, in the same paragraph, seems to produce a similar effect:

![image](https://user-images.githubusercontent.com/94126637/180648034-14c7bd26-f61c-4665-bb4a-28f5edba82b9.png)

To reproduce the problem reliably, I need to reload the file from scratch.

The problem seems to occur even when I type in a new line (but in the same paragraph). When I type in a different paragraph, it is gone.

**Comment by wereturtle** [comment]
Yes, I've seen this issue.  Not sure what to do with it as MathJax is having a conflict with ReactJS.  (ReactJS is used to only update what changed in the source document in the browser preview.)  I'll leave this one open as a "bounty" (will pay in peanuts!).

**Comment by qudent** [comment]
I find this tool really helpful for my work, and would consider incentivizing this with actual Dollars if someone makes it go away.

**Comment by qudent** [comment]
Do I understand you correctly that you know exactly what the problem is? In my case, the cursive text in the beginning was necessary as well to trigger the bug.
