### ISSUE TITLE
No RPM Packages available

### ISSUE THREAD

**Issue by sysrich** [wereturtle/ghostwriter#80]
Hi there, I notice ghostwriter currently only supports Ubuntu PPA's

Is there any plans to add RPM packages? Specifically for openSUSE Leap, Tumbleweed, and Fedora?

The openSUSE Build Service (http://openbuildservice.org / http://build.opensuse.org) might be a useful tool for building ghostwriter for many distributions, rather than limiting it to just one.

**Comment by wereturtle** [comment]
Thanks for the suggestion.  I'll look into it.  In the meantime, you could theoretically grab the .deb package from the PPA website and then use `alien` to convert it to RPM.

**Comment by plusky** [comment]
Packages for openSUSE are available [here](https://build.opensuse.org/package/show/editors/ghostwriter)

**Comment by wereturtle** [comment]
Hi @plusky 

Thank you very much for making openSUSE packages!  I'll be sure to put a link to that in the release notes for 1.3.1.
