### ISSUE TITLE
Opening the editor for the first time shows "File backup failed"

### ISSUE THREAD

**Issue by ptrcnull** [wereturtle/ghostwriter#813]
**Platform:**
 - OS and version: Alpine edge
 - If Linux, Desktop Environment: sway
 - If Linux, display server: Wayland

**ghostwriter installation:**
 - ghostwriter version: 2.1.5
 - Installation type: Alpine testing repository
 - If using a private build, version of Qt used to build: 6.3.2

**Describe the bug**
When opening the editor for the first time without any config, it tries to copy a file that wasn't saved yet to `.backup`, then fails with "File backup failed; Unknown error". The latter seems to be caused by using `backupFile.error` rather than `file.error`, changed in b2f89207cbcb28dddcc50d3fc24a618e97a23486.

**To Reproduce**
1. Remove `~/.config/ghostwriter`
2. Open ghostwriter
3. Type anything

**Expected behavior**
It doesn't show the error.

**Comment by ljcoogan** [comment]
+1, I got the same bug after installing the Flathub version today
