### ISSUE TITLE
Math support ?

### ISSUE THREAD

**Issue by Menci** [wereturtle/ghostwriter#85]
Could you please add some math support, such as inline math $ 1 + 2 * 3 = 3 * 2 + 1 $ or

$$ \sum\limits_{i = 0} ^ {n - 1} a_i $$

you can use the math renderer MathJax, or not render math, just highlight the math tag syntax.

Thanks.

**Comment by wereturtle** [comment]
Hi Menci,

You can install [Pandoc](http://pandoc.org/) or [MultiMarkdown](http://fletcherpenney.net/multimarkdown/) for MathJax support.  

Issue #81 has further examples on how you would use MathJax with each of these Markdown processors.
