### ISSUE TITLE
Wait until word is complete until checking spelling

### ISSUE THREAD

**Issue by jondcoleman** [wereturtle/ghostwriter#89]
I find it distracting that words will get marked as incorrectly spelled while I am still typing them.  Would it be possible to only check after the word is complete?

**Comment by jondcoleman** [comment]
Wow, thanks for making this happen so quickly @wereturtle!  Do you have any idea when this would be put into a release?  Thanks!

**Comment by wereturtle** [comment]
You're welcome.

The 1.4.0 release should happen in a couple of weeks.  I'm waiting on all the volunteer translators to finish their translations.
