### ISSUE TITLE
Ability to close current file

### ISSUE THREAD

**Issue by dhbwmawhd** [wereturtle/ghostwriter#90]
Didn't find the ability to close the current file. Current workaround is selecting `File > New` from the menu.

**Comment by nonplayer** [comment]
Seconding this request. When using this program in conjunction with a git repo, it holds files open in a way that messes up commits sometimes. Being able to close the file would likely help with that.

**Comment by wereturtle** [comment]
I had intended to have ghostwriter be able to close the file by selecting `File -> New` from the menu bar.  It would duplicate the functionality of `File -> New` to add a `File -> Close` option.  Besides, this is a fairly common UI convention for text editors that only edit a single document at a time.  One notable example is Notepad (on Windows).

**Comment by suhr** [comment]
I have an another idea: temporally opened files. You run ghostwriter with a special cli option, and it doesn't save history for the file.

This is better than having to close files manually.
