### ISSUE TITLE
More default themes?

### ISSUE THREAD

**Issue by dhbwmawhd** [wereturtle/ghostwriter#91]
Would you consider adding more default themes out of the box?

I noticed the `Classic` themes that ship with *ghostwriter* differ slightly from Github's current default styles (see also https://github.com/primer).

Added Primer (Dark / Light) and Gruvbox (Dark / Light) via jggouvea/ghostwriter-themes#3.

**Comment by wereturtle** [comment]
Themes are a very personal touch, and I don't want to clutter the theme manager with too many default themes that various users might not like.  It's also very easy to make your own.  Just go to `Settings -> Themes` in the menu bar, and click on the `+` button.

The two Classic themes are actually based off of Byword's defaults.  However, the upcoming release, v1.4.0, will tweak those themes to use the color palette from the KDE Plasma 5 Breeze themes.
