### ISSUE TITLE
`<kbd>` tags unsupported

### ISSUE THREAD

**Issue by dhbwmawhd** [wereturtle/ghostwriter#97]
`<kbd>` tags for Github-style outputs unsupported. Any clues as to why?

**Comment by dhbwmawhd** [comment]
Compare `<kbd>Ctrl</kbd><kbd>C</kbd>` and <kbd>Ctrl</kbd><kbd>C</kbd>.

**Comment by wereturtle** [comment]
It looks like an oversight in the default Github stylesheet.  I'll add it for the upcoming release.  (FYI, if you make your own stylesheet to use, you'll have to be sure to style the kbd element to get the same effect.)
