### ISSUE TITLE
Image preview in the editor itself

### ISSUE THREAD

**Issue by tmr232** [wereturtle/ghostwriter#98]
It would be great to have the images show up in the editor, and now only in the HTML preview. 
I kinda like the way it is done in https://github.com/brrd/Abricotine, where you see the image itself, and if you click on it you get the markdown again.

**Comment by wereturtle** [comment]
Sorry, the text editor engine doesn't really handle that, and switching to a rich text editor to pull it off would be very time consuming.  It's a great idea, but it probably won't be me who does it, due to lack of time.
