### ISSUE TITLE
Image drag-and-drop into wrong location

### ISSUE THREAD

**Issue by tmr232** [wereturtle/ghostwriter#99]
When dropping an image into the editor, you see the cursor moving to the position of the mouse, but when you actually drop the image, it goes to the location of the cursor before the drag-and-drop. This is very confusing. I think it will be better if the drop will happen in the last position of the cursor, not the original.

**Comment by wereturtle** [comment]
Unfortunately, that's a defect with the Qt framework itself.  I would suggest filing a bug report over at <http://bugreports.qt.io> for the QPlainTextEdit class, which is what handles the drag-and-drop operation.
